//! The era's entity-type id->name table: hermetic checks over the committed
//! table, plus an `#[ignore]`d drift guard that regenerates it from the jar's
//! own `--reports` registry dump and asserts byte-for-byte equality.
//!
//! # One protocol, one dump
//!
//! The registry is dense and alphabetical, so any insertion renumbers
//! everything after it. That is what forces one table per protocol in the
//! multi-version eras below. This era serves a single protocol, so the
//! question does not arise — but the dump is still pinned by content hash so
//! a different version's dump swapped in under the same filename fails
//! loudly.
//!
//! The dump is the unmodified output of the jar's own data generator in its
//! `--reports` mode, run against the real `.cache/mc/1.19.4/server.jar` — an
//! authority, not a community dataset. The report's own `protocol_id` is the
//! id and its keys are already namespaced identifiers, so there is no casing
//! or prefixing judgement anywhere in this file.
//!
//! Regenerate the committed table after a data bump with:
//!
//! ```text
//! LODESTONE_REGEN=1 cargo test -p lodestone-v1-19 --test entity_types \
//!     committed -- --ignored --nocapture
//! ```

use std::fmt::Write as _;
use std::path::PathBuf;

use lodestone_v1_19::entity_types;
use lodestone_v1_19::PROTOCOL_1_19_4;

/// The 1.19.4 jar's registry dump — the source the committed table is
/// rendered from.
const DUMP: &str = include_str!("support/registries_1_19_4_jar.json");
/// That dump's own filename, for assertion messages.
const DUMP_FILE: &str = "registries_1_19_4_jar.json";

/// Path under `src/generated/` the rendered table is committed at.
const COMMITTED: &str = "src/generated/entity_types.rs";

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Parses `minecraft:entity_type` out of a `--reports` registry dump into a
/// sorted `(id, identifier)` table, asserting the ids are dense from zero.
fn parse_registry_entities(doc: &str) -> Vec<(i32, String)> {
    let value: serde_json::Value = serde_json::from_str(doc).expect("registries.json parses");
    let entries = value["minecraft:entity_type"]["entries"]
        .as_object()
        .expect("registries.json carries minecraft:entity_type entries");
    let mut pairs: Vec<(i32, String)> = entries
        .iter()
        .map(|(name, entry)| {
            let id = entry["protocol_id"]
                .as_i64()
                .expect("entry has an integer protocol_id") as i32;
            (id, name.clone())
        })
        .collect();
    pairs.sort_by_key(|(id, _)| *id);
    for (index, (id, _)) in pairs.iter().enumerate() {
        assert_eq!(
            *id as usize, index,
            "entity_type protocol ids are not dense from 0"
        );
    }
    pairs
}

/// Renders the committed table source from a parsed dump.
fn generate(pairs: &[(i32, String)]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo test -p lodestone-v1-19 --test entity_types -- --ignored`\n\
         // from tests/support/registries_1_19_4_jar.json (protocol 762 / Minecraft\n\
         // 1.19.4). DO NOT EDIT BY HAND.\n\
         // Regenerate with LODESTONE_REGEN=1 (see the test module docs).\n",
    );
    out.push_str(
        "//! Generated entity-type id->name table for protocol 762\n\
         //! (Minecraft 1.19.4).\n//!\n\
         //! Maps the unified numeric entity-type id space to canonical\n\
         //! `minecraft:*` identifiers. Consumed by [`crate::entity_types`].\n\n",
    );
    let _ = writeln!(out, "/// Number of entity_types type entries.");
    let _ = writeln!(out, "pub const ENTITY_TYPE_COUNT: usize = {};\n", pairs.len());
    out.push_str(
        "/// `(type id, canonical identifier)` pairs, sorted by id for binary search.\n",
    );
    let _ = writeln!(
        out,
        "pub static ENTITY_TYPES: [(i32, &str); {}] = [",
        pairs.len()
    );
    for (id, name) in pairs {
        let _ = writeln!(out, "    ({id}, \"{name}\"),");
    }
    out.push_str("];\n");
    out
}

/// The committed dump is the one the jar produces, by shape and by content.
#[test]
fn the_committed_dump_is_the_one_the_jar_produces() {
    let pairs = parse_registry_entities(DUMP);
    assert_eq!(pairs.len(), 124, "1.19.4's entity registry holds 124 types");

    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in DUMP.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    assert_eq!(
        hash, 0x1aeb_2d4a_6f67_8ab5,
        "tests/support/{DUMP_FILE} is not the dump this table was generated from"
    );
}

/// The committed table is exactly what the dump renders to.
#[test]
#[ignore = "regenerates a committed table; run with --ignored"]
fn committed_table_matches_dump() {
    let pairs = parse_registry_entities(DUMP);
    let rendered = generate(&pairs);
    let path = manifest_dir().join(COMMITTED);
    if std::env::var_os("LODESTONE_REGEN").is_some() {
        std::fs::write(&path, &rendered).expect("write generated table");
        println!("regenerated {}", path.display());
        return;
    }
    let committed = std::fs::read_to_string(&path).expect("committed table exists");
    assert_eq!(
        committed, rendered,
        "{COMMITTED} has drifted from its dump; regenerate with LODESTONE_REGEN=1"
    );
}

/// The protocol resolves through `table_for`, and the generated file's two
/// halves agree.
#[test]
fn the_protocol_resolves_a_self_consistent_table() {
    let table = entity_types::table_for(PROTOCOL_1_19_4);
    assert_eq!(table.len(), table.declared_len(), "generated len/count disagree");
    assert!(!table.is_empty());
    assert_eq!(table.len(), 124);
}

/// Spot values, each read out of the committed dump rather than out of the
/// table under test: several named types, the last entry, and one past it.
#[test]
fn named_ids_match_the_jar_dump() {
    let pairs = parse_registry_entities(DUMP);
    let table = entity_types::table_for(PROTOCOL_1_19_4);
    for probe in [
        "minecraft:allay",
        "minecraft:warden",
        "minecraft:camel",
        "minecraft:sniffer",
        "minecraft:player",
        "minecraft:zombie",
    ] {
        let Some((id, _)) = pairs.iter().find(|(_, name)| name == probe) else {
            panic!("{probe} is absent from the committed dump");
        };
        assert_eq!(
            table.entity_type_name(*id),
            Some(probe),
            "id {id} should be {probe}"
        );
    }
    let (last_id, last_name) = pairs.last().expect("registry is non-empty");
    assert_eq!(table.entity_type_name(*last_id), Some(last_name.as_str()));
    assert_eq!(
        table.entity_type_name(i32::try_from(pairs.len()).expect("fits")),
        None,
        "one past the end names no entity"
    );
}

/// The 1.19 additions are what separate this table from the era below's, so
/// their presence is the cheapest proof the right dump was used — and the
/// 1.17-era additions being at *different* ids here is the proof the two
/// tables are not interchangeable.
#[test]
fn the_1_19_additions_are_present_and_the_ids_below_have_moved() {
    let table = entity_types::table_for(PROTOCOL_1_19_4);
    let names: Vec<&str> = (0..i32::try_from(table.len()).expect("fits"))
        .filter_map(|id| table.entity_type_name(id))
        .collect();
    for added in [
        // 1.19 itself.
        "minecraft:allay",
        "minecraft:frog",
        "minecraft:tadpole",
        "minecraft:warden",
        // 1.19.3 and 1.19.4.
        "minecraft:camel",
        "minecraft:sniffer",
    ] {
        assert!(
            names.contains(&added),
            "{added} missing from the 1.19.4 registry"
        );
    }

    // `allay` sorts first alphabetically, so it takes id 0 and every id the
    // era below assigned has moved by at least one. Reading a 1.19.4 spawn
    // through a 1.17-era table would therefore name the wrong entity for
    // essentially every id — which is why this table is per-era data and not
    // shared.
    let pairs = parse_registry_entities(DUMP);
    assert_eq!(
        pairs.first().map(|(id, name)| (*id, name.as_str())),
        Some((0, "minecraft:allay")),
        "1.19's alphabetically-first addition must take id 0"
    );
}
