#!/usr/bin/env python3
"""Validate and prepare bounded large-parity mismatch diagnostics.

The Rust comparison writes an inventory only after authenticating the complete
manifest (and its v6/v7 full-digest sidecar).  This helper re-authenticates
that identity before a JVM oracle is asked to export any chunk bodies.  It is
deliberately independent of the comparator's generated bytes: a stale
inventory can never select a reference coordinate merely because its text
looks plausible.
"""

import argparse
import hashlib
import pathlib
import sys


HERE = pathlib.Path(__file__).resolve().parent
import importlib.util

spec = importlib.util.spec_from_file_location("large_parity_manifest", HERE / "large-parity-manifest.py")
manifest = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(manifest)

MAX_ROWS = 4096


def sha256_file(path):
    digest = hashlib.sha256()
    with pathlib.Path(path).open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def parse_inventory(path):
    lines = pathlib.Path(path).read_text(encoding="ascii").splitlines()
    required = {
        "schema",
        "manifest_sha256",
        "semantic_version",
        "dimension",
        "frozen_world_sha256",
        "geometry",
        "record_width",
        "kind",
        "mismatch_count",
    }
    if not lines or lines[0] != "schema=lodestone-large-parity-mismatch-v1":
        raise ValueError(f"{path}: unsupported mismatch inventory schema")
    fields = {"schema": "lodestone-large-parity-mismatch-v1"}
    row_start = None
    for index, line in enumerate(lines[1:], start=1):
        if line == "index\tcx\tcz\texpected_full_sha256\tactual_full_sha256":
            row_start = index + 1
            break
        key, separator, value = line.partition("=")
        if not separator or key in fields:
            raise ValueError(f"{path}: malformed inventory header at line {index + 1}")
        fields[key] = value
    if row_start is None or not required.issubset(fields):
        raise ValueError(f"{path}: incomplete inventory header")
    if set(fields) - required - {"sidecar_sha256"}:
        raise ValueError(f"{path}: unknown inventory header field")
    try:
        x_range, z_range = fields["geometry"].split(":")
        gx0, gx1 = (int(value) for value in x_range.split(".."))
        gz0, gz1 = (int(value) for value in z_range.split(".."))
        version = int(fields["semantic_version"])
        count = int(fields["mismatch_count"])
        width = int(fields["record_width"])
    except (ValueError, KeyError) as error:
        raise ValueError(f"{path}: malformed inventory scalar: {error}") from error
    if gx0 > gx1 or gz0 > gz1 or count < 0 or count > MAX_ROWS:
        raise ValueError(f"{path}: invalid geometry or bounded mismatch count")
    if len(fields["manifest_sha256"]) != 64 or len(fields["frozen_world_sha256"]) != 64:
        raise ValueError(f"{path}: identity fields must be SHA-256 hex")
    rows = []
    for line_number, line in enumerate(lines[row_start:], start=row_start + 1):
        columns = line.split("\t")
        if len(columns) != 5:
            raise ValueError(f"{path}: mismatch row {line_number} has {len(columns)} fields")
        try:
            row = (int(columns[0]), int(columns[1]), int(columns[2]), columns[3], columns[4])
        except ValueError as error:
            raise ValueError(f"{path}: malformed mismatch row {line_number}") from error
        if any(len(value) != 64 for value in row[3:]):
            raise ValueError(f"{path}: mismatch row {line_number} has a non-SHA-256 digest")
        rows.append(row)
    if len(rows) != count:
        raise ValueError(f"{path}: header says {count} mismatches, found {len(rows)}")
    return fields, (gx0, gx1, gz0, gz1), rows


def authenticated_rows(manifest_path, inventory_path, coordinate_output, packet_source=None, packet_output=None, frozen_root=None):
    manifest_path = pathlib.Path(manifest_path)
    inventory_path = pathlib.Path(inventory_path)
    fields, geometry, rows = parse_inventory(inventory_path)
    header, payload, dimension = manifest.read(manifest_path)
    version = header[1]
    if fields["manifest_sha256"] != sha256_file(manifest_path):
        raise ValueError("mismatch inventory is bound to a different manifest file")
    if int(fields["semantic_version"]) != version or fields["dimension"] != dimension:
        raise ValueError("mismatch inventory schema or dimension differs from manifest")
    if fields["frozen_world_sha256"] != header[19].hex():
        raise ValueError("mismatch inventory frozen-world identity differs from manifest")
    if frozen_root is not None:
        frozen_root = pathlib.Path(frozen_root)
        contract = "v7" if version == 7 else "v6" if version == 6 else "v2"
        stamp = frozen_root / f"lodestone-large-parity-materialization-{contract}-{dimension}.freeze.sha256"
        if not stamp.is_file():
            raise ValueError(f"sealed root is missing its {contract} {dimension} freeze stamp: {stamp}")
        if stamp.read_text(encoding="ascii").strip() != header[19].hex():
            raise ValueError("sealed root identity differs from the authenticated manifest")
    if geometry != (header[11], header[12], header[13], header[14]):
        raise ValueError("mismatch inventory geometry differs from manifest")
    expected_width = manifest.RAW_WIDTH if version in (6, 7) else manifest.WIDTH
    if int(fields["record_width"]) != expected_width:
        raise ValueError("mismatch inventory record width differs from manifest")
    expected_kind = "raw-packet" if version == 6 else "light-free" if version == 7 else "semantic"
    if fields["kind"] != expected_kind:
        raise ValueError("mismatch inventory kind differs from manifest")
    sidecar = None
    if version == 6:
        sidecar = manifest.read_packet_audit(manifest_path, header, payload, dimension)
    elif version == 7:
        sidecar = manifest.read_light_free_audit(manifest_path, header, dimension)
    if sidecar is not None:
        sidecar_path = manifest.packet_audit_path(manifest_path) if version == 6 else manifest.light_free_audit_path(manifest_path)
        if fields.get("sidecar_sha256") != sha256_file(sidecar_path):
            raise ValueError("mismatch inventory is bound to a different authenticated sidecar")
    seen = set()
    width = header[12] - header[11] + 1
    for index, cx, cz, expected, actual in rows:
        if not (0 <= index < header[15]):
            raise ValueError(f"mismatch inventory index {index} is outside the manifest")
        if (cx, cz) in seen:
            raise ValueError(f"mismatch inventory repeats coordinate ({cx},{cz})")
        seen.add((cx, cz))
        if (cx, cz) != (header[11] + index % width, header[13] + index // width):
            raise ValueError(f"mismatch inventory coordinate disagrees with index {index}")
        if expected == actual:
            raise ValueError(f"mismatch inventory row {index} is not a mismatch")
        if version == 6:
            authenticated = sidecar[index * manifest.WIDTH : (index + 1) * manifest.WIDTH].hex()
        elif version == 7:
            authenticated = sidecar[index * manifest.WIDTH : (index + 1) * manifest.WIDTH].hex()
        else:
            authenticated = payload[index * manifest.WIDTH : (index + 1) * manifest.WIDTH].hex()
        if expected != authenticated:
            raise ValueError(f"mismatch inventory expected digest differs at index {index}")
    coordinate_output = pathlib.Path(coordinate_output)
    coordinate_output.write_text(
        "index\tcx\tcz\n" + "".join(f"{index}\t{cx}\t{cz}\n" for index, cx, cz, _expected, _actual in rows),
        encoding="ascii",
    )
    if packet_source is not None or packet_output is not None:
        if fields["kind"] != "raw-packet":
            raise ValueError("packet selection is only available for raw-packet inventories")
        if packet_source is None or packet_output is None:
            raise ValueError("packet selection requires both --packet-source and --packet-output")
        packet_source = pathlib.Path(packet_source)
        packet_output = pathlib.Path(packet_output)
        packet_output.mkdir(parents=True, exist_ok=True)
        for _index, cx, cz, _expected, actual in rows:
            name = f"x{cx}_z{cz}.packet"
            source = packet_source / name
            if not source.is_file():
                raise ValueError(f"actual packet is missing for mismatch ({cx},{cz}): {source}")
            packet = source.read_bytes()
            if hashlib.sha256(packet).hexdigest() != actual:
                raise ValueError(f"actual packet digest differs for mismatch ({cx},{cz})")
            destination = packet_output / name
            if destination.exists():
                raise ValueError(f"duplicate actual mismatch packet: {destination}")
            destination.write_bytes(packet)
    return fields, geometry, rows


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", required=True)
    parser.add_argument("--inventory", required=True)
    parser.add_argument("--coordinates-out", required=True)
    parser.add_argument("--packet-source")
    parser.add_argument("--packet-output")
    parser.add_argument("--frozen-world-root")
    args = parser.parse_args()
    try:
        _fields, _geometry, rows = authenticated_rows(
            args.manifest,
            args.inventory,
            args.coordinates_out,
            args.packet_source,
            args.packet_output,
            args.frozen_world_root,
        )
    except (OSError, ValueError) as error:
        parser.exit(2, f"parity diagnostic refusal: {error}\n")
    print(f"authenticated mismatch inventory: {len(rows)} coordinates -> {args.coordinates_out}")


if __name__ == "__main__":
    main()
