//! Canonical game identities and measured behavior for selected data releases.
//!
//! Identities retain the 26.2 prefix. [`GameDataVersion`] selects wire mappings
//! and release-specific behavior independently of canonical identity.

#![forbid(unsafe_code)]

#[path = "generated/attribute_types.rs"]
pub(crate) mod generated_attribute_types;
#[path = "generated/behavior_versions.rs"]
pub(crate) mod generated_behavior_versions;
#[path = "generated/identity_versions.rs"]
pub(crate) mod generated_identity_versions;
#[path = "generated/block_movement.rs"]
pub(crate) mod generated_block_movement;
#[path = "generated/block_blast.rs"]
pub(crate) mod generated_block_blast;
#[path = "generated/block_entity_types.rs"]
pub(crate) mod generated_block_entity_types;
#[path = "generated/block_enum.rs"]
pub(crate) mod generated_block_enum;
#[path = "generated/block_items.rs"]
pub(crate) mod generated_block_items;
#[path = "generated/block_property_tables.rs"]
pub(crate) mod generated_block_property_tables;
#[path = "generated/block_registry.rs"]
pub(crate) mod generated_block_registry;
#[path = "generated/biome_enum.rs"]
pub(crate) mod generated_biome_enum;
#[path = "generated/block_solidity.rs"]
pub(crate) mod generated_block_solidity;
#[path = "generated/block_states.rs"]
pub(crate) mod generated_block_states;
#[path = "generated/collision_shapes.rs"]
pub(crate) mod generated_collision_shapes;
#[path = "generated/damage_types.rs"]
pub(crate) mod generated_damage_types;
#[path = "generated/data_component_types.rs"]
pub(crate) mod generated_data_component_types;
#[path = "generated/enchantments.rs"]
pub(crate) mod generated_enchantments;
#[path = "generated/entity_census.rs"]
pub(crate) mod generated_entity_census;
#[path = "generated/entity_dimensions.rs"]
pub(crate) mod generated_entity_dimensions;
#[path = "generated/entity_type_enum.rs"]
pub(crate) mod generated_entity_type_enum;
#[path = "generated/entity_types.rs"]
pub(crate) mod generated_entity_types;
#[path = "generated/face_occlusion.rs"]
pub(crate) mod generated_face_occlusion;
#[path = "generated/hardness.rs"]
pub(crate) mod generated_hardness;
#[path = "generated/item_enum.rs"]
pub(crate) mod generated_item_enum;
#[path = "generated/item_prototypes.rs"]
pub(crate) mod generated_item_prototypes;
#[path = "generated/items.rs"]
pub(crate) mod generated_items;
#[path = "generated/light_props.rs"]
pub(crate) mod generated_light_props;
#[path = "generated/menus.rs"]
pub(crate) mod generated_menus;
#[path = "generated/mob_effect_colors.rs"]
pub(crate) mod generated_mob_effect_colors;
#[path = "generated/mob_effects.rs"]
pub(crate) mod generated_mob_effects;
#[path = "generated/outline_shapes.rs"]
pub(crate) mod generated_outline_shapes;
#[path = "generated/particle_types.rs"]
pub(crate) mod generated_particle_types;
#[path = "generated/path_types.rs"]
pub(crate) mod generated_path_types;
#[path = "generated/potion_effect_ids.rs"]
pub(crate) mod generated_potion_effect_ids;
#[path = "generated/potion_effects.rs"]
pub(crate) mod generated_potion_effects;
#[path = "generated/potions.rs"]
pub(crate) mod generated_potions;
#[path = "generated/shade_brightness.rs"]
pub(crate) mod generated_shade_brightness;
#[path = "generated/snow_support.rs"]
pub(crate) mod generated_snow_support;
#[path = "generated/block_survival.rs"]
pub(crate) mod generated_block_survival;
#[path = "generated/sound_events.rs"]
pub(crate) mod generated_sound_events;
#[path = "generated/sound_types.rs"]
pub(crate) mod generated_sound_types;
#[path = "generated/tools.rs"]
pub(crate) mod generated_tools;
#[path = "generated/tools_26_3.rs"]
pub(crate) mod generated_tools_26_3;

pub mod attribute_types;
pub mod biomes;
pub mod block;
pub mod block_blast;
pub mod block_entity_types;
pub mod block_items;
pub mod block_properties;
pub mod block_solidity;
pub mod block_survival;
pub mod block_states;
pub mod collision_shapes;
pub mod damage_types;
pub mod data_component_types;
pub mod enchantment;
pub mod entity_census;
pub mod entity_disguise;
pub mod entity_dimensions;
pub mod entity_type;
pub mod entity_types;
pub mod face_occlusion;
pub mod hardness;
pub mod item;
pub mod item_rarity;
pub mod item_prototypes;
pub mod light_props;
pub mod menus;
pub mod mob_effects;
pub mod movement;
pub mod outline_shapes;
pub mod particle_types;
pub mod path_types;
pub mod potion;
pub mod shade_brightness;
pub mod snow_support;
pub mod sound_events;
pub mod sound_types;
pub mod tool;
pub mod villager_trades;
pub mod version;

pub use version::{GameDataVersion, StateFacts, StatePredicates};
