#!/usr/bin/env python3
"""Turn a capture_connection.py --raw-output JSONL into the Configuration
fixtures the hosted 26.3 server replays.

Writes one ``registry_data_<name>.hex`` per synchronized registry (in the
server's wire order) and ``update_tags_configuration.hex`` under
``crates/versions/26.3/fixtures/server-config``. Every file holds the exact
clientbound payload a vanilla 26.3 server wrote, with no packet id or length
prefix.

    python3 crates/versions/26.3/tests/capture_connection.py --raw-output /tmp/raw.jsonl
    python3 crates/versions/26.3/tools/gen_server_config_fixtures.py /tmp/raw.jsonl
"""
import json
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "fixtures/server-config"
REGISTRY_DATA = 7
UPDATE_TAGS = 14


def varint(body, i):
    value = shift = 0
    while True:
        byte = body[i]
        i += 1
        value |= (byte & 0x7F) << shift
        shift += 7
        if not byte & 0x80:
            return value, i


def hex_lines(body):
    text = body.hex()
    pairs = [text[i:i + 2] for i in range(0, len(text), 2)]
    return "\n".join(" ".join(pairs[i:i + 32]) for i in range(0, len(pairs), 32)) + "\n"


def header(what):
    return (
        f"# Raw clientbound {what} payload captured from the official 26.3 server\n"
        "# during Configuration. Payload only: no packet length or id prefix.\n"
        "# Regenerate: python3 crates/versions/26.3/tools/gen_server_config_fixtures.py\n"
    )


def main():
    raw = Path(sys.argv[1])
    OUT.mkdir(parents=True, exist_ok=True)
    order = []
    tags = None
    for line in raw.read_text().splitlines():
        record = json.loads(line)
        if record["state"] != "configuration":
            continue
        body = bytes.fromhex(record["body_hex"])
        if record["id"] == REGISTRY_DATA:
            length, i = varint(body, 0)
            name = body[i:i + length].decode()
            stem = "registry_data_" + name.removeprefix("minecraft:").replace("/", "_")
            (OUT / f"{stem}.hex").write_text(header(f"`registry_data` for `{name}`") + hex_lines(body))
            order.append((name, stem))
        elif record["id"] == UPDATE_TAGS:
            tags = body
    assert tags is not None and order, "capture holds no registries or tags"
    (OUT / "update_tags_configuration.hex").write_text(header("`update_tags`") + hex_lines(tags))
    (OUT / "registry_order.txt").write_text("".join(f"{name}\t{stem}\n" for name, stem in order))
    rows = "".join(
        f'    ("{name}", include_str!("../../fixtures/server-config/{stem}.hex")),\n'
        for name, stem in order
    )
    (OUT.parents[1] / "src/generated/server_config.rs").write_text(
        "// Generated by tools/gen_server_config_fixtures.py; do not edit.\n"
        "use lodestone_v26_2::dialect::ServerConfigFixtures;\n\n"
        "/// The Configuration payloads a 26.3 server replays, in its own order.\n"
        "pub static SERVER_CONFIG: ServerConfigFixtures = ServerConfigFixtures {\n"
        "    registries: &[\n" + rows + "    ],\n"
        '    update_tags: include_str!("../../fixtures/server-config/update_tags_configuration.hex"),\n'
        "};\n"
    )
    print(f"wrote {len(order)} registries and update_tags to {OUT}")


main()
