#!/usr/bin/env python3
"""Generate 26.2 canonical ↔ 26.3 wire ID runs from official reports."""

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[4]
OLD = ROOT / ".cache/mc/26.2/generated/reports"
NEW = ROOT / ".cache/mc/26.3/generated/reports"
OUTPUT = ROOT / "crates/versions/26.3/src/generated/id_translation.rs"


def read(path):
    return json.loads(path.read_text())


def state_ids(path):
    blocks = read(path)
    ids = {}
    seen = set()
    for name, block in blocks.items():
        for state in block["states"]:
            state_id = state["id"]
            key = (name, tuple(sorted(state.get("properties", {}).items())))
            if key in ids or state_id in seen:
                raise ValueError(f"duplicate block state in {path}: {key}")
            ids[key] = state_id
            seen.add(state_id)
    if seen != set(range(len(seen))):
        raise ValueError(f"non-contiguous block state IDs in {path}")
    return ids


def item_ids(path):
    entries = read(path)["minecraft:item"]["entries"]
    ids = {name: entry["protocol_id"] for name, entry in entries.items()}
    if set(ids.values()) != set(range(len(ids))):
        raise ValueError(f"non-contiguous or duplicate item IDs in {path}")
    return ids


def paired_ids(old, new, name):
    missing = old.keys() - new.keys()
    if missing:
        raise ValueError(f"{name} removed canonical keys: {sorted(missing)[:5]}")
    pairs = sorted((canonical, new[key]) for key, canonical in old.items())
    if [canonical for canonical, _ in pairs] != list(range(len(old))):
        raise ValueError(f"{name} canonical IDs are not contiguous")
    return pairs


def runs(pairs):
    out = []
    for canonical, wire in pairs:
        if out and canonical == out[-1][0] + out[-1][2] and wire == out[-1][1] + out[-1][2]:
            out[-1][2] += 1
        else:
            out.append([canonical, wire, 1])
    return out


def emit_table(name, rows):
    lines = [f"pub(super) const {name}: &[Run] = &["]
    lines.extend(f"    Run::new({canonical}, {wire}, {length})," for canonical, wire, length in rows)
    return "\n".join([*lines, "];", ""])


def generate():
    block_old = state_ids(OLD / "blocks.json")
    block_new = state_ids(NEW / "blocks.json")
    item_old = item_ids(OLD / "registries.json")
    item_new = item_ids(NEW / "registries.json")
    block_pairs = paired_ids(block_old, block_new, "block states")
    item_pairs = paired_ids(item_old, item_new, "items")
    block_runs = runs(block_pairs)
    block_inverse_runs = runs(sorted((wire, canonical) for canonical, wire in block_pairs))
    item_runs = runs(item_pairs)
    item_inverse_runs = runs(sorted((wire, canonical) for canonical, wire in item_pairs))
    if max(block_new.values()) > 65535 or max(item_new.values()) > 65535:
        raise ValueError("26.3 IDs exceed the generated u16 run representation")
    return "\n".join(
        [
            "// Generated by tools/gen_id_translation.py from the official 26.2 and 26.3",
            "// blocks.json and registries.json reports. Do not edit by hand.",
            "",
            f"pub(super) const WIRE_BLOCK_STATE_COUNT: u32 = {len(block_new)};",
            f"pub(super) const WIRE_ITEM_COUNT: u32 = {len(item_new)};",
            "",
            emit_table("BLOCK_STATE_TO_WIRE", block_runs),
            emit_table("BLOCK_STATE_FROM_WIRE", block_inverse_runs),
            emit_table("ITEM_TO_WIRE", item_runs),
            emit_table("ITEM_FROM_WIRE", item_inverse_runs),
        ]
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the generated table differs")
    args = parser.parse_args()
    text = generate()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text() != text:
            raise SystemExit(f"generated table differs: {OUTPUT}")
    else:
        OUTPUT.write_text(text)
    print(f"{OUTPUT}: {'verified' if args.check else 'generated'}")


if __name__ == "__main__":
    main()
