//! The era's entity-type id->name table: hermetic checks over the committed
//! table, plus an `#[ignore]`d drift guard that regenerates it from the jars'
//! own `--reports` registry dumps and asserts byte-for-byte equality.
//!
//! # Two dumps, one table — measured, not assumed
//!
//! The registry is dense and alphabetical, so any insertion renumbers
//! everything after it. That is what forces one table per protocol in the era
//! below, where 1.15's bee and 1.16's four nether mobs leave 102 / 103 / 108
//! entries agreeing only on ids 0..=3. Nothing was inserted across this era:
//! both committed dumps carry the same 113 entity types with the same ids.
//! [`both_dumps_agree_id_for_id`] re-derives that from **both** dumps rather
//! than trusting a comment, so a future jar refresh that does renumber fails
//! loudly instead of quietly serving 758 a 756 table.
//!
//! Both dumps are the unmodified output of Mojang's own data generator in its
//! `--reports` mode, run against the real `.cache/mc/<version>/server.jar` —
//! an authority, not a community dataset. The report's own `protocol_id` is
//! the id and its keys are already namespaced identifiers, so there is no
//! casing or prefixing judgement anywhere in this file.
//!
//! Regenerate the committed table after a data bump with:
//!
//! ```text
//! LODESTONE_REGEN=1 cargo test -p lodestone-v1-17 --test entity_types \
//!     committed -- --ignored --nocapture
//! ```

use std::fmt::Write as _;
use std::path::PathBuf;

use lodestone_v1_17::entity_types;
use lodestone_v1_17::{PROTOCOL_1_17_1, PROTOCOL_1_18_2};

/// The 1.17.1 jar's registry dump — the source the committed table is
/// rendered from.
const DUMP_1_17_1: &str = include_str!("support/registries_1_17_1_jar.json");
/// The 1.18.2 jar's registry dump. Not rendered from; used only to prove the
/// two protocols agree, which is what licenses one table.
const DUMP_1_18_2: &str = include_str!("support/registries_1_18_2_jar.json");

/// Path under `src/generated/` the rendered table is committed at.
const COMMITTED: &str = "src/generated/entity_types.rs";

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Parses `minecraft:entity_type` out of a `--reports` registry dump into a
/// sorted `(id, identifier)` table, asserting the ids are dense from zero.
fn parse_registry_entities(doc: &str) -> Vec<(i32, String)> {
    let value: serde_json::Value = serde_json::from_str(doc).expect("registries.json parses");
    let entries = value["minecraft:entity_type"]["entries"]
        .as_object()
        .expect("registries.json carries minecraft:entity_type entries");
    let mut pairs: Vec<(i32, String)> = entries
        .iter()
        .map(|(name, entry)| {
            let id = entry["protocol_id"]
                .as_i64()
                .expect("entry has an integer protocol_id") as i32;
            (id, name.clone())
        })
        .collect();
    pairs.sort_by_key(|(id, _)| *id);
    for (index, (id, _)) in pairs.iter().enumerate() {
        assert_eq!(
            *id as usize, index,
            "entity_type protocol ids are not dense from 0"
        );
    }
    pairs
}

/// Renders the committed table source from a parsed dump.
fn generate(pairs: &[(i32, String)]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo test -p lodestone-v1-17 --test entity_types -- --ignored`\n\
         // from tests/support/registries_1_17_1_jar.json (protocols 756 and 758 /\n\
         // Minecraft 1.17.1 and 1.18.2 -- the two jars' dumps agree id for id,\n\
         // asserted by both_dumps_agree_id_for_id). DO NOT EDIT BY HAND.\n\
         // Regenerate with LODESTONE_REGEN=1 (see the test module docs).\n",
    );
    out.push_str(
        "//! Generated entity-type id->name table for protocols 756 and 758\n\
         //! (Minecraft 1.17.1 and 1.18.2).\n//!\n\
         //! Maps the unified numeric entity-type id space to canonical\n\
         //! `minecraft:*` identifiers. Consumed by [`crate::entity_types`].\n\n",
    );
    let _ = writeln!(out, "/// Number of entity_types type entries.");
    let _ = writeln!(out, "pub const ENTITY_TYPE_COUNT: usize = {};\n", pairs.len());
    out.push_str(
        "/// `(type id, canonical identifier)` pairs, sorted by id for binary search.\n",
    );
    let _ = writeln!(
        out,
        "pub static ENTITY_TYPES: [(i32, &str); {}] = [",
        pairs.len()
    );
    for (id, name) in pairs {
        let _ = writeln!(out, "    ({id}, \"{name}\"),");
    }
    out.push_str("];\n");
    out
}

/// The claim that licenses a single table for the whole era. Both dumps are
/// parsed independently and compared entry by entry.
#[test]
fn both_dumps_agree_id_for_id() {
    let a = parse_registry_entities(DUMP_1_17_1);
    let b = parse_registry_entities(DUMP_1_18_2);
    assert_eq!(
        a.len(),
        b.len(),
        "the two jars' entity registries differ in size ({} vs {}); this era can no longer \
         share one entity table -- add a second generated table and an entity_types::table_for arm",
        a.len(),
        b.len()
    );
    let mismatched: Vec<_> = a
        .iter()
        .zip(&b)
        .filter(|((_, x), (_, y))| x != y)
        .map(|((id, x), (_, y))| format!("{id}: {x} vs {y}"))
        .collect();
    assert!(
        mismatched.is_empty(),
        "the two jars' entity registries disagree on {} ids: {mismatched:?}",
        mismatched.len()
    );
    assert_eq!(a.len(), 113, "1.17.1's entity registry holds 113 types");
}

/// The committed table is exactly what the dump renders to.
#[test]
#[ignore = "regenerates a committed table; run with --ignored"]
fn committed_table_matches_dump() {
    let pairs = parse_registry_entities(DUMP_1_17_1);
    let rendered = generate(&pairs);
    let path = manifest_dir().join(COMMITTED);
    if std::env::var_os("LODESTONE_REGEN").is_some() {
        std::fs::write(&path, &rendered).expect("write generated table");
        println!("regenerated {}", path.display());
        return;
    }
    let committed = std::fs::read_to_string(&path).expect("committed table exists");
    assert_eq!(
        committed, rendered,
        "{COMMITTED} has drifted from its dump; regenerate with LODESTONE_REGEN=1"
    );
}

/// Both protocols resolve through `table_for`, and to the same table.
#[test]
fn both_protocols_resolve_to_the_same_table() {
    let a = entity_types::table_for(PROTOCOL_1_17_1);
    let b = entity_types::table_for(PROTOCOL_1_18_2);
    assert_eq!(a.len(), b.len());
    assert_eq!(a.len(), a.declared_len(), "generated len/count disagree");
    assert!(!a.is_empty());
    for id in 0..i32::try_from(a.len()).expect("len fits i32") {
        assert_eq!(a.entity_type_name(id), b.entity_type_name(id));
    }
}

/// Spot values, each read out of the committed dump rather than out of the
/// table under test: the first entry, the last, and three whose position
/// moved relative to the era below.
#[test]
fn named_ids_match_the_jar_dump() {
    let pairs = parse_registry_entities(DUMP_1_17_1);
    let table = entity_types::table_for(PROTOCOL_1_17_1);
    for probe in [
        "minecraft:axolotl",
        "minecraft:glow_squid",
        "minecraft:goat",
        "minecraft:player",
        "minecraft:zombie",
    ] {
        let Some((id, _)) = pairs.iter().find(|(_, name)| name == probe) else {
            continue;
        };
        assert_eq!(
            table.entity_type_name(*id),
            Some(probe),
            "id {id} should be {probe}"
        );
    }
    let (last_id, last_name) = pairs.last().expect("registry is non-empty");
    assert_eq!(table.entity_type_name(*last_id), Some(last_name.as_str()));
    assert_eq!(
        table.entity_type_name(i32::try_from(pairs.len()).expect("fits")),
        None,
        "one past the end names no entity"
    );
}

/// The 1.17 additions are what separate this table from the era below's, so
/// their presence is the cheapest proof the right dump was used.
#[test]
fn the_1_17_additions_are_present() {
    let table = entity_types::table_for(PROTOCOL_1_17_1);
    let names: Vec<&str> = (0..i32::try_from(table.len()).expect("fits"))
        .filter_map(|id| table.entity_type_name(id))
        .collect();
    for added in ["minecraft:axolotl", "minecraft:glow_squid", "minecraft:goat"] {
        assert!(names.contains(&added), "{added} missing from the 1.17 registry");
    }
}
