//! Loot documents in the datapack shape the current release ships, rewritten
//! into the shape [`crate::loot`]'s parser reads.
//!
//! # What it is
//!
//! A pure `serde_json::Value` pass. The current release's loot documents differ
//! from the older shape the parser was written against in four ways, all
//! structural and none changing what a roll does:
//!
//! * a condition list became one `condition` (a list is an `all_of`), and a
//!   function list became one `modifier` (a list is a sequence);
//! * a condition or function names its kind in `type` instead of `condition` /
//!   `function`;
//! * a condition may be a bare id naming a stored predicate (`tool/can_silk_touch`),
//!   resolved from the embedded predicate table;
//! * `match_block` replaced the block-state condition (`blocks` + `state` for
//!   `block` + `properties`), and a tag entry's `name` became `items`.
//!
//! # How to change it
//!
//! Position decides meaning, so the walk is by position (table, pool, entry,
//! function, condition), never by a key name found anywhere. A document that is
//! already in the older shape passes through unchanged: every rewrite fires only
//! on a key the older shape does not have. Add a rewrite for a new field in the
//! function for the position it lives in.
//!
//! # Dependencies
//!
//! `serde_json` only; predicates come from [`crate::crafting`]-style embedded
//! tables generated by `build.rs` (`EMBEDDED_PREDICATES`).

use serde_json::{Map, Value, json};

include!(concat!(env!("OUT_DIR"), "/embedded_embedded_predicates.rs"));

/// Rewrites a whole table document in place.
pub(crate) fn modernise_table(table: &mut Value) {
    let Some(map) = table.as_object_mut() else { return };
    take_modifier(map);
    if let Some(pools) = map.get_mut("pools").and_then(Value::as_array_mut) {
        for pool in pools {
            modernise_pool(pool);
        }
    }
}

fn modernise_pool(pool: &mut Value) {
    let Some(map) = pool.as_object_mut() else { return };
    take_condition(map);
    take_modifier(map);
    if let Some(entries) = map.get_mut("entries").and_then(Value::as_array_mut) {
        for entry in entries {
            modernise_entry(entry);
        }
    }
}

fn modernise_entry(entry: &mut Value) {
    let Some(map) = entry.as_object_mut() else { return };
    take_condition(map);
    take_modifier(map);
    if let Some(items) = map.get("items") {
        if map.get("type").and_then(Value::as_str) == Some("minecraft:tag") && items.is_string() {
            let items = map.remove("items").unwrap_or(Value::Null);
            map.insert("name".into(), items);
        }
    }
    if let Some(children) = map.get_mut("children").and_then(Value::as_array_mut) {
        for child in children {
            modernise_entry(child);
        }
    }
    if let Some(value) = map.get_mut("value") {
        if value.is_object() {
            modernise_table(value);
        }
    }
}

/// `condition` (one condition or a stored predicate id) becomes `conditions`.
fn take_condition(map: &mut Map<String, Value>) {
    if let Some(mut condition) = map.remove("condition") {
        modernise_condition(&mut condition);
        map.insert("conditions".into(), Value::Array(vec![condition]));
    } else if let Some(conditions) = map.get_mut("conditions").and_then(Value::as_array_mut) {
        for condition in conditions {
            modernise_condition(condition);
        }
    }
}

/// `modifier` (one function or a list) becomes `functions`.
fn take_modifier(map: &mut Map<String, Value>) {
    let Some(modifier) = map.remove("modifier") else {
        if let Some(functions) = map.get_mut("functions").and_then(Value::as_array_mut) {
            for function in functions {
                modernise_function(function);
            }
        }
        return;
    };
    let mut functions = match modifier {
        Value::Array(list) => list,
        single => vec![single],
    };
    for function in &mut functions {
        modernise_function(function);
    }
    map.insert("functions".into(), Value::Array(functions));
}

fn modernise_function(function: &mut Value) {
    let Some(map) = function.as_object_mut() else { return };
    if !map.contains_key("function") {
        if let Some(kind) = map.remove("type") {
            map.insert("function".into(), kind);
        }
    }
    take_condition(map);
}

fn modernise_condition(condition: &mut Value) {
    if let Some(id) = condition.as_str() {
        match stored_predicate(id) {
            Some(mut resolved) => {
                modernise_condition(&mut resolved);
                *condition = resolved;
            }
            None => {
                // An id with no stored predicate stays visible as an unknown
                // condition rather than disappearing.
                *condition = json!({ "condition": id });
            }
        }
        return;
    }
    let Some(map) = condition.as_object_mut() else { return };
    if !map.contains_key("condition") && !map.contains_key("all_of") {
        if let Some(kind) = map.remove("type") {
            map.insert("condition".into(), kind);
        }
    }
    if map.get("condition").and_then(Value::as_str) == Some("minecraft:match_block") {
        let single_block = map
            .get("blocks")
            .and_then(Value::as_str)
            .is_some_and(|b| !b.starts_with('#'));
        if single_block {
            map.insert("condition".into(), Value::String("minecraft:block_state_property".into()));
            let block = map.remove("blocks").unwrap_or(Value::Null);
            map.insert("block".into(), block);
            if let Some(state) = map.remove("state") {
                map.insert("properties".into(), state);
            }
        }
    }
    for key in ["terms"] {
        if let Some(terms) = map.get_mut(key).and_then(Value::as_array_mut) {
            for term in terms {
                modernise_condition(term);
            }
        }
    }
    if let Some(term) = map.get_mut("term") {
        modernise_condition(term);
    }
    if let Some(inline) = map.get_mut("all_of").and_then(Value::as_array_mut) {
        for term in inline {
            modernise_condition(term);
        }
    }
}

fn stored_predicate(id: &str) -> Option<Value> {
    let path = id.strip_prefix("minecraft:").unwrap_or(id);
    EMBEDDED_PREDICATES
        .iter()
        .find(|(known, _)| *known == path)
        .and_then(|(_, text)| serde_json::from_str(text).ok())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn modernised(text: &str) -> Value {
        let mut value: Value = serde_json::from_str(text).unwrap();
        modernise_table(&mut value);
        value
    }

    #[test]
    fn a_stored_predicate_id_expands_to_its_condition() {
        let out = modernised(
            r##"{"pools":[{"entries":[{"type":"minecraft:item","name":"minecraft:stone",
                "condition":"minecraft:tool/can_silk_touch"}]}]}"##,
        );
        let cond = &out["pools"][0]["entries"][0]["conditions"][0];
        assert_eq!(cond["condition"], "minecraft:match_tool");
        assert_eq!(
            cond["predicate"]["predicates"]["minecraft:enchantments"][0]["enchantments"],
            "minecraft:silk_touch"
        );
    }

    #[test]
    fn modifiers_become_function_lists_and_type_becomes_function() {
        let out = modernised(
            r##"{"modifier":{"type":"minecraft:explosion_decay"},
                "pools":[{"entries":[{"type":"minecraft:item","name":"minecraft:a",
                  "modifier":[{"type":"minecraft:set_count","count":2},
                              {"type":"minecraft:furnace_smelt",
                               "condition":{"type":"minecraft:killed_by_player"}}]}]}]}"##,
        );
        assert_eq!(out["functions"][0]["function"], "minecraft:explosion_decay");
        let fns = &out["pools"][0]["entries"][0]["functions"];
        assert_eq!(fns[0]["function"], "minecraft:set_count");
        assert_eq!(fns[1]["conditions"][0]["condition"], "minecraft:killed_by_player");
    }

    #[test]
    fn match_block_becomes_block_state_property_only_for_a_single_block() {
        let out = modernised(
            r##"{"pools":[{"condition":{"type":"minecraft:match_block","blocks":"minecraft:wheat",
                  "state":{"age":"7"}},"entries":[]},
                 {"condition":{"type":"minecraft:match_block","blocks":"#minecraft:crops",
                  "state":{"age":"7"}},"entries":[]}]}"##,
        );
        let one = &out["pools"][0]["conditions"][0];
        assert_eq!(one["condition"], "minecraft:block_state_property");
        assert_eq!(one["block"], "minecraft:wheat");
        assert_eq!(one["properties"]["age"], "7");
        let tag = &out["pools"][1]["conditions"][0];
        assert_eq!(tag["condition"], "minecraft:match_block");
    }

    #[test]
    fn a_tag_entry_reads_items_as_its_name() {
        let out = modernised(
            r##"{"pools":[{"entries":[{"type":"minecraft:tag","expand":true,"items":"#minecraft:x"}]}]}"##,
        );
        assert_eq!(out["pools"][0]["entries"][0]["name"], "#minecraft:x");
    }

    #[test]
    fn a_document_in_the_older_shape_passes_through_unchanged() {
        let text = r##"{"pools":[{"conditions":[{"condition":"minecraft:survives_explosion"}],
            "entries":[{"type":"minecraft:item","name":"minecraft:a",
              "functions":[{"function":"minecraft:set_count","count":2}]}]}]}"##;
        let before: Value = serde_json::from_str(text).unwrap();
        assert_eq!(modernised(text), before);
    }
}
