[package]
name = "lodestone-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
lodestone-storage-schema = { path = "../lodestone-storage-schema" }
prost = "0.14.3"

[dev-dependencies]
criterion = { version = "0.8", default-features = false, features = ["cargo_bench_support"] }
redb = "3.1"
tempfile.workspace = true

[[bench]]
name = "incremental"
harness = false
