//! Which cell a block is standing on, and whether it is still there — the
//! real "can this block survive here" rule, reduced to the one question a
//! neighbour update has to answer: *did my support just go away?*
//!
//! # What it is
//!
//! Vanilla destroys a block when its support leaves: many block families'
//! own shape-update reaction resolves to air, and the block placement rule
//! then drops the block's loot and writes air. Nothing in this crate did
//! that: `crate::neighbor_update` propagated notifications faithfully and
//! every reaction it dispatched (`crate::random_tick::react_to_notification`)
//! was a redstone or gravity one, so **no block anywhere reacted to losing
//! its support** — torches, flowers, rails, doors, beds and sugar cane were
//! all unbreakable-by-support.
//!
//! This module answers "which cell supports this state" ([`requirement`]) and
//! "is that cell still good" ([`survives`]). `crate::server`'s `destroy_block`
//! drives the cascade and owns the drops.
//!
//! # How the per-block rule is derived
//!
//! Not by hand. [`SUPPORT_KINDS`] was generated by walking the decompiled
//! 26.2 source's block registrations and the inheritance chain each one
//! sits in, then mapping each block to the nearest ancestor whose own
//! survival check is a self-destruct on one *named* support cell. The
//! families and their support shapes:
//!
//! | family | support cell | kind |
//! |---|---|---|
//! | flowers, saplings, crops, stems, mushrooms, grass, dead bush, nether wart, seagrass, corals | `pos.below()` | [`SupportKind::Below`] |
//! | torches (floor), rails, snow layers, carpets, pressure plates, redstone wire, diodes (repeaters/comparators), sugar cane, cactus, bamboo, sea pickles, standing signs, banners | `pos.below()` | [`SupportKind::Below`] |
//! | wall torches, ladders, wall signs, wall hanging signs, wall banners, tripwire hooks, cocoa, amethyst clusters, wall coral fans | the wall the block is attached to, opposite its facing | [`SupportKind::AttachedFacing`] |
//! | buttons, levers, grindstone | the `face`/`facing` mount | [`SupportKind::AttachFace`] |
//! | doors, double plants (tall grass, sunflower, ...), pitcher crop | lower: below; upper: the lower half | [`SupportKind::DoubleBlock`] |
//! | beds | the partner half | [`SupportKind::BedPart`] |
//! | ceiling hanging signs, hanging roots, cave vines, weeping vines (plant part) | `pos.above()` | [`SupportKind::Hanging`] |
//! | lanterns | `hanging` decides above vs below | [`SupportKind::HangingOrBelow`] |
//!
//! The generator's judgement was checked family by family against the
//! decompile, and the checks changed the table: skulls (floor and wall),
//! tripwire, turtle eggs and sniffer eggs declare **no** survival check
//! anywhere in their ancestor chains in 26.2, so a floor skull and a turtle
//! egg stay put when the block under them goes, and inheriting a "below"
//! rule for them would have been a visible new bug.
//!
//! # The one approximation, and its direction
//!
//! The real support test is a *geometric* predicate over the block's own
//! support shape — either "rigid" or "centre" support depending on the
//! family — which no census in this repo carries.
//! `lodestone_data::snow_support::face_full_up` is the neighbouring question
//! (a full-face test over the **collision** shape) and it is measurably not
//! the same one: read out of the committed JVM dump, farmland reports
//! `false` for all 8 of its states and soul sand `false` for its only one,
//! while crops and rails sit on both quite happily.
//!
//! So this module does **not** ask how sturdy the support is. It asks whether
//! the support cell went to **air or a fluid** ([`crate::chunk::is_air_or_fluid`]),
//! which is a strict subset of the real rule and therefore fails in the safe
//! direction: a block whose support was destroyed pops (the reported case), and
//! a block sitting on a *weak* support — a torch on a fence, a rail on a hopper
//! — is left alone rather than wrongly destroyed. Closing the gap means a
//! rigid/centre support-shape census in `lodestone-data`; until then the
//! deviation is one-directional and named.
//!
//! Two blocks are excluded for the same reason from the other side: `lily_pad`
//! and `frogspawn` are supported *by water*, so an "air or fluid" trigger
//! would destroy every one of them on sight.
//!
//! # How to change it
//!
//! To add a family, add its shared ancestor to the generator's base table and
//! regenerate — do not hand-add a block name, because the inheritance chain is
//! what makes the 291 rows below trustworthy. To *remove* one, check the
//! family really has no survival check first; the five removals above were
//! each grepped.
//!
//! Deliberately not covered: the kelp/weeping-and-twisting-vines head/body
//! pair (its own growth direction, and a survival check that reads the
//! *body* chain), climbing vines and multiface growths (any of five faces,
//! not one named cell), scaffolding (a distance count), chorus plants,
//! pointed dripstone, big dripleaf stems (reads above *and* below) and mossy
//! carpet (a `bottom`/side-wall variant set). Each is a real family with a
//! real rule; none of them is a *single* support cell, which is what this
//! module's shape can express.

use lodestone_model::BlockPos;

use crate::chunk::is_air_or_fluid;
use crate::redstone::{base_name, direction_from_str, get_str_property};

/// The shape of a block's support rule — which cell it depends on, and how that
/// cell is read out of the block's own state.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum SupportKind {
    /// `pos.below()`.
    Below,
    /// The cell opposite the block's own facing direction — the wall the block
    /// is stuck to. The facing may be vertical (an amethyst cluster grows off a
    /// ceiling).
    AttachedFacing,
    /// The `face`/`facing` mount, negated: `face=floor` → below,
    /// `face=ceiling` → above, `face=wall` → the wall the `facing` points
    /// away from.
    AttachFace,
    /// A two-cell block keyed by `half=lower|upper`: the lower half needs a
    /// support below, the upper half needs the lower half.
    DoubleBlock,
    /// A bed, keyed by `part=foot|head` plus `facing`: each half needs the other.
    BedPart,
    /// `pos.above()`.
    Hanging,
    /// A lantern: `hanging=true` → above, otherwise below.
    HangingOrBelow,
}

/// What must be true of one cell for a block to keep existing.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum Requirement {
    /// The cell must hold something that is not air and not a fluid — this
    /// crate's stand-in for the real rigid/centre support test. See the
    /// module doc for the direction of the approximation.
    Supported(BlockPos),
    /// The cell must hold `block` with `property` set to `value` — the exact
    /// test doors, double plants and beds perform on their partner half, with
    /// no approximation in it.
    Partner {
        pos: BlockPos,
        block: String,
        property: &'static str,
        value: &'static str,
    },
}

/// The support rule for `block` (a bare block name, no state suffix), or `None`
/// when this crate models none — which is the answer for the great majority of
/// blocks, stone and dirt included.
#[must_use]
pub(crate) fn support_kind(block: &str) -> Option<SupportKind> {
    SUPPORT_KINDS
        .binary_search_by_key(&block, |&(name, _)| name)
        .ok()
        .map(|idx| SUPPORT_KINDS[idx].1)
}

/// The one cell `state` at `pos` depends on, or `None` when nothing about this
/// block's existence is conditional.
#[must_use]
pub(crate) fn requirement(pos: BlockPos, state: &str) -> Option<Requirement> {
    let block = base_name(state);
    let below = BlockPos::new(pos.x, pos.y - 1, pos.z);
    let above = BlockPos::new(pos.x, pos.y + 1, pos.z);
    match support_kind(block)? {
        SupportKind::Below => Some(Requirement::Supported(below)),
        SupportKind::Hanging => Some(Requirement::Supported(above)),
        SupportKind::HangingOrBelow => {
            // `hanging` ? UP : DOWN, and the survival check reads the cell
            // that direction's *opposite* leads to.
            let hanging = get_str_property(state, "hanging") == Some("true");
            Some(Requirement::Supported(if hanging { above } else { below }))
        }
        SupportKind::AttachedFacing => {
            // The cell opposite the block's own facing direction. A state naming no
            // `facing` is not a legal wall variant, so there is nothing to check.
            let facing = direction_from_str(get_str_property(state, "facing")?);
            Some(Requirement::Supported(facing.opposite().relative(pos)))
        }
        SupportKind::AttachFace => {
            // `crate::redstone::attached_connected_direction` computes exactly
            // this connected direction; the survival check looks the other way.
            let connected = crate::redstone::attached_connected_direction(state);
            Some(Requirement::Supported(connected.opposite().relative(pos)))
        }
        SupportKind::DoubleBlock => match get_str_property(state, "half") {
            // The upper arm's rule: the cell below must be this same block
            // with `half=lower`.
            Some("upper") => Some(Requirement::Partner {
                pos: below,
                block: block.to_string(),
                property: "half",
                value: "lower",
            }),
            // The lower arm is the ordinary support test. A state naming no
            // `half` is treated as the lower half, which is what the default
            // state of every block in this family is.
            _ => Some(Requirement::Supported(below)),
        },
        SupportKind::BedPart => {
            // The foot looks along `facing`, the head against it. Both halves
            // fail to air when the partner is not there, which is what makes
            // breaking one end break the other.
            let facing = direction_from_str(get_str_property(state, "facing")?);
            let (partner_dir, want) = match get_str_property(state, "part") {
                Some("head") => (facing.opposite(), "foot"),
                _ => (facing, "head"),
            };
            Some(Requirement::Partner {
                pos: partner_dir.relative(pos),
                block: block.to_string(),
                property: "part",
                value: want,
            })
        }
    }
}

/// Whether `state` at `pos` still has its support, reading the world through
/// `block_at`.
///
/// `true` for every block this crate models no rule for, so this is safe to ask
/// of an arbitrary cell.
pub(crate) fn survives<F>(pos: BlockPos, state: &str, block_at: F) -> bool
where
    F: Fn(BlockPos) -> String,
{
    let Some(requirement) = requirement(pos, state) else {
        return true;
    };
    match requirement {
        Requirement::Supported(cell) => !is_air_or_fluid(&block_at(cell)),
        Requirement::Partner {
            pos: cell,
            block,
            property,
            value,
        } => {
            let partner = block_at(cell);
            base_name(&partner) == block && get_str_property(&partner, property) == Some(value)
        }
    }
}

/// Every block whose support this crate models, sorted by name so
/// [`support_kind`] can binary-search it.
///
/// Generated from the decompiled 26.2 source — see the module doc for the
/// derivation and for the five hand-checked removals. 291 rows.
static SUPPORT_KINDS: &[(&str, SupportKind)] = &[
    ("minecraft:acacia_button", SupportKind::AttachFace),
    ("minecraft:acacia_door", SupportKind::DoubleBlock),
    ("minecraft:acacia_hanging_sign", SupportKind::Hanging),
    ("minecraft:acacia_pressure_plate", SupportKind::Below),
    ("minecraft:acacia_sapling", SupportKind::Below),
    ("minecraft:acacia_sign", SupportKind::Below),
    ("minecraft:acacia_wall_hanging_sign", SupportKind::AttachedFacing),
    ("minecraft:acacia_wall_sign", SupportKind::AttachedFacing),
    ("minecraft:activator_rail", SupportKind::Below),
    ("minecraft:allium", SupportKind::Below),
    ("minecraft:amethyst_cluster", SupportKind::AttachedFacing),
    ("minecraft:attached_melon_stem", SupportKind::Below),
    ("minecraft:attached_pumpkin_stem", SupportKind::Below),
    ("minecraft:azalea", SupportKind::Below),
    ("minecraft:azure_bluet", SupportKind::Below),
    ("minecraft:bamboo", SupportKind::Below),
    ("minecraft:bamboo_button", SupportKind::AttachFace),
    ("minecraft:bamboo_door", SupportKind::DoubleBlock),
    ("minecraft:bamboo_hanging_sign", SupportKind::Hanging),
    ("minecraft:bamboo_pressure_plate", SupportKind::Below),
    ("minecraft:bamboo_sapling", SupportKind::Below),
    ("minecraft:bamboo_sign", SupportKind::Below),
    ("minecraft:bamboo_wall_hanging_sign", SupportKind::AttachedFacing),
    ("minecraft:bamboo_wall_sign", SupportKind::AttachedFacing),
    ("minecraft:beetroots", SupportKind::Below),
    ("minecraft:big_dripleaf", SupportKind::Below),
    ("minecraft:birch_button", SupportKind::AttachFace),
    ("minecraft:birch_door", SupportKind::DoubleBlock),
    ("minecraft:birch_hanging_sign", SupportKind::Hanging),
    ("minecraft:birch_pressure_plate", SupportKind::Below),
    ("minecraft:birch_sapling", SupportKind::Below),
    ("minecraft:birch_sign", SupportKind::Below),
    ("minecraft:birch_wall_hanging_sign", SupportKind::AttachedFacing),
    ("minecraft:birch_wall_sign", SupportKind::AttachedFacing),
    ("minecraft:black_banner", SupportKind::Below),
    ("minecraft:black_bed", SupportKind::BedPart),
    ("minecraft:black_carpet", SupportKind::Below),
    ("minecraft:black_wall_banner", SupportKind::AttachedFacing),
    ("minecraft:blue_banner", SupportKind::Below),
    ("minecraft:blue_bed", SupportKind::BedPart),
    ("minecraft:blue_carpet", SupportKind::Below),
    ("minecraft:blue_orchid", SupportKind::Below),
    ("minecraft:blue_wall_banner", SupportKind::AttachedFacing),
    ("minecraft:brain_coral", SupportKind::Below),
    ("minecraft:brain_coral_fan", SupportKind::Below),
    ("minecraft:brain_coral_wall_fan", SupportKind::AttachedFacing),
    ("minecraft:brown_banner", SupportKind::Below),
    ("minecraft:brown_bed", SupportKind::BedPart),
    ("minecraft:brown_carpet", SupportKind::Below),
    ("minecraft:brown_mushroom", SupportKind::Below),
    ("minecraft:brown_wall_banner", SupportKind::AttachedFacing),
    ("minecraft:bubble_coral", SupportKind::Below),
    ("minecraft:bubble_coral_fan", SupportKind::Below),
    ("minecraft:bubble_coral_wall_fan", SupportKind::AttachedFacing),
    ("minecraft:bush", SupportKind::Below),
    ("minecraft:cactus", SupportKind::Below),
    ("minecraft:cactus_flower", SupportKind::Below),
    ("minecraft:carrots", SupportKind::Below),
    ("minecraft:cave_vines", SupportKind::Hanging),
    ("minecraft:cave_vines_plant", SupportKind::Hanging),
    ("minecraft:cherry_button", SupportKind::AttachFace),
    ("minecraft:cherry_door", SupportKind::DoubleBlock),
    ("minecraft:cherry_hanging_sign", SupportKind::Hanging),
    ("minecraft:cherry_pressure_plate", SupportKind::Below),
    ("minecraft:cherry_sapling", SupportKind::Below),
    ("minecraft:cherry_sign", SupportKind::Below),
    ("minecraft:cherry_wall_hanging_sign", SupportKind::AttachedFacing),
    ("minecraft:cherry_wall_sign", SupportKind::AttachedFacing),
    ("minecraft:closed_eyeblossom", SupportKind::Below),
    ("minecraft:cocoa", SupportKind::AttachedFacing),
    ("minecraft:comparator", SupportKind::Below),
    ("minecraft:copper_torch", SupportKind::Below),
    ("minecraft:copper_wall_torch", SupportKind::AttachedFacing),
    ("minecraft:cornflower", SupportKind::Below),
    ("minecraft:crimson_button", SupportKind::AttachFace),
    ("minecraft:crimson_door", SupportKind::DoubleBlock),
    ("minecraft:crimson_fungus", SupportKind::Below),
    ("minecraft:crimson_hanging_sign", SupportKind::Hanging),
    ("minecraft:crimson_pressure_plate", SupportKind::Below),
    ("minecraft:crimson_roots", SupportKind::Below),
    ("minecraft:crimson_sign", SupportKind::Below),
    ("minecraft:crimson_wall_hanging_sign", SupportKind::AttachedFacing),
    ("minecraft:crimson_wall_sign", SupportKind::AttachedFacing),
    ("minecraft:cyan_banner", SupportKind::Below),
    ("minecraft:cyan_bed", SupportKind::BedPart),
    ("minecraft:cyan_carpet", SupportKind::Below),
    ("minecraft:cyan_wall_banner", SupportKind::AttachedFacing),
    ("minecraft:dandelion", SupportKind::Below),
    ("minecraft:dark_oak_button", SupportKind::AttachFace),
    ("minecraft:dark_oak_door", SupportKind::DoubleBlock),
    ("minecraft:dark_oak_hanging_sign", SupportKind::Hanging),
    ("minecraft:dark_oak_pressure_plate", SupportKind::Below),
    ("minecraft:dark_oak_sapling", SupportKind::Below),
    ("minecraft:dark_oak_sign", SupportKind::Below),
    ("minecraft:dark_oak_wall_hanging_sign", SupportKind::AttachedFacing),
    ("minecraft:dark_oak_wall_sign", SupportKind::AttachedFacing),
    ("minecraft:dead_brain_coral", SupportKind::Below),
    ("minecraft:dead_brain_coral_fan", SupportKind::Below),
    ("minecraft:dead_brain_coral_wall_fan", SupportKind::AttachedFacing),
    ("minecraft:dead_bubble_coral", SupportKind::Below),
    ("minecraft:dead_bubble_coral_fan", SupportKind::Below),
    ("minecraft:dead_bubble_coral_wall_fan", SupportKind::AttachedFacing),
    ("minecraft:dead_bush", SupportKind::Below),
    ("minecraft:dead_fire_coral", SupportKind::Below),
    ("minecraft:dead_fire_coral_fan", SupportKind::Below),
    ("minecraft:dead_fire_coral_wall_fan", SupportKind::AttachedFacing),
    ("minecraft:dead_horn_coral", SupportKind::Below),
    ("minecraft:dead_horn_coral_fan", SupportKind::Below),
    ("minecraft:dead_horn_coral_wall_fan", SupportKind::AttachedFacing),
    ("minecraft:dead_tube_coral", SupportKind::Below),
    ("minecraft:dead_tube_coral_fan", SupportKind::Below),
    ("minecraft:dead_tube_coral_wall_fan", SupportKind::AttachedFacing),
    ("minecraft:detector_rail", SupportKind::Below),
    ("minecraft:fern", SupportKind::Below),
    ("minecraft:fire_coral", SupportKind::Below),
    ("minecraft:fire_coral_fan", SupportKind::Below),
    ("minecraft:fire_coral_wall_fan", SupportKind::AttachedFacing),
    ("minecraft:flowering_azalea", SupportKind::Below),
    ("minecraft:golden_dandelion", SupportKind::Below),
    ("minecraft:gray_banner", SupportKind::Below),
    ("minecraft:gray_bed", SupportKind::BedPart),
    ("minecraft:gray_carpet", SupportKind::Below),
    ("minecraft:gray_wall_banner", SupportKind::AttachedFacing),
    ("minecraft:green_banner", SupportKind::Below),
    ("minecraft:green_bed", SupportKind::BedPart),
    ("minecraft:green_carpet", SupportKind::Below),
    ("minecraft:green_wall_banner", SupportKind::AttachedFacing),
    ("minecraft:grindstone", SupportKind::AttachFace),
    ("minecraft:hanging_roots", SupportKind::Hanging),
    ("minecraft:heavy_weighted_pressure_plate", SupportKind::Below),
    ("minecraft:horn_coral", SupportKind::Below),
    ("minecraft:horn_coral_fan", SupportKind::Below),
    ("minecraft:horn_coral_wall_fan", SupportKind::AttachedFacing),
    ("minecraft:iron_door", SupportKind::DoubleBlock),
    ("minecraft:jungle_button", SupportKind::AttachFace),
    ("minecraft:jungle_door", SupportKind::DoubleBlock),
    ("minecraft:jungle_hanging_sign", SupportKind::Hanging),
    ("minecraft:jungle_pressure_plate", SupportKind::Below),
    ("minecraft:jungle_sapling", SupportKind::Below),
    ("minecraft:jungle_sign", SupportKind::Below),
    ("minecraft:jungle_wall_hanging_sign", SupportKind::AttachedFacing),
    ("minecraft:jungle_wall_sign", SupportKind::AttachedFacing),
    ("minecraft:ladder", SupportKind::AttachedFacing),
    ("minecraft:lantern", SupportKind::HangingOrBelow),
    ("minecraft:large_amethyst_bud", SupportKind::AttachedFacing),
    ("minecraft:large_fern", SupportKind::DoubleBlock),
    ("minecraft:leaf_litter", SupportKind::Below),
    ("minecraft:lever", SupportKind::AttachFace),
    ("minecraft:light_blue_banner", SupportKind::Below),
    ("minecraft:light_blue_bed", SupportKind::BedPart),
    ("minecraft:light_blue_carpet", SupportKind::Below),
    ("minecraft:light_blue_wall_banner", SupportKind::AttachedFacing),
    ("minecraft:light_gray_banner", SupportKind::Below),
    ("minecraft:light_gray_bed", SupportKind::BedPart),
    ("minecraft:light_gray_carpet", SupportKind::Below),
    ("minecraft:light_gray_wall_banner", SupportKind::AttachedFacing),
    ("minecraft:light_weighted_pressure_plate", SupportKind::Below),
    ("minecraft:lilac", SupportKind::DoubleBlock),
    ("minecraft:lily_of_the_valley", SupportKind::Below),
    ("minecraft:lime_banner", SupportKind::Below),
    ("minecraft:lime_bed", SupportKind::BedPart),
    ("minecraft:lime_carpet", SupportKind::Below),
    ("minecraft:lime_wall_banner", SupportKind::AttachedFacing),
    ("minecraft:magenta_banner", SupportKind::Below),
    ("minecraft:magenta_bed", SupportKind::BedPart),
    ("minecraft:magenta_carpet", SupportKind::Below),
    ("minecraft:magenta_wall_banner", SupportKind::AttachedFacing),
    ("minecraft:mangrove_button", SupportKind::AttachFace),
    ("minecraft:mangrove_door", SupportKind::DoubleBlock),
    ("minecraft:mangrove_hanging_sign", SupportKind::Hanging),
    ("minecraft:mangrove_pressure_plate", SupportKind::Below),
    ("minecraft:mangrove_propagule", SupportKind::Below),
    ("minecraft:mangrove_sign", SupportKind::Below),
    ("minecraft:mangrove_wall_hanging_sign", SupportKind::AttachedFacing),
    ("minecraft:mangrove_wall_sign", SupportKind::AttachedFacing),
    ("minecraft:medium_amethyst_bud", SupportKind::AttachedFacing),
    ("minecraft:melon_stem", SupportKind::Below),
    ("minecraft:moss_carpet", SupportKind::Below),
    ("minecraft:nether_sprouts", SupportKind::Below),
    ("minecraft:nether_wart", SupportKind::Below),
    ("minecraft:oak_button", SupportKind::AttachFace),
    ("minecraft:oak_door", SupportKind::DoubleBlock),
    ("minecraft:oak_hanging_sign", SupportKind::Hanging),
    ("minecraft:oak_pressure_plate", SupportKind::Below),
    ("minecraft:oak_sapling", SupportKind::Below),
    ("minecraft:oak_sign", SupportKind::Below),
    ("minecraft:oak_wall_hanging_sign", SupportKind::AttachedFacing),
    ("minecraft:oak_wall_sign", SupportKind::AttachedFacing),
    ("minecraft:open_eyeblossom", SupportKind::Below),
    ("minecraft:orange_banner", SupportKind::Below),
    ("minecraft:orange_bed", SupportKind::BedPart),
    ("minecraft:orange_carpet", SupportKind::Below),
    ("minecraft:orange_tulip", SupportKind::Below),
    ("minecraft:orange_wall_banner", SupportKind::AttachedFacing),
    ("minecraft:oxeye_daisy", SupportKind::Below),
    ("minecraft:pale_oak_button", SupportKind::AttachFace),
    ("minecraft:pale_oak_door", SupportKind::DoubleBlock),
    ("minecraft:pale_oak_hanging_sign", SupportKind::Hanging),
    ("minecraft:pale_oak_pressure_plate", SupportKind::Below),
    ("minecraft:pale_oak_sapling", SupportKind::Below),
    ("minecraft:pale_oak_sign", SupportKind::Below),
    ("minecraft:pale_oak_wall_hanging_sign", SupportKind::AttachedFacing),
    ("minecraft:pale_oak_wall_sign", SupportKind::AttachedFacing),
    ("minecraft:peony", SupportKind::DoubleBlock),
    ("minecraft:pink_banner", SupportKind::Below),
    ("minecraft:pink_bed", SupportKind::BedPart),
    ("minecraft:pink_carpet", SupportKind::Below),
    ("minecraft:pink_petals", SupportKind::Below),
    ("minecraft:pink_tulip", SupportKind::Below),
    ("minecraft:pink_wall_banner", SupportKind::AttachedFacing),
    ("minecraft:pitcher_crop", SupportKind::DoubleBlock),
    ("minecraft:pitcher_plant", SupportKind::DoubleBlock),
    ("minecraft:polished_blackstone_button", SupportKind::AttachFace),
    ("minecraft:polished_blackstone_pressure_plate", SupportKind::Below),
    ("minecraft:poppy", SupportKind::Below),
    ("minecraft:potatoes", SupportKind::Below),
    ("minecraft:powered_rail", SupportKind::Below),
    ("minecraft:pumpkin_stem", SupportKind::Below),
    ("minecraft:purple_banner", SupportKind::Below),
    ("minecraft:purple_bed", SupportKind::BedPart),
    ("minecraft:purple_carpet", SupportKind::Below),
    ("minecraft:purple_wall_banner", SupportKind::AttachedFacing),
    ("minecraft:rail", SupportKind::Below),
    ("minecraft:red_banner", SupportKind::Below),
    ("minecraft:red_bed", SupportKind::BedPart),
    ("minecraft:red_carpet", SupportKind::Below),
    ("minecraft:red_mushroom", SupportKind::Below),
    ("minecraft:red_tulip", SupportKind::Below),
    ("minecraft:red_wall_banner", SupportKind::AttachedFacing),
    ("minecraft:redstone_torch", SupportKind::Below),
    ("minecraft:redstone_wall_torch", SupportKind::AttachedFacing),
    ("minecraft:redstone_wire", SupportKind::Below),
    ("minecraft:repeater", SupportKind::Below),
    ("minecraft:rose_bush", SupportKind::DoubleBlock),
    ("minecraft:sea_pickle", SupportKind::Below),
    ("minecraft:seagrass", SupportKind::Below),
    ("minecraft:short_dry_grass", SupportKind::Below),
    ("minecraft:short_grass", SupportKind::Below),
    ("minecraft:small_amethyst_bud", SupportKind::AttachedFacing),
    ("minecraft:small_dripleaf", SupportKind::Below),
    ("minecraft:snow", SupportKind::Below),
    ("minecraft:soul_lantern", SupportKind::HangingOrBelow),
    ("minecraft:soul_torch", SupportKind::Below),
    ("minecraft:soul_wall_torch", SupportKind::AttachedFacing),
    ("minecraft:spruce_button", SupportKind::AttachFace),
    ("minecraft:spruce_door", SupportKind::DoubleBlock),
    ("minecraft:spruce_hanging_sign", SupportKind::Hanging),
    ("minecraft:spruce_pressure_plate", SupportKind::Below),
    ("minecraft:spruce_sapling", SupportKind::Below),
    ("minecraft:spruce_sign", SupportKind::Below),
    ("minecraft:spruce_wall_hanging_sign", SupportKind::AttachedFacing),
    ("minecraft:spruce_wall_sign", SupportKind::AttachedFacing),
    ("minecraft:stone_button", SupportKind::AttachFace),
    ("minecraft:stone_pressure_plate", SupportKind::Below),
    ("minecraft:sugar_cane", SupportKind::Below),
    ("minecraft:sunflower", SupportKind::DoubleBlock),
    ("minecraft:sweet_berry_bush", SupportKind::Below),
    ("minecraft:tall_dry_grass", SupportKind::Below),
    ("minecraft:tall_grass", SupportKind::DoubleBlock),
    ("minecraft:tall_seagrass", SupportKind::DoubleBlock),
    ("minecraft:torch", SupportKind::Below),
    ("minecraft:torchflower", SupportKind::Below),
    ("minecraft:torchflower_crop", SupportKind::Below),
    ("minecraft:tripwire_hook", SupportKind::AttachedFacing),
    ("minecraft:tube_coral", SupportKind::Below),
    ("minecraft:tube_coral_fan", SupportKind::Below),
    ("minecraft:tube_coral_wall_fan", SupportKind::AttachedFacing),
    ("minecraft:twisting_vines_plant", SupportKind::Below),
    ("minecraft:wall_torch", SupportKind::AttachedFacing),
    ("minecraft:warped_button", SupportKind::AttachFace),
    ("minecraft:warped_door", SupportKind::DoubleBlock),
    ("minecraft:warped_fungus", SupportKind::Below),
    ("minecraft:warped_hanging_sign", SupportKind::Hanging),
    ("minecraft:warped_pressure_plate", SupportKind::Below),
    ("minecraft:warped_roots", SupportKind::Below),
    ("minecraft:warped_sign", SupportKind::Below),
    ("minecraft:warped_wall_hanging_sign", SupportKind::AttachedFacing),
    ("minecraft:warped_wall_sign", SupportKind::AttachedFacing),
    ("minecraft:weeping_vines_plant", SupportKind::Hanging),
    ("minecraft:wheat", SupportKind::Below),
    ("minecraft:white_banner", SupportKind::Below),
    ("minecraft:white_bed", SupportKind::BedPart),
    ("minecraft:white_carpet", SupportKind::Below),
    ("minecraft:white_tulip", SupportKind::Below),
    ("minecraft:white_wall_banner", SupportKind::AttachedFacing),
    ("minecraft:wildflowers", SupportKind::Below),
    ("minecraft:wither_rose", SupportKind::Below),
    ("minecraft:yellow_banner", SupportKind::Below),
    ("minecraft:yellow_bed", SupportKind::BedPart),
    ("minecraft:yellow_carpet", SupportKind::Below),
    ("minecraft:yellow_wall_banner", SupportKind::AttachedFacing),
];

#[cfg(test)]
mod tests {
    use super::*;

    fn pos() -> BlockPos {
        BlockPos::new(4, 70, -9)
    }

    /// [`support_kind`] binary-searches, so a table that is not sorted answers
    /// `None` for real blocks — silently, and only for some of them.
    #[test]
    fn the_table_is_sorted_and_has_no_duplicates() {
        let mut offenders = Vec::new();
        for pair in SUPPORT_KINDS.windows(2) {
            if pair[0].0 >= pair[1].0 {
                offenders.push((pair[0].0, pair[1].0));
            }
        }
        assert!(
            offenders.is_empty(),
            "table must be strictly ascending; out of order at {offenders:?}"
        );
    }

    /// Every name in the table must be a real 26.2 block. The table was
    /// generated from the real block registration names lowercased, which is
    /// a convention rather than a guarantee — this is the check that the
    /// convention held, against a census generated from the jar by a different
    /// route entirely.
    #[test]
    fn every_table_name_exists_in_the_block_state_census() {
        let mut missing = Vec::new();
        for &(name, _) in SUPPORT_KINDS {
            if lodestone_data::block_states::state_id(name).is_none() {
                missing.push(name);
            }
        }
        assert!(
            missing.is_empty(),
            "{} table names are not blocks in the 26.2 census: {missing:?}",
            missing.len()
        );
    }

    /// Negative control for the census check above: a name that is *not* a
    /// block must be reported as missing, or the assertion is vacuous.
    #[test]
    fn the_census_check_would_notice_a_bogus_name() {
        assert!(lodestone_data::block_states::state_id("minecraft:not_a_block").is_none());
    }

    /// The blocks whose ancestors declare no survival check must answer
    /// `None` — they were removed from the generator's output deliberately,
    /// and a regression here means skulls start popping off floors.
    #[test]
    fn blocks_with_no_vanilla_can_survive_are_absent() {
        let mut wrongly_present = Vec::new();
        for name in [
            "minecraft:skeleton_skull",
            "minecraft:zombie_head",
            "minecraft:turtle_egg",
            "minecraft:sniffer_egg",
            "minecraft:tripwire",
            "minecraft:lily_pad",
            "minecraft:frogspawn",
            "minecraft:stone",
            "minecraft:dirt",
            "minecraft:cobweb",
            "minecraft:vine",
            "minecraft:scaffolding",
        ] {
            if support_kind(name).is_some() {
                wrongly_present.push(name);
            }
        }
        assert!(
            wrongly_present.is_empty(),
            "these have no single-cell survival check in 26.2: {wrongly_present:?}"
        );
    }

    /// One assertion per family shape, collected rather than asserted in the
    /// loop so a broken arm does not hide the other five.
    #[test]
    fn each_family_reads_the_cell_vanilla_reads() {
        let p = pos();
        let cases: Vec<(&str, &str, Requirement)> = vec![
            // A floor torch's support is below.
            (
                "floor torch",
                "minecraft:torch",
                Requirement::Supported(BlockPos::new(p.x, p.y - 1, p.z)),
            ),
            // A wall torch's support is the wall it points away from.
            // `facing=east` means the wall is west.
            (
                "wall torch",
                "minecraft:wall_torch[facing=east]",
                Requirement::Supported(BlockPos::new(p.x - 1, p.y, p.z)),
            ),
            // A lever's `face=floor` connects UP, so the support is below.
            (
                "floor lever",
                "minecraft:lever[face=floor,facing=north]",
                Requirement::Supported(BlockPos::new(p.x, p.y - 1, p.z)),
            ),
            // `face=ceiling` connects DOWN, so the support is above.
            (
                "ceiling lever",
                "minecraft:lever[face=ceiling,facing=north]",
                Requirement::Supported(BlockPos::new(p.x, p.y + 1, p.z)),
            ),
            // A rail's support is below.
            (
                "rail",
                "minecraft:rail[shape=north_south]",
                Requirement::Supported(BlockPos::new(p.x, p.y - 1, p.z)),
            ),
            // A door's upper arm: the cell below must be the same door's
            // lower half.
            (
                "door upper half",
                "minecraft:oak_door[half=upper,facing=north]",
                Requirement::Partner {
                    pos: BlockPos::new(p.x, p.y - 1, p.z),
                    block: "minecraft:oak_door".to_string(),
                    property: "half",
                    value: "lower",
                },
            ),
            // A bed's foot looks along `facing`, and `facing=south` is +z.
            (
                "bed foot",
                "minecraft:red_bed[part=foot,facing=south]",
                Requirement::Partner {
                    pos: BlockPos::new(p.x, p.y, p.z + 1),
                    block: "minecraft:red_bed".to_string(),
                    property: "part",
                    value: "head",
                },
            ),
            // A hanging sign hangs from the cell above.
            (
                "ceiling hanging sign",
                "minecraft:oak_hanging_sign[rotation=0]",
                Requirement::Supported(BlockPos::new(p.x, p.y + 1, p.z)),
            ),
            // A hanging lantern's support is above.
            (
                "hanging lantern",
                "minecraft:lantern[hanging=true]",
                Requirement::Supported(BlockPos::new(p.x, p.y + 1, p.z)),
            ),
            (
                "standing lantern",
                "minecraft:lantern[hanging=false]",
                Requirement::Supported(BlockPos::new(p.x, p.y - 1, p.z)),
            ),
        ];
        let mut mismatches = Vec::new();
        for (label, state, expected) in cases {
            let got = requirement(p, state);
            if got.as_ref() != Some(&expected) {
                mismatches.push(format!("{label}: expected {expected:?}, got {got:?}"));
            }
        }
        assert!(mismatches.is_empty(), "{mismatches:#?}");
    }

    /// The two directions of [`survives`] for one support cell, so the
    /// predicate is shown to be able to answer both ways rather than being
    /// constant.
    #[test]
    fn a_plant_survives_on_dirt_and_not_on_air_or_water() {
        let p = pos();
        let below = BlockPos::new(p.x, p.y - 1, p.z);
        let with = |fill: &'static str| {
            move |cell: BlockPos| {
                if cell == below {
                    fill.to_string()
                } else {
                    "minecraft:air".to_string()
                }
            }
        };
        assert!(survives(p, "minecraft:poppy", with("minecraft:dirt")));
        assert!(!survives(p, "minecraft:poppy", with("minecraft:air")));
        assert!(
            !survives(p, "minecraft:poppy", with("minecraft:water[level=0]")),
            "a fluid is not a support"
        );
        // And the un-modelled majority is unaffected in both worlds.
        assert!(survives(p, "minecraft:stone", with("minecraft:air")));
    }

    /// A bed's partner test is on identity, not on presence: a *different*
    /// bed colour, or the same `part`, must both fail. The same-`part` case is
    /// the one a "is there a bed next door" implementation gets wrong.
    #[test]
    fn a_bed_half_needs_the_opposite_half_of_the_same_bed() {
        let p = pos();
        let partner = BlockPos::new(p.x, p.y, p.z + 1);
        let with = |fill: &'static str| {
            move |cell: BlockPos| {
                if cell == partner {
                    fill.to_string()
                } else {
                    "minecraft:air".to_string()
                }
            }
        };
        let foot = "minecraft:red_bed[part=foot,facing=south]";
        let mut wrong = Vec::new();
        if !survives(p, foot, with("minecraft:red_bed[part=head,facing=south]")) {
            wrong.push("the matching head must support the foot");
        }
        if survives(p, foot, with("minecraft:red_bed[part=foot,facing=south]")) {
            wrong.push("two feet must not support each other");
        }
        if survives(p, foot, with("minecraft:blue_bed[part=head,facing=south]")) {
            wrong.push("a different bed block must not count as the partner");
        }
        if survives(p, foot, with("minecraft:stone")) {
            wrong.push("an ordinary block must not count as the partner");
        }
        assert!(wrong.is_empty(), "{wrong:#?}");
    }
}
