//! Which cell a block is standing on, and whether it is still there — the
//! real "can this block survive here" rule, reduced to the one question a
//! neighbour update has to answer: *did my support just go away?*
//!
//! # What it is
//!
//! Vanilla destroys a block when its support leaves: many block families'
//! own shape-update reaction resolves to air, and the block placement rule
//! then drops the block's loot and writes air. Nothing in this crate did
//! that: `crate::neighbor_update` propagated notifications faithfully and
//! every reaction it dispatched (`crate::random_tick::react_to_notification`)
//! was a redstone or gravity one, so **no block anywhere reacted to losing
//! its support** — torches, flowers, rails, doors, beds and sugar cane were
//! all unbreakable-by-support.
//!
//! This module answers "which cell supports this state" ([`requirement`]) and
//! "is that cell still good" ([`survives`]). `crate::server`'s `destroy_block`
//! drives the cascade and owns the drops.
//!
//! # How the per-block rule is derived
//!
//! Not by hand. [`support_kind`] was generated by walking the decompiled
//! 26.2 source's block registrations and the inheritance chain each one
//! sits in, then mapping each block to the nearest ancestor whose own
//! survival check is a self-destruct on one *named* support cell. The
//! families and their support shapes:
//!
//! | family | support cell | kind |
//! |---|---|---|
//! | flowers, saplings, crops, stems, mushrooms, grass, dead bush, nether wart, seagrass, corals | `pos.below()` | [`SupportKind::Below`] |
//! | torches (floor), rails, snow layers, carpets, pressure plates, redstone wire, diodes (repeaters/comparators), sugar cane, cactus, bamboo, sea pickles, standing signs, banners | `pos.below()` | [`SupportKind::Below`] |
//! | wall torches, ladders, wall signs, wall hanging signs, wall banners, tripwire hooks, cocoa, amethyst clusters, wall coral fans | the wall the block is attached to, opposite its facing | [`SupportKind::AttachedFacing`] |
//! | buttons, levers, grindstone | the `face`/`facing` mount | [`SupportKind::AttachFace`] |
//! | doors, double plants (tall grass, sunflower, ...), pitcher crop, small dripleaf | lower: below; upper: the lower half | [`SupportKind::DoubleBlock`] |
//! | beds | the partner half | [`SupportKind::BedPart`] |
//! | ceiling hanging signs, hanging roots, cave vines, weeping vines (plant part) | `pos.above()` | [`SupportKind::Hanging`] |
//! | lanterns | `hanging` decides above vs below | [`SupportKind::HangingOrBelow`] |
//!
//! The generator's judgement was checked family by family against the
//! decompile, and the checks changed the table: skulls (floor and wall),
//! tripwire, turtle eggs and sniffer eggs declare **no** survival check
//! anywhere in their ancestor chains in 26.2, so a floor skull and a turtle
//! egg stay put when the block under them goes, and inheriting a "below"
//! rule for them would have been a visible new bug.
//!
//! # The one approximation, and its direction
//!
//! The real support test is a *geometric* predicate over the block's own
//! support shape — either "rigid" or "centre" support depending on the
//! family — which no census in this repo carries.
//! `lodestone_data::snow_support::face_full_up` is the neighbouring question
//! (a full-face test over the **collision** shape) and it is measurably not
//! the same one: read out of the committed JVM dump, farmland reports
//! `false` for all 8 of its states and soul sand `false` for its only one,
//! while crops and rails sit on both quite happily.
//!
//! So this module does **not** ask how sturdy the support is. It asks whether
//! the support cell went to **air or a fluid** ([`crate::chunk::is_air_or_fluid`]),
//! which is a strict subset of the real rule and therefore fails in the safe
//! direction: a block whose support was destroyed pops (the reported case), and
//! a block sitting on a *weak* support — a torch on a fence, a rail on a hopper
//! — is left alone rather than wrongly destroyed. Closing the gap means a
//! rigid/centre support-shape census in `lodestone-data`; until then the
//! deviation is one-directional and named.
//!
//! Two blocks are excluded for the same reason from the other side: `lily_pad`
//! and `frogspawn` are supported *by water*, so an "air or fluid" trigger
//! would destroy every one of them on sight.
//!
//! # How to change it
//!
//! To add a family, add its shared ancestor to the generator's base table and
//! regenerate — do not hand-add a block name, because the inheritance chain is
//! what makes the 291 rows below trustworthy. To *remove* one, check the
//! family really has no survival check first; the five removals above were
//! each grepped.
//!
//! Deliberately not covered: the kelp/weeping-and-twisting-vines head/body
//! pair (its own growth direction, and a survival check that reads the
//! *body* chain), climbing vines and multiface growths (any of five faces,
//! not one named cell), scaffolding (a distance count), chorus plants,
//! pointed dripstone, big dripleaf stems (reads above *and* below) and mossy
//! carpet (a `bottom`/side-wall variant set). Each is a real family with a
//! real rule; none of them is a *single* support cell, which is what this
//! module's shape can express.

use lodestone_data::block::Block;
use lodestone_data::block_properties::{BuiltinPropertyValue, PropertyKey};
use lodestone_data::block_states::StateId;
use lodestone_model::BlockPos;

use crate::chunk::is_air_or_fluid_id;
use crate::redstone::{attached_connected_direction, direction_from_property, get_str_property, WorldState};

/// The shape of a block's support rule — which cell it depends on, and how that
/// cell is read out of the block's own state.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum SupportKind {
    /// `pos.below()`.
    Below,
    /// The cell opposite the block's own facing direction — the wall the block
    /// is stuck to. The facing may be vertical (an amethyst cluster grows off a
    /// ceiling).
    AttachedFacing,
    /// The `face`/`facing` mount, negated: `face=floor` → below,
    /// `face=ceiling` → above, `face=wall` → the wall the `facing` points
    /// away from.
    AttachFace,
    /// A two-cell block keyed by `half=lower|upper`: the lower half needs a
    /// support below, the upper half needs the lower half.
    DoubleBlock,
    /// A bed, keyed by `part=foot|head` plus `facing`: each half needs the other.
    BedPart,
    /// `pos.above()`.
    Hanging,
    /// A lantern: `hanging=true` → above, otherwise below.
    HangingOrBelow,
}

/// What must be true of one cell for a block to keep existing.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum Requirement {
    /// The cell must hold something that is not air and not a fluid — this
    /// crate's stand-in for the real rigid/centre support test. See the
    /// module doc for the direction of the approximation.
    Supported(BlockPos),
    /// The cell must hold `block` with `property` set to `value` — the exact
    /// test doors, double plants and beds perform on their partner half, with
    /// no approximation in it.
    Partner {
        pos: BlockPos,
        block: Block,
        property: PropertyKey,
        value: BuiltinPropertyValue,
    },
}

/// The support rule for `block` (a bare block name, no state suffix), or `None`
/// when this crate models none — which is the answer for the great majority of
/// blocks, stone and dirt included.
#[must_use]
pub(crate) fn support_kind(block: Block) -> Option<SupportKind> {
    match block {
        Block::AcaciaButton => Some(SupportKind::AttachFace),
        Block::AcaciaDoor => Some(SupportKind::DoubleBlock),
        Block::AcaciaHangingSign => Some(SupportKind::Hanging),
        Block::AcaciaPressurePlate => Some(SupportKind::Below),
        Block::AcaciaSapling => Some(SupportKind::Below),
        Block::AcaciaSign => Some(SupportKind::Below),
        Block::AcaciaWallHangingSign => Some(SupportKind::AttachedFacing),
        Block::AcaciaWallSign => Some(SupportKind::AttachedFacing),
        Block::ActivatorRail => Some(SupportKind::Below),
        Block::Allium => Some(SupportKind::Below),
        Block::AmethystCluster => Some(SupportKind::AttachedFacing),
        Block::AttachedMelonStem => Some(SupportKind::Below),
        Block::AttachedPumpkinStem => Some(SupportKind::Below),
        Block::Azalea => Some(SupportKind::Below),
        Block::AzureBluet => Some(SupportKind::Below),
        Block::Bamboo => Some(SupportKind::Below),
        Block::BambooButton => Some(SupportKind::AttachFace),
        Block::BambooDoor => Some(SupportKind::DoubleBlock),
        Block::BambooHangingSign => Some(SupportKind::Hanging),
        Block::BambooPressurePlate => Some(SupportKind::Below),
        Block::BambooSapling => Some(SupportKind::Below),
        Block::BambooSign => Some(SupportKind::Below),
        Block::BambooWallHangingSign => Some(SupportKind::AttachedFacing),
        Block::BambooWallSign => Some(SupportKind::AttachedFacing),
        Block::Beetroots => Some(SupportKind::Below),
        Block::BigDripleaf => Some(SupportKind::Below),
        Block::BirchButton => Some(SupportKind::AttachFace),
        Block::BirchDoor => Some(SupportKind::DoubleBlock),
        Block::BirchHangingSign => Some(SupportKind::Hanging),
        Block::BirchPressurePlate => Some(SupportKind::Below),
        Block::BirchSapling => Some(SupportKind::Below),
        Block::BirchSign => Some(SupportKind::Below),
        Block::BirchWallHangingSign => Some(SupportKind::AttachedFacing),
        Block::BirchWallSign => Some(SupportKind::AttachedFacing),
        Block::BlackBanner => Some(SupportKind::Below),
        Block::BlackBed => Some(SupportKind::BedPart),
        Block::BlackCarpet => Some(SupportKind::Below),
        Block::BlackWallBanner => Some(SupportKind::AttachedFacing),
        Block::BlueBanner => Some(SupportKind::Below),
        Block::BlueBed => Some(SupportKind::BedPart),
        Block::BlueCarpet => Some(SupportKind::Below),
        Block::BlueOrchid => Some(SupportKind::Below),
        Block::BlueWallBanner => Some(SupportKind::AttachedFacing),
        Block::BrainCoral => Some(SupportKind::Below),
        Block::BrainCoralFan => Some(SupportKind::Below),
        Block::BrainCoralWallFan => Some(SupportKind::AttachedFacing),
        Block::BrownBanner => Some(SupportKind::Below),
        Block::BrownBed => Some(SupportKind::BedPart),
        Block::BrownCarpet => Some(SupportKind::Below),
        Block::BrownMushroom => Some(SupportKind::Below),
        Block::BrownWallBanner => Some(SupportKind::AttachedFacing),
        Block::BubbleCoral => Some(SupportKind::Below),
        Block::BubbleCoralFan => Some(SupportKind::Below),
        Block::BubbleCoralWallFan => Some(SupportKind::AttachedFacing),
        Block::Bush => Some(SupportKind::Below),
        Block::Cactus => Some(SupportKind::Below),
        Block::CactusFlower => Some(SupportKind::Below),
        Block::Carrots => Some(SupportKind::Below),
        Block::CaveVines => Some(SupportKind::Hanging),
        Block::CaveVinesPlant => Some(SupportKind::Hanging),
        Block::CherryButton => Some(SupportKind::AttachFace),
        Block::CherryDoor => Some(SupportKind::DoubleBlock),
        Block::CherryHangingSign => Some(SupportKind::Hanging),
        Block::CherryPressurePlate => Some(SupportKind::Below),
        Block::CherrySapling => Some(SupportKind::Below),
        Block::CherrySign => Some(SupportKind::Below),
        Block::CherryWallHangingSign => Some(SupportKind::AttachedFacing),
        Block::CherryWallSign => Some(SupportKind::AttachedFacing),
        Block::ClosedEyeblossom => Some(SupportKind::Below),
        Block::Cocoa => Some(SupportKind::AttachedFacing),
        Block::Comparator => Some(SupportKind::Below),
        Block::CopperTorch => Some(SupportKind::Below),
        Block::CopperWallTorch => Some(SupportKind::AttachedFacing),
        Block::Cornflower => Some(SupportKind::Below),
        Block::CrimsonButton => Some(SupportKind::AttachFace),
        Block::CrimsonDoor => Some(SupportKind::DoubleBlock),
        Block::CrimsonFungus => Some(SupportKind::Below),
        Block::CrimsonHangingSign => Some(SupportKind::Hanging),
        Block::CrimsonPressurePlate => Some(SupportKind::Below),
        Block::CrimsonRoots => Some(SupportKind::Below),
        Block::CrimsonSign => Some(SupportKind::Below),
        Block::CrimsonWallHangingSign => Some(SupportKind::AttachedFacing),
        Block::CrimsonWallSign => Some(SupportKind::AttachedFacing),
        Block::CyanBanner => Some(SupportKind::Below),
        Block::CyanBed => Some(SupportKind::BedPart),
        Block::CyanCarpet => Some(SupportKind::Below),
        Block::CyanWallBanner => Some(SupportKind::AttachedFacing),
        Block::Dandelion => Some(SupportKind::Below),
        Block::DarkOakButton => Some(SupportKind::AttachFace),
        Block::DarkOakDoor => Some(SupportKind::DoubleBlock),
        Block::DarkOakHangingSign => Some(SupportKind::Hanging),
        Block::DarkOakPressurePlate => Some(SupportKind::Below),
        Block::DarkOakSapling => Some(SupportKind::Below),
        Block::DarkOakSign => Some(SupportKind::Below),
        Block::DarkOakWallHangingSign => Some(SupportKind::AttachedFacing),
        Block::DarkOakWallSign => Some(SupportKind::AttachedFacing),
        Block::DeadBrainCoral => Some(SupportKind::Below),
        Block::DeadBrainCoralFan => Some(SupportKind::Below),
        Block::DeadBrainCoralWallFan => Some(SupportKind::AttachedFacing),
        Block::DeadBubbleCoral => Some(SupportKind::Below),
        Block::DeadBubbleCoralFan => Some(SupportKind::Below),
        Block::DeadBubbleCoralWallFan => Some(SupportKind::AttachedFacing),
        Block::DeadBush => Some(SupportKind::Below),
        Block::DeadFireCoral => Some(SupportKind::Below),
        Block::DeadFireCoralFan => Some(SupportKind::Below),
        Block::DeadFireCoralWallFan => Some(SupportKind::AttachedFacing),
        Block::DeadHornCoral => Some(SupportKind::Below),
        Block::DeadHornCoralFan => Some(SupportKind::Below),
        Block::DeadHornCoralWallFan => Some(SupportKind::AttachedFacing),
        Block::DeadTubeCoral => Some(SupportKind::Below),
        Block::DeadTubeCoralFan => Some(SupportKind::Below),
        Block::DeadTubeCoralWallFan => Some(SupportKind::AttachedFacing),
        Block::DetectorRail => Some(SupportKind::Below),
        Block::Fern => Some(SupportKind::Below),
        Block::FireCoral => Some(SupportKind::Below),
        Block::FireCoralFan => Some(SupportKind::Below),
        Block::FireCoralWallFan => Some(SupportKind::AttachedFacing),
        Block::FloweringAzalea => Some(SupportKind::Below),
        Block::GoldenDandelion => Some(SupportKind::Below),
        Block::GrayBanner => Some(SupportKind::Below),
        Block::GrayBed => Some(SupportKind::BedPart),
        Block::GrayCarpet => Some(SupportKind::Below),
        Block::GrayWallBanner => Some(SupportKind::AttachedFacing),
        Block::GreenBanner => Some(SupportKind::Below),
        Block::GreenBed => Some(SupportKind::BedPart),
        Block::GreenCarpet => Some(SupportKind::Below),
        Block::GreenWallBanner => Some(SupportKind::AttachedFacing),
        Block::Grindstone => Some(SupportKind::AttachFace),
        Block::HangingRoots => Some(SupportKind::Hanging),
        Block::HeavyWeightedPressurePlate => Some(SupportKind::Below),
        Block::HornCoral => Some(SupportKind::Below),
        Block::HornCoralFan => Some(SupportKind::Below),
        Block::HornCoralWallFan => Some(SupportKind::AttachedFacing),
        Block::IronDoor => Some(SupportKind::DoubleBlock),
        Block::JungleButton => Some(SupportKind::AttachFace),
        Block::JungleDoor => Some(SupportKind::DoubleBlock),
        Block::JungleHangingSign => Some(SupportKind::Hanging),
        Block::JunglePressurePlate => Some(SupportKind::Below),
        Block::JungleSapling => Some(SupportKind::Below),
        Block::JungleSign => Some(SupportKind::Below),
        Block::JungleWallHangingSign => Some(SupportKind::AttachedFacing),
        Block::JungleWallSign => Some(SupportKind::AttachedFacing),
        Block::Ladder => Some(SupportKind::AttachedFacing),
        Block::Lantern => Some(SupportKind::HangingOrBelow),
        Block::LargeAmethystBud => Some(SupportKind::AttachedFacing),
        Block::LargeFern => Some(SupportKind::DoubleBlock),
        Block::LeafLitter => Some(SupportKind::Below),
        Block::Lever => Some(SupportKind::AttachFace),
        Block::LightBlueBanner => Some(SupportKind::Below),
        Block::LightBlueBed => Some(SupportKind::BedPart),
        Block::LightBlueCarpet => Some(SupportKind::Below),
        Block::LightBlueWallBanner => Some(SupportKind::AttachedFacing),
        Block::LightGrayBanner => Some(SupportKind::Below),
        Block::LightGrayBed => Some(SupportKind::BedPart),
        Block::LightGrayCarpet => Some(SupportKind::Below),
        Block::LightGrayWallBanner => Some(SupportKind::AttachedFacing),
        Block::LightWeightedPressurePlate => Some(SupportKind::Below),
        Block::Lilac => Some(SupportKind::DoubleBlock),
        Block::LilyOfTheValley => Some(SupportKind::Below),
        Block::LimeBanner => Some(SupportKind::Below),
        Block::LimeBed => Some(SupportKind::BedPart),
        Block::LimeCarpet => Some(SupportKind::Below),
        Block::LimeWallBanner => Some(SupportKind::AttachedFacing),
        Block::MagentaBanner => Some(SupportKind::Below),
        Block::MagentaBed => Some(SupportKind::BedPart),
        Block::MagentaCarpet => Some(SupportKind::Below),
        Block::MagentaWallBanner => Some(SupportKind::AttachedFacing),
        Block::MangroveButton => Some(SupportKind::AttachFace),
        Block::MangroveDoor => Some(SupportKind::DoubleBlock),
        Block::MangroveHangingSign => Some(SupportKind::Hanging),
        Block::MangrovePressurePlate => Some(SupportKind::Below),
        Block::MangrovePropagule => Some(SupportKind::Below),
        Block::MangroveSign => Some(SupportKind::Below),
        Block::MangroveWallHangingSign => Some(SupportKind::AttachedFacing),
        Block::MangroveWallSign => Some(SupportKind::AttachedFacing),
        Block::MediumAmethystBud => Some(SupportKind::AttachedFacing),
        Block::MelonStem => Some(SupportKind::Below),
        Block::MossCarpet => Some(SupportKind::Below),
        Block::NetherSprouts => Some(SupportKind::Below),
        Block::NetherWart => Some(SupportKind::Below),
        Block::OakButton => Some(SupportKind::AttachFace),
        Block::OakDoor => Some(SupportKind::DoubleBlock),
        Block::OakHangingSign => Some(SupportKind::Hanging),
        Block::OakPressurePlate => Some(SupportKind::Below),
        Block::OakSapling => Some(SupportKind::Below),
        Block::OakSign => Some(SupportKind::Below),
        Block::OakWallHangingSign => Some(SupportKind::AttachedFacing),
        Block::OakWallSign => Some(SupportKind::AttachedFacing),
        Block::OpenEyeblossom => Some(SupportKind::Below),
        Block::OrangeBanner => Some(SupportKind::Below),
        Block::OrangeBed => Some(SupportKind::BedPart),
        Block::OrangeCarpet => Some(SupportKind::Below),
        Block::OrangeTulip => Some(SupportKind::Below),
        Block::OrangeWallBanner => Some(SupportKind::AttachedFacing),
        Block::OxeyeDaisy => Some(SupportKind::Below),
        Block::PaleOakButton => Some(SupportKind::AttachFace),
        Block::PaleOakDoor => Some(SupportKind::DoubleBlock),
        Block::PaleOakHangingSign => Some(SupportKind::Hanging),
        Block::PaleOakPressurePlate => Some(SupportKind::Below),
        Block::PaleOakSapling => Some(SupportKind::Below),
        Block::PaleOakSign => Some(SupportKind::Below),
        Block::PaleOakWallHangingSign => Some(SupportKind::AttachedFacing),
        Block::PaleOakWallSign => Some(SupportKind::AttachedFacing),
        Block::Peony => Some(SupportKind::DoubleBlock),
        Block::PinkBanner => Some(SupportKind::Below),
        Block::PinkBed => Some(SupportKind::BedPart),
        Block::PinkCarpet => Some(SupportKind::Below),
        Block::PinkPetals => Some(SupportKind::Below),
        Block::PinkTulip => Some(SupportKind::Below),
        Block::PinkWallBanner => Some(SupportKind::AttachedFacing),
        Block::PitcherCrop => Some(SupportKind::DoubleBlock),
        Block::PitcherPlant => Some(SupportKind::DoubleBlock),
        Block::PolishedBlackstoneButton => Some(SupportKind::AttachFace),
        Block::PolishedBlackstonePressurePlate => Some(SupportKind::Below),
        Block::Poppy => Some(SupportKind::Below),
        Block::Potatoes => Some(SupportKind::Below),
        Block::PoweredRail => Some(SupportKind::Below),
        Block::PumpkinStem => Some(SupportKind::Below),
        Block::PurpleBanner => Some(SupportKind::Below),
        Block::PurpleBed => Some(SupportKind::BedPart),
        Block::PurpleCarpet => Some(SupportKind::Below),
        Block::PurpleWallBanner => Some(SupportKind::AttachedFacing),
        Block::Rail => Some(SupportKind::Below),
        Block::RedBanner => Some(SupportKind::Below),
        Block::RedBed => Some(SupportKind::BedPart),
        Block::RedCarpet => Some(SupportKind::Below),
        Block::RedMushroom => Some(SupportKind::Below),
        Block::RedTulip => Some(SupportKind::Below),
        Block::RedWallBanner => Some(SupportKind::AttachedFacing),
        Block::RedstoneTorch => Some(SupportKind::Below),
        Block::RedstoneWallTorch => Some(SupportKind::AttachedFacing),
        Block::RedstoneWire => Some(SupportKind::Below),
        Block::Repeater => Some(SupportKind::Below),
        Block::RoseBush => Some(SupportKind::DoubleBlock),
        Block::SeaPickle => Some(SupportKind::Below),
        Block::Seagrass => Some(SupportKind::Below),
        Block::ShortDryGrass => Some(SupportKind::Below),
        Block::ShortGrass => Some(SupportKind::Below),
        Block::SmallAmethystBud => Some(SupportKind::AttachedFacing),
        Block::SmallDripleaf => Some(SupportKind::DoubleBlock),
        Block::Snow => Some(SupportKind::Below),
        Block::SoulLantern => Some(SupportKind::HangingOrBelow),
        Block::SoulTorch => Some(SupportKind::Below),
        Block::SoulWallTorch => Some(SupportKind::AttachedFacing),
        Block::SpruceButton => Some(SupportKind::AttachFace),
        Block::SpruceDoor => Some(SupportKind::DoubleBlock),
        Block::SpruceHangingSign => Some(SupportKind::Hanging),
        Block::SprucePressurePlate => Some(SupportKind::Below),
        Block::SpruceSapling => Some(SupportKind::Below),
        Block::SpruceSign => Some(SupportKind::Below),
        Block::SpruceWallHangingSign => Some(SupportKind::AttachedFacing),
        Block::SpruceWallSign => Some(SupportKind::AttachedFacing),
        Block::StoneButton => Some(SupportKind::AttachFace),
        Block::StonePressurePlate => Some(SupportKind::Below),
        Block::SugarCane => Some(SupportKind::Below),
        Block::Sunflower => Some(SupportKind::DoubleBlock),
        Block::SweetBerryBush => Some(SupportKind::Below),
        Block::TallDryGrass => Some(SupportKind::Below),
        Block::TallGrass => Some(SupportKind::DoubleBlock),
        Block::TallSeagrass => Some(SupportKind::DoubleBlock),
        Block::Torch => Some(SupportKind::Below),
        Block::Torchflower => Some(SupportKind::Below),
        Block::TorchflowerCrop => Some(SupportKind::Below),
        Block::TripwireHook => Some(SupportKind::AttachedFacing),
        Block::TubeCoral => Some(SupportKind::Below),
        Block::TubeCoralFan => Some(SupportKind::Below),
        Block::TubeCoralWallFan => Some(SupportKind::AttachedFacing),
        Block::TwistingVinesPlant => Some(SupportKind::Below),
        Block::WallTorch => Some(SupportKind::AttachedFacing),
        Block::WarpedButton => Some(SupportKind::AttachFace),
        Block::WarpedDoor => Some(SupportKind::DoubleBlock),
        Block::WarpedFungus => Some(SupportKind::Below),
        Block::WarpedHangingSign => Some(SupportKind::Hanging),
        Block::WarpedPressurePlate => Some(SupportKind::Below),
        Block::WarpedRoots => Some(SupportKind::Below),
        Block::WarpedSign => Some(SupportKind::Below),
        Block::WarpedWallHangingSign => Some(SupportKind::AttachedFacing),
        Block::WarpedWallSign => Some(SupportKind::AttachedFacing),
        Block::WeepingVinesPlant => Some(SupportKind::Hanging),
        Block::Wheat => Some(SupportKind::Below),
        Block::WhiteBanner => Some(SupportKind::Below),
        Block::WhiteBed => Some(SupportKind::BedPart),
        Block::WhiteCarpet => Some(SupportKind::Below),
        Block::WhiteTulip => Some(SupportKind::Below),
        Block::WhiteWallBanner => Some(SupportKind::AttachedFacing),
        Block::Wildflowers => Some(SupportKind::Below),
        Block::WitherRose => Some(SupportKind::Below),
        Block::YellowBanner => Some(SupportKind::Below),
        Block::YellowBed => Some(SupportKind::BedPart),
        Block::YellowCarpet => Some(SupportKind::Below),
        Block::YellowWallBanner => Some(SupportKind::AttachedFacing),
        _ => None,
    }
}

/// The one cell `state` at `pos` depends on, or `None` when nothing about this
/// block's existence is conditional.
#[must_use]
pub(crate) fn requirement(pos: BlockPos, state: StateId) -> Option<Requirement> {
    let block = state.block();
    let below = BlockPos::new(pos.x, pos.y - 1, pos.z);
    let above = BlockPos::new(pos.x, pos.y + 1, pos.z);
    match support_kind(block)? {
        SupportKind::Below => Some(Requirement::Supported(below)),
        SupportKind::Hanging => Some(Requirement::Supported(above)),
        SupportKind::HangingOrBelow => {
            // `hanging` ? UP : DOWN, and the survival check reads the cell
            // that direction's *opposite* leads to.
            let hanging = get_str_property(state, PropertyKey::Hanging)
                == Some(BuiltinPropertyValue::True);
            Some(Requirement::Supported(if hanging { above } else { below }))
        }
        SupportKind::AttachedFacing => {
            // The cell opposite the block's own facing direction. A state naming no
            // `facing` is not a legal wall variant, so there is nothing to check.
            let facing = direction_from_property(get_str_property(state, PropertyKey::Facing)?)?;
            Some(Requirement::Supported(facing.opposite().relative(pos)))
        }
        SupportKind::AttachFace => {
            // `crate::redstone::attached_connected_direction` computes exactly
            // this connected direction; the survival check looks the other way.
            let connected = attached_connected_direction(state);
            Some(Requirement::Supported(connected.opposite().relative(pos)))
        }
        SupportKind::DoubleBlock => match get_str_property(state, PropertyKey::Half) {
            // The upper arm's rule: the cell below must be this same block
            // with `half=lower`.
            Some(BuiltinPropertyValue::Upper) => Some(Requirement::Partner {
                pos: below,
                block,
                property: PropertyKey::Half,
                value: BuiltinPropertyValue::Lower,
            }),
            // The lower arm is the ordinary support test. A state naming no
            // `half` is treated as the lower half, which is what the default
            // state of every block in this family is.
            _ => Some(Requirement::Supported(below)),
        },
        SupportKind::BedPart => {
            // The foot looks along `facing`, the head against it. Both halves
            // fail to air when the partner is not there, which is what makes
            // breaking one end break the other.
            let facing = direction_from_property(get_str_property(state, PropertyKey::Facing)?)?;
            let (partner_dir, want) = match get_str_property(state, PropertyKey::Part) {
                Some(BuiltinPropertyValue::Head) => (facing.opposite(), BuiltinPropertyValue::Foot),
                _ => (facing, BuiltinPropertyValue::Head),
            };
            Some(Requirement::Partner {
                pos: partner_dir.relative(pos),
                block,
                property: PropertyKey::Part,
                value: want,
            })
        }
    }
}

/// Whether `state` at `pos` still has its support, reading the world through
/// `block_at`.
///
/// `true` for every block this crate models no rule for, so this is safe to ask
/// of an arbitrary cell.
pub(crate) fn survives<F>(pos: BlockPos, state: StateId, block_at: F) -> bool
where
    F: Fn(BlockPos) -> WorldState,
{
    let Some(requirement) = requirement(pos, state) else {
        return true;
    };
    match requirement {
        Requirement::Supported(cell) => !is_air_or_fluid_id(block_at(cell)),
        Requirement::Partner {
            pos: cell,
            block,
            property,
            value,
        } => {
            let partner = block_at(cell);
            partner.block() == block && get_str_property(partner, property) == Some(value)
        }
    }
}

/// Returns the support rule for every block family with one named support cell.

#[cfg(test)]
mod tests {
    use super::*;

    fn pos() -> BlockPos {
        BlockPos::new(4, 70, -9)
    }

    #[test]
    fn every_supported_block_is_builtin() {
        assert_eq!(
            Block::all().filter(|&block| support_kind(block).is_some()).count(),
            291
        );
    }

    #[test]
    fn unsupported_blocks_are_absent() {
        for block in [
            Block::SkeletonSkull,
            Block::ZombieHead,
            Block::TurtleEgg,
            Block::SnifferEgg,
            Block::Tripwire,
            Block::LilyPad,
            Block::Frogspawn,
            Block::Stone,
            Block::Dirt,
            Block::Cobweb,
            Block::Vine,
            Block::Scaffolding,
        ] {
            assert!(support_kind(block).is_none(), "unexpected support rule for {block:?}");
        }
    }

    /// The blocks whose ancestors declare no survival check must answer
    /// `None` — they were removed from the generator's output deliberately,
    /// and a regression here means skulls start popping off floors.
    #[test]
    fn blocks_with_no_vanilla_can_survive_are_absent() {
        let mut wrongly_present = Vec::new();
        for block in [
            Block::SkeletonSkull,
            Block::ZombieHead,
            Block::TurtleEgg,
            Block::SnifferEgg,
            Block::Tripwire,
            Block::LilyPad,
            Block::Frogspawn,
            Block::Stone,
            Block::Dirt,
            Block::Cobweb,
            Block::Vine,
            Block::Scaffolding,
        ] {
            if support_kind(block).is_some() {
                wrongly_present.push(block);
            }
        }
        assert!(
            wrongly_present.is_empty(),
            "these have no single-cell survival check in 26.2: {wrongly_present:?}"
        );
    }

    /// One assertion per family shape, collected rather than asserted in the
    /// loop so a broken arm does not hide the other five.
    #[test]
    fn each_family_reads_the_cell_vanilla_reads() {
        let p = pos();
        let cases: Vec<(&str, StateId, Requirement)> = vec![
            // A floor torch's support is below.
            (
                "floor torch",
                state("minecraft:torch"),
                Requirement::Supported(BlockPos::new(p.x, p.y - 1, p.z)),
            ),
            // A wall torch's support is the wall it points away from.
            // `facing=east` means the wall is west.
            (
                "wall torch",
                state("minecraft:wall_torch[facing=east]"),
                Requirement::Supported(BlockPos::new(p.x - 1, p.y, p.z)),
            ),
            // A lever's `face=floor` connects UP, so the support is below.
            (
                "floor lever",
                state("minecraft:lever[face=floor,facing=north]"),
                Requirement::Supported(BlockPos::new(p.x, p.y - 1, p.z)),
            ),
            // `face=ceiling` connects DOWN, so the support is above.
            (
                "ceiling lever",
                state("minecraft:lever[face=ceiling,facing=north]"),
                Requirement::Supported(BlockPos::new(p.x, p.y + 1, p.z)),
            ),
            // A rail's support is below.
            (
                "rail",
                state("minecraft:rail[shape=north_south]"),
                Requirement::Supported(BlockPos::new(p.x, p.y - 1, p.z)),
            ),
            // A door's upper arm: the cell below must be the same door's
            // lower half.
            (
                "door upper half",
                state("minecraft:oak_door[half=upper,facing=north]"),
                Requirement::Partner {
                    pos: BlockPos::new(p.x, p.y - 1, p.z),
                    block: Block::OakDoor,
                    property: PropertyKey::Half,
                    value: BuiltinPropertyValue::Lower,
                },
            ),
            // Small dripleaf has the same upper/lower partner rule as the
            // other two-cell plants, even though its lower half also carries
            // direction and water state.
            (
                "small dripleaf upper half",
                state("minecraft:small_dripleaf[half=upper,facing=north,waterlogged=false]"),
                Requirement::Partner {
                    pos: BlockPos::new(p.x, p.y - 1, p.z),
                    block: Block::SmallDripleaf,
                    property: PropertyKey::Half,
                    value: BuiltinPropertyValue::Lower,
                },
            ),
            // A bed's foot looks along `facing`, and `facing=south` is +z.
            (
                "bed foot",
                state("minecraft:red_bed[part=foot,facing=south]"),
                Requirement::Partner {
                    pos: BlockPos::new(p.x, p.y, p.z + 1),
                    block: Block::RedBed,
                    property: PropertyKey::Part,
                    value: BuiltinPropertyValue::Head,
                },
            ),
            // A hanging sign hangs from the cell above.
            (
                "ceiling hanging sign",
                state("minecraft:oak_hanging_sign[rotation=0]"),
                Requirement::Supported(BlockPos::new(p.x, p.y + 1, p.z)),
            ),
            // A hanging lantern's support is above.
            (
                "hanging lantern",
                state("minecraft:lantern[hanging=true]"),
                Requirement::Supported(BlockPos::new(p.x, p.y + 1, p.z)),
            ),
            (
                "standing lantern",
                state("minecraft:lantern[hanging=false]"),
                Requirement::Supported(BlockPos::new(p.x, p.y - 1, p.z)),
            ),
        ];
        let mut mismatches = Vec::new();
        for (label, state, expected) in cases {
            let got = requirement(p, state);
            if got.as_ref() != Some(&expected) {
                mismatches.push(format!("{label}: expected {expected:?}, got {got:?}"));
            }
        }
        assert!(mismatches.is_empty(), "{mismatches:#?}");
    }

    /// The two directions of [`survives`] for one support cell, so the
    /// predicate is shown to be able to answer both ways rather than being
    /// constant.
    #[test]
    fn a_plant_survives_on_dirt_and_not_on_air_or_water() {
        let p = pos();
        let below = BlockPos::new(p.x, p.y - 1, p.z);
        let with = |fill: &'static str| {
            move |cell: BlockPos| {
                if cell == below {
                    state(fill)
                } else {
                    state("minecraft:air")
                }
            }
        };
        assert!(survives(p, state("minecraft:poppy"), with("minecraft:dirt")));
        assert!(!survives(p, state("minecraft:poppy"), with("minecraft:air")));
        assert!(
            !survives(p, state("minecraft:poppy"), with("minecraft:water[level=0]")),
            "a fluid is not a support"
        );
        // And the un-modelled majority is unaffected in both worlds.
        assert!(survives(p, state("minecraft:stone"), with("minecraft:air")));
    }

    /// A bed's partner test is on identity, not on presence: a *different*
    /// bed colour, or the same `part`, must both fail. The same-`part` case is
    /// the one a "is there a bed next door" implementation gets wrong.
    #[test]
    fn a_bed_half_needs_the_opposite_half_of_the_same_bed() {
        let p = pos();
        let partner = BlockPos::new(p.x, p.y, p.z + 1);
        let with = |fill: &'static str| {
            move |cell: BlockPos| {
                if cell == partner {
                    state(fill)
                } else {
                    state("minecraft:air")
                }
            }
        };
        let foot = state("minecraft:red_bed[part=foot,facing=south]");
        let mut wrong = Vec::new();
        if !survives(p, foot, with("minecraft:red_bed[part=head,facing=south]")) {
            wrong.push("the matching head must support the foot");
        }
        if survives(p, foot, with("minecraft:red_bed[part=foot,facing=south]")) {
            wrong.push("two feet must not support each other");
        }
        if survives(p, foot, with("minecraft:blue_bed[part=head,facing=south]")) {
            wrong.push("a different bed block must not count as the partner");
        }
        if survives(p, foot, with("minecraft:stone")) {
            wrong.push("an ordinary block must not count as the partner");
        }
        assert!(wrong.is_empty(), "{wrong:#?}");
    }

    fn state(text: &str) -> StateId {
        StateId::from_state_str(text).expect("fixture state must resolve")
    }
}
