//! Embeds every JSON file under `assets/<registry>/` as an `include_str!` table.
//!
//! One generated table per registry directory, each a sorted `&[(&str, &str)]` of
//! `(name-without-extension, contents)`, so the order is independent of `read_dir`.

use std::fs;
use std::path::{Path, PathBuf};

fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(read) = fs::read_dir(dir) else { return };
    for entry in read.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else if path.extension().is_some_and(|e| e == "json" || e == "nbt") {
            let rel = path.strip_prefix(root).expect("under root").with_extension("");
            out.push((rel.to_string_lossy().replace('\\', "/"), path));
        }
    }
}

fn main() {
    let assets = manifest_dir().join("assets");
    println!("cargo::rerun-if-changed=assets");
    let mut code = String::from("// @generated by build.rs; do not edit.\n");
    let mut registries: Vec<String> = fs::read_dir(&assets)
        .map(|r| r.flatten().filter(|e| e.path().is_dir()).map(|e| e.file_name().to_string_lossy().into_owned()).collect())
        .unwrap_or_default();
    registries.sort();
    for registry in &registries {
        let root = assets.join(registry);
        let mut entries = Vec::new();
        collect(&root, &root, &mut entries);
        entries.sort_by(|a, b| a.0.cmp(&b.0));
        // A registry of binary templates is a `(name, bytes)` table; every other one is text.
        let binary = entries.iter().any(|(_, p)| p.extension().is_some_and(|e| e == "nbt"));
        if binary {
            code.push_str(&format!("pub static {}: &[(&str, &[u8])] = &[\n", registry.to_uppercase()));
        } else {
            code.push_str(&format!("pub static {}: &[(&str, &str)] = &[\n", registry.to_uppercase()));
        }
        for (name, path) in &entries {
            let include = if binary { "include_bytes" } else { "include_str" };
            // Relative to the crate root and resolved when the crate compiles: the
            // generated file lives in a target directory several checkouts share,
            // so an absolute path here would point at whichever checkout ran the
            // script last.
            let relative = path.strip_prefix(manifest_dir()).expect("asset under the crate").to_string_lossy().replace('\\', "/");
            code.push_str(&format!(
                "    ({name:?}, {include}!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{relative}\"))),\n"
            ));
        }
        code.push_str("];\n");
    }
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("embedded.rs");
    fs::write(out, code).expect("write generated table");
}

/// The crate directory, read when the script runs. `env!` would bake the
/// compiling checkout's path into the script binary, which a compiler cache can
/// then hand to a different checkout.
fn manifest_dir() -> std::path::PathBuf {
    std::path::PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").expect("Cargo supplies CARGO_MANIFEST_DIR"))
}
