//! Legacy sound-id→name table for protocol 340: hermetic checks over the
//! committed table, plus an `#[ignore]`d drift guard that regenerates it
//! from the vendored `minecraft-data` project and asserts byte-for-byte
//! equality. Modelled directly on `tests/item_types.rs`'s
//! generate/commit/drift-check shape.
//!
//! Regenerate the committed table after a data bump with:
//!
//! ```text
//! LODESTONE_REGEN=1 cargo test -p lodestone-v340 --test sound_ids \
//!     committed_table_matches_source -- --ignored --nocapture
//! ```

use std::path::PathBuf;

use lodestone_v340::sound_ids::{self, SOUND_ID_COUNT};

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn source_path() -> PathBuf {
    manifest_dir().join("../../../vendor/minecraft-data/data/pc/1.12.2/sounds.json")
}

fn committed_path() -> PathBuf {
    manifest_dir().join("src/generated/sound_ids.rs")
}

// ---------------------------------------------------------------------------
// Generator (shared by regen and the drift check)
// ---------------------------------------------------------------------------

/// Parses `sounds.json` into a wire-order name list, asserting the id space
/// is contiguous `0..N` — the table indexes directly by id rather than
/// binary-searching sorted pairs, so a gap would silently misalign every
/// entry after it.
fn parse_names(doc: &serde_json::Value) -> Vec<String> {
    let entries = doc.as_array().expect("sounds.json is an array");
    let mut pairs: Vec<(i64, String)> = entries
        .iter()
        .map(|entry| {
            let id = entry
                .get("id")
                .and_then(serde_json::Value::as_i64)
                .expect("sound entry has an integer id");
            let name = entry
                .get("name")
                .and_then(serde_json::Value::as_str)
                .expect("sound entry has a name");
            (id, name.to_owned())
        })
        .collect();
    pairs.sort_by_key(|(id, _)| *id);
    for (index, (id, _)) in pairs.iter().enumerate() {
        assert_eq!(
            *id, index as i64,
            "sounds.json id space is not contiguous 0..N at index {index}"
        );
    }
    pairs.into_iter().map(|(_, name)| name).collect()
}

fn generate(doc: &serde_json::Value) -> String {
    let names = parse_names(doc);

    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo test -p lodestone-v340 --test sound_ids -- --ignored`\n\
         // from vendor/minecraft-data/data/pc/1.12.2/sounds.json (protocol 340 /\n\
         // Minecraft 1.12.2). DO NOT EDIT BY HAND. Regenerate with LODESTONE_REGEN=1\n\
         // (see the test module docs).\n",
    );
    out.push_str(
        "//! Generated legacy `SoundEvent` id->name table for protocol 340 (Minecraft 1.12.2).\n//!\n",
    );
    out.push_str(
        "//! Maps the numeric `sound_effect` packet's `SoundEvent` registry id to its\n\
         //! bare (unnamespaced) legacy name. Consumed by [`crate::sound_ids`].\n\n",
    );
    out.push_str("/// Number of legacy sound entries (network ids are `0..SOUND_ID_COUNT`).\n");
    out.push_str(&format!("pub const SOUND_ID_COUNT: usize = {};\n\n", names.len()));
    out.push_str("/// Legacy sound name, without a namespace prefix, indexed by network id.\n");
    out.push_str(&format!(
        "pub static SOUND_ID_NAMES: [&str; SOUND_ID_COUNT] = [\n"
    ));
    for name in &names {
        out.push_str(&format!("    \"{name}\",\n"));
    }
    out.push_str("];\n");

    out
}

// ---------------------------------------------------------------------------
// Hermetic tests over the committed table (no source needed)
// ---------------------------------------------------------------------------

#[test]
fn table_is_non_empty_and_out_of_range_is_none() {
    assert!(sound_ids::sound_name(0).is_some(), "table populated");
    assert_eq!(sound_ids::sound_name(-1), None);
    assert_eq!(sound_ids::sound_name(i32::MAX), None);
}

#[test]
fn known_ids_resolve_to_namespaced_identifiers() {
    assert_eq!(
        sound_ids::sound_name(0),
        Some("minecraft:ambient.cave".to_owned())
    );
    assert_eq!(
        sound_ids::sound_name(1),
        Some("minecraft:block.anvil.break".to_owned())
    );
    let last = sound_ids::sound_name((SOUND_ID_COUNT - 1) as i32).expect("last id resolves");
    assert!(last.starts_with("minecraft:"));
}

#[test]
fn every_resolved_name_is_a_valid_resource_key() {
    for id in 0..SOUND_ID_COUNT as i32 {
        let name = sound_ids::sound_name(id).expect("in-range id resolves");
        let _key: lodestone_model::ResourceKey = name.parse().expect("valid resource key");
    }
}

// ---------------------------------------------------------------------------
// Drift guard (needs the vendored source; #[ignore]d so the suite stays hermetic)
// ---------------------------------------------------------------------------

#[test]
#[ignore = "reads the gitignored vendor/minecraft-data; run explicitly to regen/verify"]
fn committed_table_matches_source() {
    let raw = std::fs::read_to_string(source_path())
        .expect("sounds.json present under vendor/minecraft-data/data/pc/1.12.2");
    let doc: serde_json::Value = serde_json::from_str(&raw).expect("sounds.json parses");
    let generated = generate(&doc);

    if std::env::var_os("LODESTONE_REGEN").is_some() {
        std::fs::write(committed_path(), &generated).expect("write committed table");
        eprintln!("regenerated {}", committed_path().display());
        return;
    }

    let committed = std::fs::read_to_string(committed_path()).expect("committed table present");
    assert_eq!(
        generated, committed,
        "src/generated/sound_ids.rs is stale vs sounds.json; regenerate with LODESTONE_REGEN=1"
    );

    let names = parse_names(&doc);
    assert_eq!(names.len(), SOUND_ID_COUNT, "sound count mismatch");
    let mut mismatches = 0usize;
    for (id, name) in names.iter().enumerate() {
        if sound_ids::sound_name(id as i32) != Some(format!("minecraft:{name}")) {
            mismatches += 1;
        }
    }
    println!("=== SOUND-ID TABLE REPORT (protocol 340) ===");
    println!("sound ids  : {SOUND_ID_COUNT}");
    println!("mismatches : {mismatches}");
    println!("=============================================");
    assert_eq!(mismatches, 0, "committed table disagrees with sounds.json");
}
