//! Entity-type id→name table for protocol 754: hermetic checks over the
//! committed table, plus an `#[ignore]`d drift guard that regenerates it from
//! the vendored `minecraft-data` project and asserts byte-for-byte equality
//! (modelled on the v770 entity-type table and the packet-id generator).
//!
//! 1.13 flattening **unified** the entity registry: 1.12's two id spaces (a
//! `spawn_mob` mob table and a `spawn_object` object table) collapsed into a
//! single numeric registry that both `spawn_entity` and `spawn_entity_living`
//! index. So there is exactly one table here, not two. The oracle is
//! `minecraft-data` (`vendor/minecraft-data/data/pc/1.16.2/entities.json`,
//! which 1.16.5 shares per `dataPaths.json`; gitignored).
//!
//! `minecraft-data`'s 1.16 `name` fields are already lowercase snake_case, so
//! there is no casing judgement. The `type` field is unreliable in this dump
//! (several 1.16 mobs are tagged `UNKNOWN`), so the generator keys off `id`
//! and includes every entry rather than filtering by category.
//!
//! Regenerate the committed table after a data bump with:
//!
//! ```text
//! LODESTONE_REGEN=1 cargo test -p lodestone-v735 --test entity_types \
//!     committed_tables_match_source -- --ignored --nocapture
//! ```

use std::fmt::Write as _;
use std::path::PathBuf;

use lodestone_v735::entity_types::{self, ENTITY_TYPE_COUNT};

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Vendored community data (gitignored local artifact). 1.16.5 shares
/// 1.16.2's entity registry per `minecraft-data`'s `dataPaths.json`.
fn source_path() -> PathBuf {
    manifest_dir().join("../../../vendor/minecraft-data/data/pc/1.16.2/entities.json")
}

fn committed_path() -> PathBuf {
    manifest_dir().join("src/generated/entity_types.rs")
}

// ---------------------------------------------------------------------------
// Generator (shared by regen and the drift check)
// ---------------------------------------------------------------------------

/// Converts a `minecraft-data` name to a canonical lowercase path: spaces
/// become underscores and CamelCase word boundaries gain an underscore. For
/// 1.16 this is a no-op on every name, but it is kept for defensiveness.
fn snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    let mut prev_lower_or_digit = false;
    for ch in name.chars() {
        if ch == ' ' || ch == '-' {
            if !out.ends_with('_') && !out.is_empty() {
                out.push('_');
            }
            prev_lower_or_digit = false;
            continue;
        }
        if ch.is_ascii_uppercase() {
            if prev_lower_or_digit {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
            prev_lower_or_digit = false;
        } else {
            out.push(ch);
            prev_lower_or_digit = ch.is_ascii_lowercase() || ch.is_ascii_digit();
        }
    }
    out
}

/// Parses `entities.json` into a sorted `(id, identifier)` table over the
/// whole unified registry (every entry, keyed by `id`).
fn parse_entities(doc: &serde_json::Value) -> Vec<(i32, String)> {
    let entries = doc.as_array().expect("entities.json is an array");
    let mut pairs: Vec<(i32, String)> = entries
        .iter()
        .map(|entry| {
            let id = entry
                .get("id")
                .and_then(serde_json::Value::as_i64)
                .expect("entity entry has an integer id") as i32;
            let name = entry
                .get("name")
                .and_then(serde_json::Value::as_str)
                .expect("entity entry has a name");
            (id, format!("minecraft:{}", snake_case(name)))
        })
        .collect();
    pairs.sort_by_key(|(id, _)| *id);
    for window in pairs.windows(2) {
        assert_ne!(
            window[0].0, window[1].0,
            "duplicate entity id {} in entities.json",
            window[0].0
        );
    }
    pairs
}

fn render_table(out: &mut String, const_name: &str, count_name: &str, pairs: &[(i32, String)]) {
    let _ = writeln!(
        out,
        "/// Number of {} type entries.",
        const_name.to_lowercase()
    );
    let _ = writeln!(out, "pub const {count_name}: usize = {};\n", pairs.len());
    let _ = writeln!(
        out,
        "/// `(type id, canonical identifier)` pairs, sorted by id for binary search."
    );
    let _ = writeln!(
        out,
        "pub static {const_name}: [(i32, &str); {}] = [",
        pairs.len()
    );
    for (id, name) in pairs {
        let _ = writeln!(out, "    ({id}, \"{name}\"),");
    }
    out.push_str("];\n\n");
}

fn generate(doc: &serde_json::Value) -> String {
    let entities = parse_entities(doc);

    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo test -p lodestone-v735 --test entity_types -- --ignored`\n\
         // from vendor/minecraft-data/data/pc/1.16.2/entities.json (protocol 754 /\n\
         // Minecraft 1.16.5). DO NOT EDIT BY HAND. Regenerate with LODESTONE_REGEN=1\n\
         // (see the test module docs).\n",
    );
    out.push_str(
        "//! Generated entity-type id->name table for protocol 754 (Minecraft 1.16.5).\n//!\n",
    );
    out.push_str(
        "//! Maps the unified 1.16 numeric entity-type id space to canonical\n\
         //! `minecraft:*` identifiers. Consumed by [`crate::entity_types`].\n\n",
    );

    render_table(&mut out, "ENTITY_TYPES", "ENTITY_TYPE_COUNT", &entities);

    out
}

// ---------------------------------------------------------------------------
// Hermetic tests over the committed table (no source needed)
// ---------------------------------------------------------------------------

#[test]
fn table_is_non_empty_and_out_of_range_is_none() {
    assert!(
        entity_types::entity_type_name(12).is_some(),
        "entity table populated"
    );
    assert_eq!(entity_types::entity_type_name(-1), None);
    assert_eq!(entity_types::entity_type_name(i32::MAX), None);
    // The mob/object aliases resolve through the same unified table.
    assert_eq!(entity_types::mob_type_name(-1), None);
    assert_eq!(entity_types::object_type_name(i32::MAX), None);
}

#[test]
fn known_ids_resolve_to_well_formed_identifiers() {
    // Spot 1.16 unified ids the live seam relies on; a transposed table fails
    // instantly.
    assert_eq!(entity_types::entity_type_name(12), Some("minecraft:creeper"));
    assert_eq!(entity_types::entity_type_name(59), Some("minecraft:pig"));
    assert_eq!(entity_types::entity_type_name(102), Some("minecraft:zombie"));
    assert_eq!(entity_types::entity_type_name(2), Some("minecraft:arrow"));
    assert_eq!(entity_types::entity_type_name(6), Some("minecraft:boat"));
    assert_eq!(entity_types::entity_type_name(106), Some("minecraft:player"));
    // Both spawn aliases index the unified registry in 1.16.
    assert_eq!(entity_types::mob_type_name(59), Some("minecraft:pig"));
    assert_eq!(entity_types::object_type_name(6), Some("minecraft:boat"));
    assert_eq!(entity_types::PLAYER, "minecraft:player");
}

#[test]
fn identifiers_have_lowercase_paths() {
    for id in 0..256 {
        if let Some(name) = entity_types::entity_type_name(id) {
            let path = name
                .strip_prefix("minecraft:")
                .expect("namespaced identifier");
            assert!(!path.is_empty(), "id {id} has an empty path");
            assert!(
                path.chars().all(|c| c.is_ascii_lowercase()
                    || c.is_ascii_digit()
                    || matches!(c, '_' | '.' | '-' | '/')),
                "id {id} identifier {name:?} has an invalid path character"
            );
            let _key: lodestone_model::ResourceKey = name.parse().expect("valid resource key");
        }
    }
}

// ---------------------------------------------------------------------------
// Drift guard (needs the vendored source; #[ignore]d so the suite stays hermetic)
// ---------------------------------------------------------------------------

#[test]
#[ignore = "reads the gitignored vendor/minecraft-data; run explicitly to regen/verify"]
fn committed_tables_match_source() {
    let raw = std::fs::read_to_string(source_path())
        .expect("entities.json present under vendor/minecraft-data/data/pc/1.16.2");
    let doc: serde_json::Value = serde_json::from_str(&raw).expect("entities.json parses");
    let generated = generate(&doc);

    if std::env::var_os("LODESTONE_REGEN").is_some() {
        std::fs::write(committed_path(), &generated).expect("write committed tables");
        eprintln!("regenerated {}", committed_path().display());
        return;
    }

    let committed = std::fs::read_to_string(committed_path()).expect("committed tables present");
    assert_eq!(
        generated, committed,
        "src/generated/entity_types.rs is stale vs entities.json; regenerate with LODESTONE_REGEN=1"
    );

    let entities = parse_entities(&doc);
    assert_eq!(entities.len(), ENTITY_TYPE_COUNT, "entity count mismatch");
    let mut mismatches = 0usize;
    for (id, name) in &entities {
        if entity_types::entity_type_name(*id) != Some(name.as_str()) {
            mismatches += 1;
        }
    }
    println!("=== ENTITY-TYPE TABLE REPORT (protocol 754) ===");
    println!("entity types : {ENTITY_TYPE_COUNT}");
    println!("mismatches   : {mismatches}");
    println!("===============================================");
    assert_eq!(
        mismatches, 0,
        "committed table disagrees with entities.json"
    );
}
