//! The shell's local world, generated by the **real** Lodestone worldgen
//! pipeline.
//!
//! Until recently this file was a 189-line sine+hash stand-in. It now calls
//! [`lodestone_server::overworld_generator`], which wraps the version-free,
//! JVM-verified `lodestone-worldgen` pipeline (noise router → interpolated
//! density → sea-level aquifer approximation → surface rules), so the terrain on
//! screen is real vanilla shape+surface for a fixed seed — the same block field
//! `chunk_parity`/`surface_parity` prove bit-for-bit against a JVM.
//!
//! # Why a direct call (and how it stays replaceable)
//!
//! Vanilla singleplayer runs an integrated server that streams chunks to the
//! client over a loopback connection; that is the faithful end state and
//! `lodestone-server` already hosts it (`lodestone_server::IntegratedServer`).
//! This module deliberately takes the *direct* path instead — build the
//! generator once, call [`OverworldGenerator::column`] per chunk — because it
//! closes the island today without waiting on the client's clientbound chunk
//! decode seam. The seam is drawn so the integrated-server path replaces the
//! *call site here*, not the generator: everything below `generate_column` is
//! already the shared code multiplayer uses.
//!
//! # Honest scope of what renders
//!
//! The composed generator produces real terrain **shape + surface**, and — since
//! the feature stage was chained in — **ores and vegetation** as well. Enumerated
//! rather than assumed, by walking every state of chunks `(-2..=2)²` at seed 3
//! and collecting distinct base names, it emits: stone/deepslate/andesite/
//! diorite/granite/tuff/clay/gravel/dirt/grass_block/water; the full ore set
//! (coal, copper, iron, gold, lapis, redstone, diamond, plus the deepslate
//! variants); `oak`/`birch`/`dark_oak` logs and leaves; and the non-solid plants
//! `bush`, `short_grass`, `leaf_litter`, `wildflowers`, `lilac`, `peony`,
//! `rose_bush`, `lily_of_the_valley`. Carvers (no caves) and the full aquifer
//! (no underground water/lava pockets) are still absent, and generation runs a
//! single fixed biome (plains) until the multi-noise biome source lands.
//!
//! **That list is load-bearing for [`map_block`]**, whose `_ =>` fallback is
//! `STONE`: while this doc still claimed features did not run, every tree in the
//! local world rendered as a solid stone pillar and every flower as a solid
//! stone cube. Re-run the enumeration after chaining in another stage rather
//! than trusting this paragraph.
//!
//! # Vertical windowing
//!
//! The real overworld spans world Y `-64..=319`. The shell renders a window
//! `[MIN_Y, MIN_Y + SECTION_COUNT*16)` of that same world coordinate space
//! (shell Y **is** world Y). Everything below `MIN_Y` is solid stone the player
//! never sees, so dropping it keeps meshing cheap; the bottom row is forced to
//! bedrock for a guaranteed sealed floor.

use std::sync::OnceLock;

use lodestone_server::{OverworldGenerator, overworld_generator};
use lodestone_world::{
    ChunkColumn, ChunkPos, Heightmaps, LoadedChunk, PaletteKind, World, compute_column_light,
};

use crate::blocks::{DemoLightProps, id};

/// Fixed world seed. Chosen so the origin column is pleasant dry grassland
/// (surface ≈ y70) rather than mid-ocean, which seed 42's origin happens to be.
pub const WORLD_SEED: i64 = 3;

/// World vertical layout: lowest rendered block at y=0 (= world y 0).
pub const MIN_Y: i32 = 0;
/// Number of 16-tall sections rendered per column (96 blocks — covers plains
/// surface ≈ y64–90 with headroom).
pub const SECTION_COUNT: usize = 6;
/// Vanilla overworld sea level; non-solid blocks below it are water.
pub const SEA_LEVEL: i32 = 63;

/// Exclusive top of the rendered window in world Y.
const TOP_Y: i32 = MIN_Y + (SECTION_COUNT as i32) * 16;

/// The bundled overworld generator, built once (the density tree + surface
/// noises are seed-dependent and non-trivial to construct, so this is shared
/// across every column and every `surface_height` query).
fn generator() -> &'static OverworldGenerator {
    static GEN: OnceLock<OverworldGenerator> = OnceLock::new();
    GEN.get_or_init(|| overworld_generator(WORLD_SEED))
}

/// Strips any `[properties]` suffix from a block-state string.
fn base(name: &str) -> &str {
    name.split('[').next().unwrap_or(name)
}

/// Whether a block name is a log-shaped full cube — a log, a stripped log, or a
/// `_wood` block. All of them take the demo palette's `LOG` sprite pair.
fn is_log(name: &str) -> bool {
    name.ends_with("_log") || name.ends_with("_wood") || name.ends_with("_stem")
}

/// Maps a vanilla block-state name onto the shell's tiny demo palette.
///
/// The arms cover exactly the names the module doc's enumeration says the
/// composed generator emits; unknown **solid** blocks fall back to stone, a safe
/// always-in-atlas id.
///
/// # The fallback is only safe for solids
///
/// `_ => STONE` is wrong for two whole categories the feature stage introduced,
/// and both were shipping:
///
/// * **Trees.** `oak`/`birch`/`dark_oak` logs and leaves have had `id::LOG` and
///   `id::LEAVES` in [`crate::blocks`] — sprites, tint colours, and a light
///   opacity of 1 for leaves — since before this module called the real
///   generator. Nothing mapped onto them, so every tree drew as a solid stone
///   pillar under a solid stone canopy, and the canopy blocked skylight like
///   stone instead of attenuating it by 1.
/// * **Plants.** `bush`, `short_grass`, `leaf_litter`, `wildflowers`, `lilac`,
///   `peony`, `rose_bush` and `lily_of_the_valley` have no collision and no
///   full-cube model in vanilla, and the demo palette has no cross-quad sprite
///   to draw them with. They map to **air**, not stone: a stone cube there is
///   wrong in three separate ways at once — it draws a grey block on the grass,
///   it blocks the player's movement, and it blocks skylight. Air is the honest
///   rendering of "this palette cannot draw a flower", and it is what the old
///   sine-terrain world showed.
fn map_block(name: &str) -> u32 {
    match base(name) {
        "minecraft:air" | "minecraft:cave_air" | "minecraft:void_air" => id::AIR,
        // Non-solid vegetation the demo palette has no model for. See above:
        // air rather than the `_` fallback, which would be a solid cube.
        "minecraft:bush"
        | "minecraft:short_grass"
        | "minecraft:tall_grass"
        | "minecraft:fern"
        | "minecraft:large_fern"
        | "minecraft:dead_bush"
        | "minecraft:leaf_litter"
        | "minecraft:wildflowers"
        | "minecraft:lilac"
        | "minecraft:peony"
        | "minecraft:rose_bush"
        | "minecraft:sunflower"
        | "minecraft:lily_of_the_valley"
        | "minecraft:dandelion"
        | "minecraft:poppy" => id::AIR,
        "minecraft:grass_block" => id::GRASS,
        "minecraft:dirt"
        | "minecraft:coarse_dirt"
        | "minecraft:rooted_dirt"
        | "minecraft:mud"
        | "minecraft:podzol" => id::DIRT,
        "minecraft:sand"
        | "minecraft:red_sand"
        | "minecraft:sandstone"
        | "minecraft:red_sandstone" => id::SAND,
        "minecraft:gravel" => id::GRAVEL,
        "minecraft:water" | "minecraft:lava" => id::WATER,
        "minecraft:bedrock" => id::BEDROCK,
        // Trees. `_log` / `_leaves` catches every wood type the vegetation
        // stage can place, not just the three seed 3 happens to grow, so
        // another biome does not silently reintroduce stone trees. Stripped
        // logs and wood blocks take the same side sprite.
        _ if is_log(base(name)) => id::LOG,
        _ if base(name).ends_with("_leaves") => id::LEAVES,
        // stone, deepslate, tuff, calcite, and any other solid: render as stone.
        _ => id::STONE,
    }
}

/// The topmost `y` in the rendered window whose **mapped** palette id satisfies
/// `keep`, or [`MIN_Y`] if none does.
///
/// Classifies through [`map_block`] rather than matching raw vanilla names a
/// second time, and that is the point: a height query that used its own name list
/// reports a `y` where the generated column has nothing. That is exactly what
/// happened when the feature stage landed — `surface_height` counted a
/// `minecraft:bush` as ground while [`generate_column`] wrote air there, so the
/// reported surface was a block above the real one at every column carrying a
/// plant. One classifier, one answer, no second list to drift.
fn top_mapped(wx: i32, wz: i32, keep: impl Fn(u32) -> bool) -> i32 {
    let cx = wx.div_euclid(16);
    let cz = wz.div_euclid(16);
    let lx = wx.rem_euclid(16) as usize;
    let lz = wz.rem_euclid(16) as usize;
    let col = generator().column(cx, cz);
    for y in (MIN_Y..TOP_Y).rev() {
        // The floor is forced to bedrock by `generate_column`, so it is solid
        // regardless of what the generator says there.
        let block = if y == MIN_Y {
            id::BEDROCK
        } else {
            map_block(col.block_state(lx, y, lz))
        };
        if keep(block) {
            return y;
        }
    }
    MIN_Y
}

/// Surface height (world-Y of the highest walkable, i.e. non-air/non-fluid,
/// block) at world column `(wx, wz)`, clamped to the rendered window.
///
/// **Includes tree canopy**, since leaves are walkable — this is vanilla's
/// `MOTION_BLOCKING` sense. For "where is the ground", which is what a spawn
/// point wants, use [`ground_height`].
#[must_use]
pub fn surface_height(wx: i32, wz: i32) -> i32 {
    top_mapped(wx, wz, |block| block != id::AIR && block != id::WATER)
}

/// World-Y of the highest **terrain** block at `(wx, wz)`: like
/// [`surface_height`], but ignoring anything the vegetation stage placed.
///
/// Vanilla's `MOTION_BLOCKING_NO_LEAVES` heightmap, and the one it uses to
/// choose a spawn position for exactly this reason. Once the feature stage was
/// chained in, seed 3's origin column acquired a birch canopy at y78–79 over
/// ground at y70, so [`spawn_feet`] — "just above the surface" — was putting the
/// player on top of a tree nine blocks in the air. Logs are excluded as well as
/// leaves: standing on a trunk is no more "the ground" than standing on the
/// canopy.
#[must_use]
pub fn ground_height(wx: i32, wz: i32) -> i32 {
    top_mapped(wx, wz, |block| {
        block != id::AIR && block != id::WATER && block != id::LOG && block != id::LEAVES
    })
}

/// Generate a single chunk column at chunk position `(cx, cz)` by windowing the
/// real generator's output into the shell's [`ChunkColumn`].
#[must_use]
pub fn generate_column(cx: i32, cz: i32) -> LoadedChunk {
    let col = generator().column(cx, cz);

    let mut column = ChunkColumn::new(
        MIN_Y,
        SECTION_COUNT,
        PaletteKind::block_states(),
        PaletteKind::biomes(),
        id::AIR,
        0,
    );

    for lx in 0..16usize {
        for lz in 0..16usize {
            for y in MIN_Y..TOP_Y {
                let block = if y == MIN_Y {
                    // Guaranteed sealed floor regardless of seed/column.
                    id::BEDROCK
                } else {
                    map_block(col.block_state(lx, y, lz))
                };
                if block != id::AIR {
                    column.set_block(lx, y, lz, block);
                }
            }
        }
    }

    // Compute real column light from the demo palette's opacity/emission so the
    // local world carries genuine sky-light gradients (caves and overhang cells
    // go dark; open sky stays 15). This is isolated per column — exact on open
    // terrain, and the honest, self-healing result at true chunk seams — and is
    // what makes the light-aware mesher non-vacuous. Feeding an all-`Missing`
    // `ColumnLight::new` here (the old behaviour) would leave every cell at the
    // dimension default and render flat full-bright, indistinguishable from the
    // retired `UniformLight` bridge.
    let light = compute_column_light(&column, &DemoLightProps);
    let heightmaps = Heightmaps::new();
    LoadedChunk::new(column, light, heightmaps, Vec::new())
}

/// Generate a square patch of chunks of radius `radius` (in chunks) centred on
/// chunk `(0,0)`, loaded into a fresh [`World`].
///
/// Real worldgen is ~100× the cost of the old sine stand-in (measured
/// ≈250 ms/chunk single-threaded in release), so a full `render_distance`
/// patch is generated in parallel across the machine's cores. This is a
/// coarse, per-chunk split over the *same* [`generate_column`] entry point —
/// the seam the integrated-server path will later replace — so nothing about
/// the generator or its determinism changes; only the batch driver fans out.
#[must_use]
pub fn generate(radius: i32) -> World {
    let coords: Vec<(i32, i32)> = (-radius..=radius)
        .flat_map(|cz| (-radius..=radius).map(move |cx| (cx, cz)))
        .collect();

    let workers = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(4)
        .clamp(1, coords.len().max(1));

    let batch = coords.len().div_ceil(workers);
    let mut world = World::new();

    std::thread::scope(|scope| {
        let handles: Vec<_> = coords
            .chunks(batch.max(1))
            .map(|slice| {
                scope.spawn(move || {
                    slice
                        .iter()
                        .map(|&(cx, cz)| (ChunkPos { x: cx, z: cz }, generate_column(cx, cz)))
                        .collect::<Vec<_>>()
                })
            })
            .collect();

        for handle in handles {
            for (pos, chunk) in handle.join().expect("worldgen worker panicked") {
                world.load(pos, chunk);
            }
        }
    });

    world
}

/// A comfortable spawn position (feet) just above the surface at the world
/// origin.
///
/// [`ground_height`], not [`surface_height`]: seed 3's origin column grows a
/// birch tree, and "just above the surface" through the canopy-inclusive height
/// put the player standing on leaves nine blocks off the ground. Vanilla picks a
/// spawn off `MOTION_BLOCKING_NO_LEAVES` for the same reason.
#[must_use]
pub fn spawn_feet() -> [f64; 3] {
    let ground = ground_height(0, 0);
    [0.5, (ground + 1) as f64, 0.5]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn surface_is_deterministic() {
        assert_eq!(surface_height(3, 7), surface_height(3, 7));
    }

    /// **The surface rule ran, and nothing solid sits above what it produced.**
    ///
    /// Asserted against [`ground_height`], not [`surface_height`]: the feature
    /// stage grows a birch tree on seed 3's origin column, so the canopy-inclusive
    /// height lands on a leaf block at y79 and "the origin surface is grass" fails
    /// with `left: 1` — `map_block`'s `_ => STONE` fallback, which was the real
    /// defect that failure was reporting.
    ///
    /// The expectation is vanilla's overworld surface rule, not a transcription of
    /// the measurement: on dry land above sea level it places `grass_block` with
    /// `dirt` beneath it, over the stone the density function produced. So this
    /// predicts the *stack* — grass, then dirt directly under it, then stone
    /// within the dirt rule's 1..=4 depth — rather than one block at one height,
    /// and a generator that stopped running surface rules would fail on the dirt
    /// or the stone even if it happened to leave grass on top.
    ///
    /// The last loop is what makes it a gate on the feature stage rather than on
    /// terrain alone: everything above the ground surface must be air or
    /// vegetation. A stray stone or dirt block up there means either the density
    /// function grew a detached overhang the ground-height scan walked past, or
    /// `map_block` sent a plant down the `_ => STONE` fallback again — the exact
    /// bug this test found.
    #[test]
    fn bedrock_floor_and_real_surface() {
        let chunk = generate_column(0, 0);
        let col = &chunk.column;
        assert_eq!(
            col.get_block(0, MIN_Y, 0),
            id::BEDROCK,
            "forced bedrock at the floor"
        );

        let ground = ground_height(0, 0);
        assert!(
            (SEA_LEVEL..TOP_Y).contains(&ground),
            "origin ground {ground} should be dry land in the window"
        );
        assert_eq!(
            col.get_block(0, ground, 0),
            id::GRASS,
            "the surface rule puts grass_block on dry land above sea level"
        );
        assert_eq!(
            col.get_block(0, ground - 1, 0),
            id::DIRT,
            "and dirt directly beneath it — grass with stone under it means the \
             surface rule's dirt band did not run"
        );
        let stone_within_rule_depth = (1..=4)
            .any(|depth| col.get_block(0, ground - depth, 0) == id::STONE);
        assert!(
            stone_within_rule_depth,
            "the dirt band is 1..=4 deep, so stone must appear within four \
             blocks of the surface"
        );

        for y in (ground + 1)..TOP_Y {
            let block = col.get_block(0, y, 0);
            assert!(
                block == id::AIR || block == id::LOG || block == id::LEAVES,
                "y={y} above the ground surface is id {block}: only air and \
                 vegetation may sit above the terrain the surface rule capped"
            );
        }
    }

    /// The origin column really does carry the tree that broke the test above —
    /// the premise the assertions there depend on, made explicit so it cannot
    /// quietly stop holding.
    ///
    /// Without this, `bedrock_floor_and_real_surface`'s vegetation loop is
    /// satisfied by a column of pure air above the grass, and
    /// `spawn_feet`'s reason for preferring `ground_height` would be untested.
    #[test]
    fn the_origin_column_carries_canopy_above_its_ground_surface() {
        let chunk = generate_column(0, 0);
        let col = &chunk.column;
        let ground = ground_height(0, 0);
        let surface = surface_height(0, 0);
        assert!(
            surface > ground,
            "premise: seed 3's origin grows a birch tree, so the walkable \
             surface ({surface}) must sit above the ground ({ground})"
        );
        assert_eq!(
            col.get_block(0, surface, 0),
            id::LEAVES,
            "and the block at the walkable surface is canopy, not the stone the \
             `_ =>` fallback used to make it"
        );
        assert_eq!(
            spawn_feet()[1],
            f64::from(ground + 1),
            "so spawn stands on the ground, not on the canopy"
        );
    }

    #[test]
    fn columns_are_not_all_air() {
        let chunk = generate_column(2, -3);
        let col = &chunk.column;
        let mut solids = 0;
        for y in MIN_Y..TOP_Y {
            if col.get_block(8, y, 8) != id::AIR {
                solids += 1;
            }
        }
        assert!(solids > 20, "expected a solid column, got {solids} solids");
    }

    #[test]
    fn water_appears_below_sea_level_somewhere() {
        // The generator's world has oceans; a small patch around origin should
        // contain some water (the fluid stage ran), even if the origin column is
        // dry. Scan a few chunks.
        let mut water = 0usize;
        for cz in -1..=1 {
            for cx in -1..=1 {
                let chunk = generate_column(cx, cz);
                let col = &chunk.column;
                for y in MIN_Y..=SEA_LEVEL {
                    for lz in 0..16usize {
                        for lx in 0..16usize {
                            if col.get_block(lx, y, lz) == id::WATER {
                                water += 1;
                            }
                        }
                    }
                }
            }
        }
        assert!(water > 0, "fluid stage produced no water in a 3x3 patch");
    }

    #[test]
    fn generate_loads_the_expected_chunk_count() {
        let world = generate(2);
        assert_eq!(world.len(), 25, "5x5 patch");
        assert!(crate::blocks::palette().len() >= 9);
    }
}
