//! Structure placement against a **vanilla-authored** save.
//!
//! The expected values come from `tests/support/structure_starts_survival.txt`,
//! scanned out of the per-chunk `structures.starts` NBT of the real 26.2 server's
//! survival world at `.cache/mc/survival` (seed −195764831). Nothing in that file
//! passed through this repo's encoder, and the world was generated by a different
//! implementation months before this engine existed — the two arms share nothing
//! but the seed.
//!
//! # What is gated, and what is deliberately not
//!
//! Six bundled structure sets are **closed** under the generators that exist
//! today: `shipwrecks`, `ocean_ruins`, `buried_treasures`, `ocean_monuments`,
//! `mineshafts` (S7) and — now — `ruined_portals`. Every structure they can
//! place has a decidable start (biome-valid implies start-valid for all six:
//! vanilla's own ruined-portal structure "find generation point", like the other five, always
//! returns `Optional.of(...)`), so for those the placement answer is exactly
//! vanilla's and both directions are checkable:
//!
//! * **Positive** — every one of the fixture's 86 closed-set starts is produced
//!   by this engine at exactly that chunk.
//! * **Negative** — over a 64×64 chunk window that the oracle world has generated
//!   essentially completely (4,080 of 4,096 chunks), this engine produces *no*
//!   closed-set start the oracle does not have. Without this half the positive
//!   test is satisfied by an engine that starts a shipwreck in every chunk.
//!
//! The remaining fixture starts (jigsaw structures) are **not** gated: their
//! sets are open — a structure whose piece generator has not landed cannot have
//! its start validity decided, so this engine's answer for those sets is a
//! superset by construction. `StructureRegistry::unsupported` names every one,
//! and this file asserts that ledger is non-empty rather than letting an
//! accidentally-empty implementation look complete.
//!
//! `ruined_portal_nether` shares its `type` id with the six overworld ids this
//! file gates, but the oracle census has no Nether chunks in scope here — its
//! own ledger row is asserted below alongside the others.

use std::collections::{BTreeSet, HashSet};
use std::path::{Path, PathBuf};

use lodestone_worldgen::density::{NoiseParams, Resolver};
use lodestone_worldgen::overworld::OverworldGenerator;
use serde_json::Value;

/// The oracle world's seed, read from its own `world_gen_settings.dat`.
const SEED: i64 = -195_764_831;

const FIXTURE: &str = include_str!("support/structure_starts_survival.txt");

/// The structure sets every structure of which this engine can decide.
///
/// `mineshafts` joined the list with S7. It is closed for the same reason the other
/// four are: vanilla's own mineshaft structure "find generation point" returns `Optional.of(...)`
/// unconditionally, so biome-valid implies start-valid and this engine's answer for
/// the set is exactly vanilla's — in **both** directions, which is what makes the
/// 46 oracle mineshaft starts a usable expected value rather than a superset.
const CLOSED_SET_STRUCTURES: &[&str] = &[
    "minecraft:shipwreck",
    "minecraft:shipwreck_beached",
    "minecraft:ocean_ruin_cold",
    "minecraft:ocean_ruin_warm",
    "minecraft:buried_treasure",
    "minecraft:monument",
    "minecraft:mineshaft",
    "minecraft:mineshaft_mesa",
    "minecraft:ruined_portal",
    "minecraft:ruined_portal_desert",
    "minecraft:ruined_portal_jungle",
    "minecraft:ruined_portal_mountain",
    "minecraft:ruined_portal_ocean",
    "minecraft:ruined_portal_swamp",
];

/// The negative sweep's window: `x in -32..32`, `z in -48..16`. Chosen because
/// the oracle world has generated 4,080 of its 4,096 chunks — measured, not
/// assumed, and the 16 absent ones are listed below so the sweep can skip them
/// rather than compare against a chunk vanilla never wrote.
const WINDOW: (i32, i32, i32, i32) = (-32, 32, -48, 16);

/// The 16 chunks inside [`WINDOW`] the oracle world has **not** generated.
const WINDOW_UNGENERATED: &[(i32, i32)] = &[
    (-32, 12), (-32, 13), (-32, 14), (-32, 15),
    (-31, 12), (-31, 13), (-31, 14), (-31, 15),
    (-30, 12), (-30, 13), (-30, 14), (-30, 15),
    (-29, 12), (-29, 13), (-29, 14), (-29, 15),
];

/// A [`Resolver`] over `crates/lodestone-server/assets/worldgen/` — the same
/// bundle the integrated server embeds. Reads the real biome-parameter table so
/// the biome predicates are the production ones; a single-biome fixture tree
/// would make every biome check trivially pass or trivially fail, which is the
/// "world" species of vacuous test.
struct ServerAssets {
    root: PathBuf,
}

impl ServerAssets {
    fn read(&self, kind: &str, id: &str) -> Value {
        let name = id.strip_prefix("minecraft:").unwrap_or(id);
        let path = self.root.join(kind).join(format!("{name}.json"));
        let text = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
        serde_json::from_str(&text).unwrap_or_else(|e| panic!("parsing {}: {e}", path.display()))
    }

    fn try_read(&self, kind: &str, id: &str) -> Value {
        let name = id.strip_prefix("minecraft:").unwrap_or(id);
        let path = self.root.join(kind).join(format!("{name}.json"));
        match std::fs::read_to_string(&path) {
            Ok(text) => serde_json::from_str(&text)
                .unwrap_or_else(|e| panic!("parsing {}: {e}", path.display())),
            Err(_) => Value::Null,
        }
    }
}

impl Resolver for ServerAssets {
    fn density_function(&self, id: &str) -> Value {
        self.read("density_function", id)
    }
    fn noise(&self, id: &str) -> NoiseParams {
        let v = self.read("noise", id);
        NoiseParams {
            first_octave: v["firstOctave"].as_i64().expect("firstOctave") as i32,
            amplitudes: v["amplitudes"]
                .as_array()
                .expect("amplitudes")
                .iter()
                .map(|a| a.as_f64().expect("amplitude"))
                .collect(),
        }
    }
    fn biome_parameters(&self) -> Value {
        self.read("biome_parameters", "overworld")
    }
    fn biome_temperatures(&self) -> Value {
        self.read("biome_parameters", "overworld_temperature")
    }
    fn structure_set_ids(&self) -> Vec<String> {
        let dir = self.root.join("structure_set");
        let mut ids: Vec<String> = std::fs::read_dir(&dir)
            .unwrap_or_else(|e| panic!("reading {}: {e}", dir.display()))
            .filter_map(|e| {
                let path = e.ok()?.path();
                let stem = path.file_stem()?.to_str()?;
                (path.extension()? == "json").then(|| format!("minecraft:{stem}"))
            })
            .collect();
        ids.sort();
        ids
    }
    fn structure_set(&self, id: &str) -> Value {
        self.try_read("structure_set", id)
    }
    fn structure(&self, id: &str) -> Value {
        self.try_read("structure", id)
    }
    fn biome_tag(&self, id: &str) -> Value {
        self.try_read("tags/worldgen/biome", id)
    }
    /// The NBT templates sit beside `worldgen/`, under `assets/structure/`
    ///. Without this every template-driven structure is demoted
    /// to unsupported — which is exactly what the ledger test below caught when
    /// this method was missing, so it is load-bearing for the *positive* half of
    /// that test, not just for placement.
    fn structure_template(&self, id: &str) -> Option<Vec<u8>> {
        let name = id.strip_prefix("minecraft:").unwrap_or(id);
        std::fs::read(self.root.join("../structure").join(format!("{name}.nbt"))).ok()
    }
}

fn generator() -> OverworldGenerator {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../lodestone-server/assets/worldgen");
    let resolver = ServerAssets { root: root.clone() };
    let settings: Value = serde_json::from_str(
        &std::fs::read_to_string(root.join("noise_settings/overworld.json")).unwrap(),
    )
    .unwrap();
    OverworldGenerator::new(SEED, &settings, &resolver, "minecraft:plains", false)
}

/// The fixture, as `(structure id, cx, cz)`.
fn oracle_starts() -> BTreeSet<(String, i32, i32)> {
    FIXTURE
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(|line| {
            let mut it = line.split_whitespace();
            let id = it.next().expect("id").to_string();
            let cx = it.next().expect("cx").parse().expect("cx");
            let cz = it.next().expect("cz").parse().expect("cz");
            (id, cx, cz)
        })
        .collect()
}

/// The ledger has to be non-empty and has to name the structures this file
/// deliberately does not gate. An empty ledger would mean either that everything
/// is implemented (it is not) or that unsupported types are being silently
/// dropped — and the second would make the negative sweep below pass vacuously
/// for the wrong reason.
#[test]
fn the_unsupported_ledger_names_what_is_not_implemented() {
    let generator = generator();
    let ledger = generator.structure_ledger();
    assert!(!ledger.is_empty(), "structure data loaded but nothing is named unsupported");
    for expected in [
        "minecraft:village_plains",
        "minecraft:trial_chambers",
    ] {
        assert!(
            ledger.contains_key(expected),
            "{expected} should be on the ledger; ledger = {ledger:#?}"
        );
    }
    // `CLOSED_SET_STRUCTURES` is a list of structures whose *placement* is closed,
    // which is not the same as having a piece generator. `monument` used to be a
    // deliberate exception here (placement/start complete, `OceanMonumentPieces`
    // not landed) — now that `structure::monument` exists, it follows the same
    // rule as every other closed-set structure.
    for implemented in CLOSED_SET_STRUCTURES {
        assert!(
            !ledger.contains_key(*implemented),
            "{implemented} has a generator but is on the unsupported ledger"
        );
    }
}

/// Every closed-set start vanilla persisted is produced by this engine at exactly
/// that chunk.
///
/// `#[ignore]`d: builds the real production generator and samples noise columns,
/// which is seconds rather than milliseconds.
#[test]
#[ignore = "reads the vanilla survival oracle world's start census; seconds, not milliseconds"]
fn closed_set_starts_match_the_vanilla_survival_world() {
    let generator = generator();
    let closed: HashSet<&str> = CLOSED_SET_STRUCTURES.iter().copied().collect();
    let expected: Vec<(String, i32, i32)> = oracle_starts()
        .into_iter()
        .filter(|(id, _, _)| closed.contains(id.as_str()))
        .collect();

    // World precondition, asserted rather than assumed: the fixture has to
    // actually contain the structures this test is about, or it measures nothing.
    assert_eq!(
        expected.len(),
        86,
        "the oracle census for the six closed sets is 86 starts (31 + mineshaft's 46 + \
         ruined_portal's 9: ruined_portal x4, ruined_portal_mountain x1, \
         ruined_portal_ocean x4); got {}",
        expected.len()
    );

    let mut missing = Vec::new();
    for (id, cx, cz) in &expected {
        let ours: Vec<String> = generator
            .structure_starts_including_incomplete(*cx, *cz)
            .iter()
            .map(|s| s.structure.clone())
            .collect();
        if !ours.iter().any(|s| s == id) {
            missing.push(format!("{id} at ({cx},{cz}) — we produced {ours:?}"));
        }
    }
    assert!(
        missing.is_empty(),
        "{}/{} vanilla closed-set starts not reproduced:\n{}",
        missing.len(),
        expected.len(),
        missing.join("\n")
    );
    println!("all {} vanilla closed-set starts reproduced", expected.len());
}

/// The other direction: over a window the oracle world has generated almost
/// completely, this engine invents no closed-set start vanilla does not have.
#[test]
#[ignore = "sweeps 4,080 chunks of the vanilla oracle window; tens of seconds"]
fn no_extra_closed_set_starts_over_the_oracle_window() {
    let generator = generator();
    let closed: HashSet<&str> = CLOSED_SET_STRUCTURES.iter().copied().collect();
    let oracle = oracle_starts();
    let ungenerated: HashSet<(i32, i32)> = WINDOW_UNGENERATED.iter().copied().collect();

    let (x0, x1, z0, z1) = WINDOW;
    let mut extra = Vec::new();
    let mut ours_in_window = 0usize;
    for cx in x0..x1 {
        for cz in z0..z1 {
            if ungenerated.contains(&(cx, cz)) {
                continue;
            }
            for start in generator.structure_starts_including_incomplete(cx, cz).iter() {
                if !closed.contains(start.structure.as_str()) {
                    continue;
                }
                ours_in_window += 1;
                if !oracle.contains(&(start.structure.clone(), cx, cz)) {
                    extra.push(format!("{} at ({cx},{cz})", start.structure));
                }
            }
        }
    }

    let expected_in_window = oracle
        .iter()
        .filter(|(id, cx, cz)| {
            closed.contains(id.as_str())
                && (x0..x1).contains(cx)
                && (z0..z1).contains(cz)
                && !ungenerated.contains(&(*cx, *cz))
        })
        .count();
    // Precondition again: a window with no closed-set start in it would make the
    // "no extras" assertion true for an engine that places nothing.
    // 12 before S7, mineshaft's 6, and ruined_portal's 4 inside the window
    // (`ruined_portal` at (7,-37), `ruined_portal_ocean` at (-17,13), (-16,-16)
    // and (2,6); the other 5 oracle ruined-portal starts sit outside `WINDOW`).
    assert_eq!(expected_in_window, 22, "window census changed");

    assert!(
        extra.is_empty(),
        "{} closed-set starts this engine invented and vanilla does not have:\n{}",
        extra.len(),
        extra.join("\n")
    );
    assert_eq!(
        ours_in_window, expected_in_window,
        "we produced {ours_in_window} closed-set starts in the window, vanilla has {expected_in_window}"
    );
}

/// A real chest, at the real seed, in both oracle `buried_treasure` chunks —
/// not just a start with an empty piece list.
///
/// The fixture only carries `(id, cx, cz)`, not per-block ground truth, so this
/// cannot check the chest's exact Y the way the start-position tests above do;
/// what it checks is that `structure_place_stage` actually reaches the
/// placement-time refinement end to end (surface, carve and structure
/// composed together for a real seed), landing the chest at the piece's own
/// fixed column (`chunkBlockX(9)`, `chunkBlockZ(9)`) and nowhere else in it.
#[test]
#[ignore = "runs the full pre-ore pipeline for two real chunks; not milliseconds"]
fn buried_treasure_chests_place_a_real_chest_in_both_oracle_chunks() {
    let generator = generator();
    for (cx, cz) in [(10, 33), (52, -10)] {
        let column = generator.column(cx, cz);
        let chest = "minecraft:chest[facing=north,type=single,waterlogged=false]";
        let mut found: Vec<i32> = Vec::new();
        for y in column.min_y()..(column.min_y() + column.height()) {
            if column.block_state(9, y, 9) == chest {
                found.push(y);
            }
        }
        assert_eq!(
            found.len(),
            1,
            "chunk ({cx},{cz}) has {} chests at its own column, expected exactly 1: {found:?}",
            found.len()
        );
        // Nowhere else in the 16x16 footprint carries one — the piece is a
        // single point, not a spread.
        let mut elsewhere = 0;
        for lx in 0..16usize {
            for lz in 0..16usize {
                if (lx, lz) == (9, 9) {
                    continue;
                }
                for y in column.min_y()..(column.min_y() + column.height()) {
                    if column.block_state(lx, y, lz) == chest {
                        elsewhere += 1;
                    }
                }
            }
        }
        assert_eq!(elsewhere, 0, "chunk ({cx},{cz}) has a chest outside its own column");
    }
}
