//! Cross-implementation decode validation against an external oracle.
//!
//! The lesson from plan §12.31 is that agreement between artefacts *you* wrote
//! is weak evidence: our physics oracle, golden vectors, and implementation all
//! encoded the same misunderstanding and agreed bit-for-bit while all being
//! wrong. So this test does not compare `decode_vorbis` against a golden that
//! this crate produced. It compares against a fixture whose two halves come
//! from *different third-party* codebases:
//!
//! * `chirp_stereo_44100.ogg` — a synthetic stereo log-sweep (L up, R down),
//!   generated by us but **encoded by libsndfile** (`soundfile`), an
//!   implementation with no shared lineage with lewton.
//! * `chirp_stereo_44100.f32le` — the golden PCM, produced by **decoding that
//!   ogg with ffmpeg's native Vorbis decoder**, again unrelated to lewton.
//!
//! So three independent Vorbis implementations touch this data: libsndfile
//! (encode), ffmpeg (decode → golden), lewton (decode → under test). The signal
//! is a self-generated chirp, so it carries no copyright, and it is a real
//! frequency sweep rather than a degenerate constant, so a wrong decoder cannot
//! pass by emitting silence.
//!
//! Measured live this session against real vanilla `.ogg` files from the asset
//! store (harp, levelup) the same lewton-vs-ffmpeg gap was `max_abs_diff` ≈
//! 3.1e-5, consistent with the ~1 LSB introduced by our `i16 -> f32` (`/32768`)
//! quantisation. We assert a generous `1e-3` tolerance here so the test is a
//! regression guard, not a re-derivation of that number.

use lodestone_audio::decode_vorbis;

const OGG: &[u8] = include_bytes!("fixtures/chirp_stereo_44100.ogg");
const GOLDEN_F32LE: &[u8] = include_bytes!("fixtures/chirp_stereo_44100.f32le");

/// Tolerance: comfortably above the ~3e-5 quantisation floor, far below any
/// real decode error. A transform or sample-order bug moves samples by O(0.1+).
const TOL: f32 = 1e-3;

fn golden() -> Vec<f32> {
    assert_eq!(GOLDEN_F32LE.len() % 4, 0, "golden not whole f32 samples");
    GOLDEN_F32LE
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
        .collect()
}

fn max_abs_diff(a: &[f32], b: &[f32]) -> f32 {
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0_f32, f32::max)
}

#[test]
fn decodes_native_layout() {
    let pcm = decode_vorbis(OGG).expect("decode ogg");
    assert_eq!(pcm.sample_rate(), 44100, "sample rate");
    assert_eq!(pcm.channels(), 2, "stereo preserved, not downmixed");
}

#[test]
fn is_not_silent() {
    // Guards against the degenerate-case trap: a decoder that returns all zeros
    // would match a silent golden perfectly. The chirp peaks near 0.5 by
    // construction (both channels 0.5 * sin(...)), so require a real peak.
    let pcm = decode_vorbis(OGG).expect("decode ogg");
    let peak = pcm.samples().iter().fold(0.0_f32, |m, &s| m.max(s.abs()));
    assert!(
        peak > 0.3,
        "decoded peak {peak} too low — silent/degenerate?"
    );
}

#[test]
fn matches_external_oracle() {
    let pcm = decode_vorbis(OGG).expect("decode ogg");
    let got = pcm.samples();
    let want = golden();

    // Vorbis decoders may differ by up to ~one block of trailing samples
    // depending on end-trim handling; compare the overlapping prefix and bound
    // the surplus so a grossly-wrong length still fails.
    let n = got.len().min(want.len());
    assert!(n > 40_000, "far too few overlapping samples: {n}");
    let surplus = got.len().abs_diff(want.len());
    assert!(surplus < 2048, "length surplus {surplus} exceeds one block");

    let diff = max_abs_diff(&got[..n], &want[..n]);
    assert!(diff < TOL, "max_abs_diff {diff} exceeds tol {TOL}");
}

#[test]
fn wrong_decode_must_fail_the_same_assertion() {
    // Teeth: prove the tolerance can actually reject a wrong result. If the
    // assertion in `matches_external_oracle` passed no matter what, it would be
    // worthless. We construct decodes that a *wrong* implementation could
    // plausibly produce and confirm each blows past TOL.
    let pcm = decode_vorbis(OGG).expect("decode ogg");
    let got = pcm.samples();
    let want = golden();
    let n = got.len().min(want.len());

    // (a) Sign flip — a decoder that inverts phase.
    let negated: Vec<f32> = want[..n].iter().map(|s| -s).collect();
    assert!(
        max_abs_diff(&got[..n], &negated) > TOL,
        "negated golden should NOT match — assertion has no teeth"
    );

    // (b) Channel swap — interleaving L/R the wrong way. The two channels are
    // distinct sweeps, so swapping them must diverge.
    let mut swapped = want[..n].to_vec();
    for f in swapped.chunks_exact_mut(2) {
        f.swap(0, 1);
    }
    assert!(
        max_abs_diff(&got[..n], &swapped) > TOL,
        "channel-swapped golden should NOT match"
    );

    // (c) One-frame time shift — an off-by-one in framing.
    let shifted = &want[2..n];
    let m = shifted.len();
    assert!(
        max_abs_diff(&got[..m], shifted) > TOL,
        "time-shifted golden should NOT match"
    );
}
