//! Item-id→name table for protocol 340: hermetic checks over the committed
//! table, plus an `#[ignore]`d drift guard that regenerates it from the
//! vendored `minecraft-data` project and asserts byte-for-byte equality.
//! Modelled directly on `lodestone-v1-8`'s `tests/item_types.rs` — same
//! source project, same generate/commit/drift-check shape, different only in
//! `source_path`: 1.12.2's own `dataPaths.json` entry redirects `items` at
//! `pc/1.12` (its own folder carries no `items.json`), so this generator
//! reads that folder rather than one matching the protocol number.
//!
//! Regenerate the committed table after a data bump with:
//!
//! ```text
//! LODESTONE_REGEN=1 cargo test -p lodestone-v1-9 --test item_types \
//!     committed_table_matches_source -- --ignored --nocapture
//! ```

use std::fmt::Write as _;
use std::path::PathBuf;

use lodestone_v1_9::item_types::{self, ITEM_TYPE_COUNT};

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn source_path() -> PathBuf {
    manifest_dir().join("../../../vendor/minecraft-data/data/pc/1.12/items.json")
}

fn committed_path() -> PathBuf {
    manifest_dir().join("src/generated/item_types.rs")
}

// ---------------------------------------------------------------------------
// Generator (shared by regen and the drift check)
// ---------------------------------------------------------------------------

/// Parses `items.json` into a sorted `(id, identifier)` table. Every entry's
/// `name` field is already a clean `snake_case` identifier (asserted below),
/// unlike `entities.json`'s CamelCase names.
fn parse_items(doc: &serde_json::Value) -> Vec<(i32, String)> {
    let entries = doc.as_array().expect("items.json is an array");
    let mut pairs: Vec<(i32, String)> = entries
        .iter()
        .map(|entry| {
            let id = entry
                .get("id")
                .and_then(serde_json::Value::as_i64)
                .expect("item entry has an integer id") as i32;
            let name = entry
                .get("name")
                .and_then(serde_json::Value::as_str)
                .expect("item entry has a name");
            assert!(
                name.chars()
                    .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_'),
                "item {id} name {name:?} is not already snake_case; the \
                 no-case-folding-judgement-call doc comment in \
                 src/item_types.rs is now wrong and needs revisiting"
            );
            (id, format!("minecraft:{name}"))
        })
        .collect();
    pairs.sort_by_key(|(id, _)| *id);
    for window in pairs.windows(2) {
        assert_ne!(
            window[0].0, window[1].0,
            "duplicate item id {} in items.json",
            window[0].0
        );
    }
    pairs
}

fn generate(doc: &serde_json::Value) -> String {
    let items = parse_items(doc);

    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo test -p lodestone-v1-9 --test item_types -- --ignored`\n\
         // from vendor/minecraft-data/data/pc/1.12/items.json (protocol 340 /\n\
         // Minecraft 1.12.2 -- 1.12.2's own dataPaths.json entry redirects `items` at\n\
         // pc/1.12, its own folder has no items.json). DO NOT EDIT BY HAND. Regenerate\n\
         // with LODESTONE_REGEN=1 (see the test module docs).\n",
    );
    out.push_str(
        "//! Generated item-id->name table for protocol 340 (Minecraft 1.12.2).\n//!\n",
    );
    out.push_str(
        "//! Maps 1.12.2's `Slot` numeric item id to its canonical family identifier\n\
         //! (metadata/damage is not resolved into a variant — see\n\
         //! `crate::item_types`'s module doc for why). Consumed by\n\
         //! [`crate::item_types`].\n\n",
    );

    let _ = writeln!(out, "/// Number of item type entries.");
    let _ = writeln!(out, "pub const ITEM_TYPE_COUNT: usize = {};\n", items.len());
    let _ = writeln!(
        out,
        "/// `(item id, canonical identifier)` pairs, sorted by id for binary search."
    );
    let _ = writeln!(
        out,
        "pub static ITEM_TYPES: [(i32, &str); {}] = [",
        items.len()
    );
    for (id, name) in &items {
        let _ = writeln!(out, "    ({id}, \"{name}\"),");
    }
    out.push_str("];\n");

    out
}

// ---------------------------------------------------------------------------
// Hermetic tests over the committed table (no source needed)
// ---------------------------------------------------------------------------

#[test]
fn table_is_non_empty_and_out_of_range_is_none() {
    assert!(item_types::item_name(1).is_some(), "table populated");
    assert_eq!(item_types::item_name(-1), None);
    assert_eq!(item_types::item_name(i16::MAX), None);
}

#[test]
fn known_ids_resolve_to_well_formed_identifiers() {
    assert_eq!(item_types::item_name(1), Some("minecraft:stone"));
    assert_eq!(item_types::item_name(35), Some("minecraft:wool"));
    assert_eq!(item_types::item_name(351), Some("minecraft:dye"));
    assert_eq!(item_types::item_name(256), Some("minecraft:iron_shovel"));
}

#[test]
fn identifiers_have_lowercase_paths() {
    for id in 0..2300i16 {
        let Some(name) = item_types::item_name(id) else {
            continue;
        };
        let path = name
            .strip_prefix("minecraft:")
            .expect("namespaced identifier");
        assert!(!path.is_empty(), "id {id} has an empty path");
        assert!(
            path.chars()
                .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_'),
            "id {id} identifier {name:?} has an invalid path character"
        );
        let _key: lodestone_model::ResourceKey = name.parse().expect("valid resource key");
    }
}

// ---------------------------------------------------------------------------
// Drift guard (needs the vendored source; #[ignore]d so the suite stays hermetic)
// ---------------------------------------------------------------------------

#[test]
#[ignore = "reads the gitignored vendor/minecraft-data; run explicitly to regen/verify"]
fn committed_table_matches_source() {
    let raw = std::fs::read_to_string(source_path())
        .expect("items.json present under vendor/minecraft-data/data/pc/1.12");
    let doc: serde_json::Value = serde_json::from_str(&raw).expect("items.json parses");
    let generated = generate(&doc);

    if std::env::var_os("LODESTONE_REGEN").is_some() {
        std::fs::write(committed_path(), &generated).expect("write committed table");
        eprintln!("regenerated {}", committed_path().display());
        return;
    }

    let committed = std::fs::read_to_string(committed_path()).expect("committed table present");
    assert_eq!(
        generated, committed,
        "src/generated/item_types.rs is stale vs items.json; regenerate with LODESTONE_REGEN=1"
    );

    let items = parse_items(&doc);
    assert_eq!(items.len(), ITEM_TYPE_COUNT, "item count mismatch");
    let mut mismatches = 0usize;
    for (id, name) in &items {
        if item_types::item_name(*id as i16) != Some(name.as_str()) {
            mismatches += 1;
        }
    }
    println!("=== ITEM-TYPE TABLE REPORT (protocol 340) ===");
    println!("item types : {ITEM_TYPE_COUNT}");
    println!("mismatches : {mismatches}");
    println!("=============================================");
    assert_eq!(mismatches, 0, "committed table disagrees with items.json");
}
