//! Gates for the generated [`BuiltinBiome`] enum.
//!
//! The source is the checked-in worldgen asset registry, not a hand-maintained
//! Rust list. The ignored regeneration gate re-lists the asset directory and
//! rewrites `src/generated/biome_enum.rs`; the ordinary tests then compare the
//! compiled enum against that same external source independently.

use std::fmt::Write as _;
use std::path::PathBuf;

use lodestone_data::biomes::{BiomeRef, BuiltinBiome, ExtensionId};

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn source_dir() -> PathBuf {
    manifest_dir().join("../lodestone-server/assets/worldgen/biome")
}

fn committed_path() -> PathBuf {
    manifest_dir().join("src/generated/biome_enum.rs")
}

fn source_names() -> Vec<String> {
    let directory = source_dir();
    assert!(
        directory.is_dir(),
        "authoritative biome asset directory is missing: {}",
        directory.display()
    );
    let mut names: Vec<String> = std::fs::read_dir(&directory)
        .expect("read authoritative biome asset directory")
        .map(|entry| entry.expect("read biome asset entry").path())
        .filter(|path| path.extension().and_then(|extension| extension.to_str()) == Some("json"))
        .map(|path| {
            path.file_stem()
                .and_then(|stem| stem.to_str())
                .expect("biome asset filename is UTF-8")
                .to_owned()
        })
        .collect();
    names.sort_unstable();
    names
}

fn variant_name(path: &str) -> String {
    let mut out = String::with_capacity(path.len());
    for word in path.split('_') {
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            out.extend(first.to_uppercase());
            out.push_str(chars.as_str());
        }
    }
    out
}

fn generate(names: &[String]) -> String {
    assert!(!names.is_empty(), "biome asset census must not be empty");
    let variants: Vec<(usize, String)> = names
        .iter()
        .enumerate()
        .map(|(index, path)| {
            assert!(
                path.bytes()
                    .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_'),
                "biome path {path:?} is not safe for a generated Rust enum"
            );
            let variant = variant_name(path);
            assert_ne!(variant, "Self", "biome path {path:?} becomes reserved `Self`");
            (index, variant)
        })
        .collect();

    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo test -p lodestone-data --test biome_enum -- --ignored`\n\
// from crates/lodestone-server/assets/worldgen/biome/*.json, the checked-in\n\
// authoritative 26.2 worldgen registry data. DO NOT EDIT BY HAND. Regenerate\n\
// with LODESTONE_REGEN=1 (see the test module docs).\n\
//! The generated built-in worldgen-biome names for Minecraft 26.2.\n\
//!\n\
//! This is deliberately a compact enum rather than a table of owned strings:\n\
//! the discriminant is the canonical built-in-biome identity used by the\n\
//! version-free worldgen pipeline. Names are retained once in rodata for the\n\
//! display/serialization boundary.\n\n",
    );
    out.push_str(
        "/// A built-in `minecraft:worldgen/biome` entry.\n\
///\n\
/// Ordering is stable alphabetical path order. It is an internal canonical\n\
/// order, not the holder order a particular protocol sends during login.\n\
/// Dynamically supplied entries live one level out in [`crate::biomes::BiomeRef`].\n\
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\n\
#[repr(u8)]\n\
pub enum BuiltinBiome {\n",
    );
    for (index, variant) in &variants {
        let path = &names[*index];
        let _ = writeln!(out, "    /// `minecraft:{path}`\n    {variant} = {index},");
    }
    out.push_str("}\n\npub static BUILTINS: [BuiltinBiome; ");
    let _ = writeln!(out, "{}] = [", variants.len());
    for chunk in variants.chunks(8) {
        out.push_str("    ");
        for (position, (_, variant)) in chunk.iter().enumerate() {
            if position != 0 {
                out.push_str(", ");
            }
            let _ = write!(out, "BuiltinBiome::{variant}");
        }
        out.push_str(",\n");
    }
    out.push_str("];\n\npub static BIOME_NAMES: [&str; ");
    let _ = writeln!(out, "{}] = [", names.len());
    for chunk in names.chunks(8) {
        out.push_str("    ");
        for (position, path) in chunk.iter().enumerate() {
            if position != 0 {
                out.push_str(", ");
            }
            let _ = write!(out, "\"{path}\"");
        }
        out.push_str(",\n");
    }
    out.push_str("];\n\nimpl BuiltinBiome {\n    /// The canonical namespaced name for this generated entry.\n    #[must_use]\n    pub const fn name(self) -> &'static str {\n        BIOME_QUALIFIED_NAMES[self as usize]\n    }\n}\n\npub static BIOME_QUALIFIED_NAMES: [&str; ");
    let _ = writeln!(out, "{}] = [", names.len());
    for chunk in names.chunks(8) {
        out.push_str("    ");
        for (position, path) in chunk.iter().enumerate() {
            if position != 0 {
                out.push_str(", ");
            }
            let _ = write!(out, "concat!(\"minecraft:\", \"{path}\")");
        }
        out.push_str(",\n");
    }
    out.push_str("];\n");
    out
}

#[test]
fn compiled_enum_matches_authoritative_asset_census() {
    let names = source_names();
    let compiled: Vec<&'static str> = BuiltinBiome::all().map(BuiltinBiome::path).collect();
    assert_eq!(compiled, names.iter().map(String::as_str).collect::<Vec<_>>());
    assert_eq!(BuiltinBiome::COUNT as usize, names.len());
    for (index, path) in names.iter().enumerate() {
        let qualified = format!("minecraft:{path}");
        let biome = BuiltinBiome::from_name(&qualified).expect("asset biome parses");
        assert_eq!(biome as usize, index);
        assert_eq!(biome.name(), qualified);
    }
}

#[test]
fn biome_ref_is_a_compact_identity_with_an_explicit_extension_arm() {
    assert_eq!(std::mem::size_of::<BuiltinBiome>(), 1);
    assert_eq!(std::mem::size_of::<BiomeRef>(), 4);
    let builtin = BiomeRef::builtin(BuiltinBiome::Plains);
    assert_eq!(builtin.builtin_or_none(), Some(BuiltinBiome::Plains));
    let extension = BiomeRef::extension(ExtensionId::from_index(7));
    assert_eq!(extension.builtin_or_none(), None);
    assert_eq!(ExtensionId::from_index(7).index(), 7);
}

#[test]
fn canonical_identity_is_not_presented_as_a_wire_registry_ordinal() {
    assert_eq!(BuiltinBiome::from_canonical_id(BuiltinBiome::Plains as u32), Some(BuiltinBiome::Plains));
    assert_eq!(BuiltinBiome::from_canonical_id(u32::MAX), None);
}

#[test]
fn strict_builtin_parse_rejects_unknown_and_foreign_names() {
    assert_eq!(BuiltinBiome::parse("minecraft:plains"), Ok(BuiltinBiome::Plains));
    assert!(BuiltinBiome::parse("minecraft:not_a_biome").is_err());
    assert!(BuiltinBiome::parse("modded:plains").is_err());
}

#[test]
#[ignore = "regenerates/verifies the committed enum; run explicitly"]
fn committed_enum_matches_authoritative_assets() {
    let generated = generate(&source_names());
    if std::env::var_os("LODESTONE_REGEN").is_some() {
        std::fs::write(committed_path(), &generated).expect("write generated biome enum");
        eprintln!("regenerated {}", committed_path().display());
        return;
    }
    let committed = std::fs::read_to_string(committed_path()).expect("generated biome enum exists");
    assert_eq!(generated, committed, "generated biome enum is stale; regenerate with LODESTONE_REGEN=1");
}
