//! Item → placed-block table: hermetic checks over the committed table, plus
//! an `#[ignore]`d drift guard that regenerates it from the committed JVM dump
//! and asserts byte-for-byte equality (modelled on `hardness.rs` and
//! `item_prototypes.rs`). The generator lives here so the checked-in table can
//! never silently drift from the game data.
//!
//! # Data provenance
//!
//! `tests/support/block_items_jvm.txt` is an authoritative dump produced by
//! booting the real 26.2 server and walking vanilla's own item registry, asking
//! every item that is a block item for its own "get block" accessor — `oracle-java/BlockItemOracle.java`.
//!
//! Neither `registries.json` nor `blocks.json` can answer this: the first is a
//! flat list of item *names* with no item→block relation at all, the second is
//! block properties with no item side. The relation exists only as a field on
//! the `BlockItem` instance, constructed at bootstrap. So, as with collision
//! shapes and hardness, "boot the jar and ask it" is the only authoritative
//! source, and the dump is committed as the external anchor (§ "an expected
//! value must originate outside the code under test").
//!
//! # Refreshing after a version bump
//!
//! 1. Re-dump from the server. Any JDK ≥ 21 with the server jar and its
//!    libraries on the classpath will do — a local JDK:
//!
//! ```text
//! MC="$(cd .cache/mc/26.2 && pwd)"
//! CP="$MC/versions/26.2/server-26.2.jar:$(find "$MC/libraries" -name '*.jar' | tr '\n' ':')"
//! javac -cp "$CP" -d /tmp/oracle crates/lodestone-data/oracle-java/BlockItemOracle.java
//! java -cp "/tmp/oracle:$CP" BlockItemOracle
//! ```
//!
//!    or the temurin Docker classpath the neighbouring oracles document, if no
//!    JDK is installed. Copy its stdout over `tests/support/block_items_jvm.txt`,
//!    keeping the `#` header.
//!
//! 2. Regenerate the committed table:
//!
//! ```text
//! LODESTONE_REGEN=1 cargo test -p lodestone-data --test block_items \
//!     committed_table_matches_the_committed_dump -- --ignored --nocapture
//! ```

use std::fmt::Write as _;
use std::path::PathBuf;

use lodestone_data::block::Block;
use lodestone_data::block_items;

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn committed_path() -> PathBuf {
    manifest_dir().join("src/generated/block_items.rs")
}

/// The committed JVM dump — an external anchor, not gitignored.
const DUMP: &str = include_str!("support/block_items_jvm.txt");

/// One authoritative row: item registry id, item name, and the block it places
/// (`None` for an item that is not a `BlockItem`).
struct Row {
    id: usize,
    item: String,
    block: Option<String>,
}

fn parse_dump(text: &str) -> Vec<Row> {
    let mut rows = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut tok = line.split_whitespace();
        let id: usize = tok.next().expect("id column").parse().expect("id is a usize");
        let item = tok.next().expect("item column").to_owned();
        let block_raw = tok.next().expect("block column");
        assert!(tok.next().is_none(), "unexpected trailing tokens on {line:?}");
        let block = (block_raw != "-").then(|| block_raw.to_owned());
        if let Some(name) = &block {
            assert!(
                name.starts_with("minecraft:"),
                "block column must be a namespaced id or '-', got {name:?}"
            );
        }
        assert!(
            item.starts_with("minecraft:"),
            "item column must be a namespaced id, got {item:?}"
        );
        rows.push(Row { id, item, block });
    }
    rows.sort_by_key(|row| row.id);
    for (index, row) in rows.iter().enumerate() {
        assert_eq!(row.id, index, "dump ids are not a dense 0..N (gap at {index})");
    }
    rows
}

/// Renders the committed `block_items.rs` source from the parsed dump.
fn generate(rows: &[Row]) -> String {
    let count = rows.len();
    let placeable = rows.iter().filter(|row| row.block.is_some()).count();

    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo test -p lodestone-data --test block_items -- --ignored`\n\
         // from tests/support/block_items_jvm.txt (a headless 26.2 server dump of the\n\
         // item registry joined with each block item's own placed-block accessor,\n\
         // protocol 776 / Minecraft 26.2). DO NOT EDIT BY HAND. Regenerate with\n\
         // LODESTONE_REGEN=1 (see the test module docs).\n",
    );
    out.push_str(
        "//! Generated item -> placed-block table for protocol 776 (Minecraft 26.2),\n\
         //! indexed by item network registry id. Consumed by [`crate::block_items`].\n\
         //!\n\
         //! The column holds [`crate::block::Block`] rather than the block's name. Both\n\
         //! spellings are the same fact, but a `&'static str` column costs a pointer and\n\
         //! a length per row plus a relocation each, where the enum costs one `u16` and\n\
         //! resolves to the single copy of the name already in\n\
         //! `BLOCK_REGISTRY_NAMES` — and it cannot hold a string that is not a block.\n\n\
         use crate::block::Block;\n\n",
    );

    let _ = writeln!(out, "/// Number of item entries (ids are `0..ITEM_COUNT`).");
    let _ = writeln!(out, "pub const ITEM_COUNT: u32 = {count};\n");

    let _ = writeln!(
        out,
        "/// The block each item places, indexed by item network registry id; `None`\n\
         /// for the {} of {count} items that are not `BlockItem`s and place nothing.",
        count - placeable
    );
    let _ = writeln!(
        out,
        "pub static BLOCK_FOR_ITEM: [Option<Block>; {count}] = ["
    );
    for row in rows {
        match &row.block {
            Some(block) => {
                // Resolving through `Block::from_name` rather than emitting the
                // camel-cased path directly is deliberate: a name the block
                // registry does not contain fails generation here, naming the
                // item, instead of emitting a variant that does not exist and
                // reporting it as a compile error in a generated file.
                let variant = Block::from_name(block).unwrap_or_else(|| {
                    panic!("item {} places {block}, which is not a built-in block", row.item)
                });
                let _ = writeln!(
                    out,
                    "    Some(Block::{variant:?}), // {} {}",
                    row.id, row.item
                );
            }
            None => {
                let _ = writeln!(out, "    None, // {} {}", row.id, row.item);
            }
        }
    }
    out.push_str("];\n");

    out
}

// ---------------------------------------------------------------------------
// Hermetic tests over the committed table (anchored to the committed dump)
// ---------------------------------------------------------------------------

#[test]
fn committed_table_matches_the_committed_dump_row_for_row() {
    // The strongest check: every entry in the shipped accessor equals what the
    // real server said. Non-vacuous by construction -- it iterates all 1,537
    // items and compares exact strings, so a single transposed row fails.
    let rows = parse_dump(DUMP);
    assert_eq!(
        rows.len(),
        block_items::ITEM_COUNT as usize,
        "dump/table item count mismatch"
    );
    let mut checked_some = 0usize;
    let mut checked_none = 0usize;
    for row in &rows {
        let id = i32::try_from(row.id).expect("item id fits i32");
        // Compared as *names*, so the expected value stays the dump's own
        // string rather than a `Block` this crate produced — the table is typed
        // now, but the anchor must still come from outside it.
        let actual = block_items::block_for_item_id(id).map(Block::name);
        assert_eq!(
            actual,
            row.block.as_deref(),
            "item {} ({}) places the wrong block",
            row.id,
            row.item
        );
        // The name-keyed accessor must agree with the id-keyed one for every
        // item -- otherwise `items::item_id`'s reverse scan has drifted.
        assert_eq!(
            block_items::block_for_item(&row.item),
            row.block.as_deref(),
            "name and id lookups disagree for {}",
            row.item
        );
        if row.block.is_some() {
            checked_some += 1;
        } else {
            checked_none += 1;
        }
    }
    // Both arms must be non-trivially populated, or this test could pass while
    // measuring only one of them.
    assert_eq!(checked_some, 1054, "placeable-item count changed");
    assert_eq!(checked_none, 483, "non-placeable-item count changed");
}

/// Every block this table names must actually exist in the block registry.
/// A typo or a stale block rename would otherwise ship a `set_block` call for
/// a block nothing can resolve.
///
/// # What the `Block` column already guarantees, and what is left for this test
///
/// Half of this assertion is now true by construction: the column is
/// [`Block`]-typed, so it cannot hold a name the *registry* lacks — a bad name
/// fails generation instead. What remains is a genuine cross-table join, and it
/// is the half that was always the real risk: the registry is registration-
/// ordered and the block-*state* table is name-sorted, two independently
/// generated censuses, and this asserts every placeable block appears in both.
#[test]
fn every_placed_block_is_a_real_registered_block() {
    let mut checked = 0usize;
    for id in 0..block_items::ITEM_COUNT {
        let Some(block) = block_items::block_for_item_id(id as i32) else {
            continue;
        };
        let found = (0..lodestone_data::block_states::STATE_COUNT)
            .any(|state| lodestone_data::block_states::block_name(state) == Some(block.name()));
        assert!(found, "item id {id} places {block:?}, which is not a registered block");
        checked += 1;
    }
    assert_eq!(checked, 1054, "expected every placeable item to be checked");
}

/// The exact rows that separate this census from a name match. If someone ever
/// "simplifies" the table into `item_name == block_name`, these fail.
///
/// Both directions are represented: an item whose block has a different name,
/// and an item that places nothing *despite* a block of its name existing.
#[test]
fn the_census_disagrees_with_a_name_match_exactly_where_the_game_does() {
    // False negatives of a name match: real placeable items it would decline.
    for (item, block) in [
        ("minecraft:redstone", "minecraft:redstone_wire"),
        ("minecraft:string", "minecraft:tripwire"),
        ("minecraft:wheat_seeds", "minecraft:wheat"),
        ("minecraft:cocoa_beans", "minecraft:cocoa"),
        ("minecraft:carrot", "minecraft:carrots"),
        ("minecraft:potato", "minecraft:potatoes"),
        ("minecraft:pumpkin_seeds", "minecraft:pumpkin_stem"),
        ("minecraft:melon_seeds", "minecraft:melon_stem"),
    ] {
        assert_eq!(
            block_items::block_for_item(item),
            Some(block),
            "{item} must place {block}"
        );
    }

    // False positives of a name match: a block of this name exists, but the
    // item is not a `BlockItem` and places nothing.
    for item in ["minecraft:wheat", "minecraft:air"] {
        let block_of_that_name = (0..lodestone_data::block_states::STATE_COUNT)
            .any(|state| lodestone_data::block_states::block_name(state) == Some(item));
        assert!(
            block_of_that_name,
            "{item} must still name a real block, or this test proves nothing"
        );
        assert_eq!(
            block_items::block_for_item(item),
            None,
            "{item} names a block but is not a BlockItem, so it must place nothing"
        );
    }
}

/// The ordinary name-match cases, plus the non-placeable direction.
#[test]
fn plain_blocks_resolve_to_themselves_and_tools_resolve_to_nothing() {
    for item in [
        "minecraft:dirt",
        "minecraft:oak_planks",
        "minecraft:white_wool",
        "minecraft:glass",
        "minecraft:cobblestone",
        "minecraft:sand",
        "minecraft:oak_log",
    ] {
        assert_eq!(block_items::block_for_item(item), Some(item), "{item} places itself");
    }

    for item in [
        "minecraft:diamond_sword",
        "minecraft:water_bucket",
        "minecraft:stick",
        "minecraft:bread",
        "minecraft:zombie_spawn_egg",
        "minecraft:flint_and_steel",
    ] {
        assert_eq!(
            block_items::block_for_item(item),
            None,
            "{item} is not a BlockItem and must place nothing"
        );
    }

    // An item this version does not know is a miss, not a panic.
    assert_eq!(block_items::block_for_item("minecraft:not_a_real_item"), None);
    assert_eq!(block_items::block_for_item_id(-1), None);
    assert_eq!(
        block_items::block_for_item_id(block_items::ITEM_COUNT as i32),
        None
    );
}

/// [`block_items::item_for_block`], the inverse this issue's server-side half
/// needs: pairwise-distinct blocks so a transposition in the `OnceLock`
/// build (`table[placed as usize] = ...`) cannot survive, plus the two `None`
/// shapes — a block with no `BlockItem` at all, and an out-of-range `Block`
/// cannot occur since `Block` is exhaustive, so only the first shape is real.
#[test]
fn item_for_block_inverts_block_for_item_id_for_ordinary_blocks() {
    for (item, block_name) in [
        ("minecraft:dirt", "minecraft:dirt"),
        ("minecraft:oak_planks", "minecraft:oak_planks"),
        ("minecraft:diamond_block", "minecraft:diamond_block"),
        ("minecraft:glass", "minecraft:glass"),
    ] {
        let block = Block::from_name(block_name).unwrap_or_else(|| panic!("{block_name} must be a real block"));
        assert_eq!(
            block_items::item_for_block(block).map(lodestone_data::item::Item::name),
            Some(item),
            "item_for_block({block_name}) must invert block_for_item({item})"
        );
    }
}

/// A block no `BlockItem` targets at all — fluids and technical blocks a
/// player can never hold as an item — must report `None` rather than a
/// fabricated item. (`minecraft:redstone_wire` is *not* such a block: the
/// census's own false-negative example, `minecraft:redstone` places it, so
/// `item_for_block` correctly answers `Some(Redstone)` there — this test
/// picks blocks with no `BlockItem` pointing at them by any name.)
#[test]
fn item_for_block_is_none_for_a_block_with_no_block_item() {
    for name in ["minecraft:water", "minecraft:fire", "minecraft:air", "minecraft:nether_portal"] {
        let block = Block::from_name(name).unwrap_or_else(|| panic!("{name} is a real block"));
        assert_eq!(block_items::item_for_block(block), None, "{name} must have no BlockItem");
    }
}

/// Every block this crate's `item_for_block` names must round-trip back
/// through [`block_items::block_for_item_id`] — the property that makes it a
/// true inverse rather than an independently-wrong second table.
#[test]
fn item_for_block_round_trips_through_block_for_item_id_for_every_block() {
    let mut checked = 0usize;
    for block in Block::all() {
        let Some(item) = block_items::item_for_block(block) else {
            continue;
        };
        let item_id = i32::from(item.registry_id());
        assert_eq!(
            block_items::block_for_item_id(item_id),
            Some(block),
            "{item:?} must place {block:?} back"
        );
        checked += 1;
    }
    assert!(checked > 1000, "expected most of the 1,054 placeable blocks to round-trip, got {checked}");
}

/// The block-entity blocks `lodestone-server` models must still resolve, since
/// its placement path composes this table with `block_entity_for_item`.
#[test]
fn the_block_entity_blocks_still_resolve_to_themselves() {
    for item in [
        "minecraft:furnace",
        "minecraft:smoker",
        "minecraft:blast_furnace",
        "minecraft:composter",
        "minecraft:hopper",
        "minecraft:brewing_stand",
        "minecraft:chest",
    ] {
        assert_eq!(block_items::block_for_item(item), Some(item));
    }
}

// ---------------------------------------------------------------------------
// Drift guard / generator
// ---------------------------------------------------------------------------

/// Regenerates the committed table from the committed dump and asserts it is
/// byte-identical. `#[ignore]`d because it touches the filesystem under
/// `LODESTONE_REGEN=1`.
#[test]
#[ignore = "regenerates/asserts the committed table; run explicitly"]
fn committed_table_matches_the_committed_dump() {
    let rows = parse_dump(DUMP);
    let rendered = generate(&rows);
    let path = committed_path();

    if std::env::var_os("LODESTONE_REGEN").is_some() {
        std::fs::write(&path, &rendered).expect("write generated table");
        println!("regenerated {} ({} rows)", path.display(), rows.len());
        return;
    }

    let committed = std::fs::read_to_string(&path).expect("read committed table");
    assert_eq!(
        committed, rendered,
        "committed src/generated/block_items.rs has drifted from tests/support/block_items_jvm.txt; \
         regenerate with LODESTONE_REGEN=1"
    );
}
