//! Enchantment census: the generator, its drift guard, and hermetic controls.
//!
//! `minecraft:enchantment` is data-driven, so it is absent from `registries.json`;
//! the census (path and level range per enchantment) comes from the release's own
//! datapack files, `data/minecraft/enchantment/*.json`, unpacked from the server jar
//! under the current release's cache directory (`src/data/...`, gitignored).
//! Only the file set and each file's top-level `max_level` are read, which is why
//! the census survives a release that rewrites the effect bodies.
//!
//! Regenerate the committed table after a release bump with:
//!
//! ```text
//! LODESTONE_REGEN=1 cargo test -p lodestone-data --test enchantments \
//!     committed_table_matches_datapack -- --ignored --nocapture
//! ```

use std::fmt::Write as _;
use std::path::PathBuf;

use lodestone_data::enchantment::{ENCHANTMENT_COUNT, ENCHANTMENTS};

fn committed_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src/generated/enchantments.rs")
}

fn datapack_dir() -> PathBuf {
    lodestone_mc_cache::cache_root()
        .expect("current-release cache directory is present")
        .join("src/data/minecraft/enchantment")
}

/// `(path, max_level)` for every enchantment file, sorted by path.
fn read_census(dir: &std::path::Path) -> Vec<(String, u8)> {
    let mut rows: Vec<(String, u8)> = std::fs::read_dir(dir)
        .unwrap_or_else(|err| panic!("read {}: {err}", dir.display()))
        .map(|entry| entry.expect("directory entry").path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "json"))
        .map(|path| {
            let stem = path.file_stem().expect("file stem").to_string_lossy().into_owned();
            let doc: serde_json::Value = serde_json::from_str(
                &std::fs::read_to_string(&path).expect("read enchantment file"),
            )
            .unwrap_or_else(|err| panic!("{} is not JSON: {err}", path.display()));
            let max = doc
                .get("max_level")
                .and_then(serde_json::Value::as_u64)
                .unwrap_or_else(|| panic!("{} has no max_level", path.display()));
            (stem, u8::try_from(max).expect("max_level fits u8"))
        })
        .collect();
    rows.sort();
    rows
}

fn generate(rows: &[(String, u8)]) -> String {
    let version = lodestone_mc_cache::current_version();
    let count = rows.len();
    let mut out = String::new();
    let _ = write!(
        out,
        "// @generated by `cargo test -p lodestone-data --test enchantments -- --ignored` from\n\
         // the release's `data/minecraft/enchantment/*.json` ({count} files, Minecraft {version}).\n\
         // DO NOT EDIT. Regenerate with LODESTONE_REGEN=1 (see the test module docs).\n\
         //\n\
         // Absent from registries.json entirely: minecraft:enchantment is data-driven, so its\n\
         // network id is assigned per-connection by configuration-phase registry sync order,\n\
         // not a fixed protocol id — see `ItemEnchantment::id`'s own doc in `lodestone-model`.\n\
         // This table exists only for a **session-independent** enchantment census (name, min\n\
         // level, max level), never for a network id.\n\
         //! Generated enchantment census (Minecraft {version}; the 26.2 set and level ranges are\n\
         //! identical, so protocol 776 reads it too).\n\
         //!\n\
         //! Ordered alphabetically by registry path, matching the order the datapack loader\n\
         //! scans resources in (a sorted map from resource location to resource), which is\n\
         //! what feeds the creative-tab generation of max-level-only enchanted books. Each\n\
         //! entry is one `data/minecraft/enchantment/*.json` file's own `max_level` field.\n\
         \n\
         /// Number of enchantment entries.\n\
         pub const ENCHANTMENT_COUNT: u32 = {count};\n\
         \n\
         /// One enchantment: its registry path (no `minecraft:` prefix — these are always\n\
         /// namespaced `minecraft:`), min level, and max level.\n\
         #[derive(Debug)]\n\
         pub struct EnchantmentCensus {{\n\
         \x20   /// Registry path, e.g. `\"sharpness\"`.\n\
         \x20   pub path: &'static str,\n\
         \x20   /// A hardcoded `1` for every enchantment, **not** a JSON field (no enchantment\n\
         \x20   /// definition carries a `min_level` key).\n\
         \x20   pub min_level: u8,\n\
         \x20   /// `max_level` from the enchantment's own JSON.\n\
         \x20   pub max_level: u8,\n\
         }}\n\
         \n\
         /// Every enchantment, alphabetical by path (see module doc for why that is the\n\
         /// creative-menu order).\n\
         pub static ENCHANTMENTS: [EnchantmentCensus; ENCHANTMENT_COUNT as usize] = [\n"
    );
    for (path, max) in rows {
        let _ = writeln!(
            out,
            "    EnchantmentCensus {{ path: {path:?}, min_level: 1, max_level: {max} }},"
        );
    }
    out.push_str("];\n");
    out
}

#[test]
fn committed_census_is_sorted_and_counted() {
    assert_eq!(ENCHANTMENTS.len(), ENCHANTMENT_COUNT as usize);
    let paths: Vec<&str> = ENCHANTMENTS.iter().map(|e| e.path).collect();
    let mut sorted = paths.clone();
    sorted.sort_unstable();
    assert_eq!(paths, sorted, "the census is alphabetical by path");
    // Literal controls: independent of the generator.
    let sharpness = ENCHANTMENTS.iter().find(|e| e.path == "sharpness").expect("sharpness");
    assert_eq!((sharpness.min_level, sharpness.max_level), (1, 5));
    let mending = ENCHANTMENTS.iter().find(|e| e.path == "mending").expect("mending");
    assert_eq!(mending.max_level, 1);
}

/// A census with one level changed must not generate the committed text, or a
/// green drift check proves nothing.
#[test]
fn generator_output_depends_on_the_levels() {
    let mut rows: Vec<(String, u8)> = ENCHANTMENTS
        .iter()
        .map(|e| (e.path.to_owned(), e.max_level))
        .collect();
    let faithful = generate(&rows);
    rows[0].1 += 1;
    assert_ne!(faithful, generate(&rows));
}

#[test]
#[ignore = "reads the gitignored release datapack; run explicitly to regen/verify"]
fn committed_table_matches_datapack() {
    let generated = generate(&read_census(&datapack_dir()));
    if std::env::var_os("LODESTONE_REGEN").is_some() {
        std::fs::write(committed_path(), &generated).expect("write generated table");
        println!("regenerated {}", committed_path().display());
        return;
    }
    let committed = std::fs::read_to_string(committed_path()).expect("read committed table");
    assert_eq!(
        committed, generated,
        "src/generated/enchantments.rs drifted; run with LODESTONE_REGEN=1"
    );
}
