//! Entity-type id→name table: hermetic checks over the committed table, plus an
//! `#[ignore]`d drift guard that regenerates it from Mojang's own
//! `registries.json` and asserts byte-for-byte equality (modelled on the
//! block-state and path-type tables). The generator lives here so the checked-in
//! table can never silently drift from the game data.
//!
//! `registries.json` (under `.cache/mc/26.2/generated/reports/`, gitignored) is
//! Mojang's authoritative registry dump; `minecraft:entity_type` lists every
//! entity type with its network `protocol_id`. Those ids are what `add_entity`
//! puts on the wire, and they shift between releases, so the mapping is
//! version-specific data that must live in this crate.
//!
//! Regenerate the committed table after a data bump with:
//!
//! ```text
//! LODESTONE_REGEN=1 cargo test -p lodestone-data --test entity_types \
//!     committed_table_matches_report -- --ignored --nocapture
//! ```

use std::fmt::Write as _;
use std::path::PathBuf;

use lodestone_data::entity_types::{self, TYPE_COUNT};

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Mojang's authoritative registry report (gitignored local artifact).
fn report_path() -> PathBuf {
    manifest_dir().join("../../.cache/mc/26.2/generated/reports/registries.json")
}

fn committed_path() -> PathBuf {
    manifest_dir().join("src/generated/entity_types.rs")
}

// ---------------------------------------------------------------------------
// Generator (shared by regen and the drift check)
// ---------------------------------------------------------------------------

/// Parses `registries.json` into `names[protocol_id]`, asserting the id space is
/// dense (`0..N`) so an indexed array is a faithful representation.
fn parse_report(doc: &serde_json::Value) -> Vec<String> {
    let entries = doc
        .get("minecraft:entity_type")
        .and_then(|reg| reg.get("entries"))
        .and_then(serde_json::Value::as_object)
        .expect("registries.json has minecraft:entity_type.entries");

    let mut pairs: Vec<(usize, String)> = entries
        .iter()
        .map(|(name, value)| {
            let id = value
                .get("protocol_id")
                .and_then(serde_json::Value::as_u64)
                .expect("entry has a protocol_id") as usize;
            (id, name.clone())
        })
        .collect();
    pairs.sort_by_key(|(id, _)| *id);

    let count = pairs.len();
    let mut names = vec![None; count];
    for (id, name) in pairs {
        assert!(
            id < count,
            "entity_type protocol_id {id} outside a dense 0..{count} range"
        );
        assert!(
            names[id].is_none(),
            "duplicate entity_type protocol_id {id}"
        );
        names[id] = Some(name);
    }
    names
        .into_iter()
        .enumerate()
        .map(|(id, name)| name.unwrap_or_else(|| panic!("gap at entity_type id {id}")))
        .collect()
}

fn generate(doc: &serde_json::Value) -> String {
    let names = parse_report(doc);
    let count = names.len();

    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo test -p lodestone-data --test entity_types -- --ignored`\n\
         // from .cache/mc/26.2/generated/reports/registries.json (protocol 776 /\n\
         // Minecraft 26.2). DO NOT EDIT BY HAND. Regenerate with LODESTONE_REGEN=1 (see\n\
         // the test module docs).\n",
    );
    out.push_str(
        "//! Generated entity-type id->name table for protocol 776 (Minecraft 26.2).\n//!\n",
    );
    out.push_str(
        "//! Maps the network entity-type registry id (the varint carried by\n\
         //! `add_entity`) to its canonical `minecraft:*` identifier. Consumed by\n\
         //! [`crate::entity_types`].\n\n",
    );

    let _ = writeln!(
        out,
        "/// Number of entity types (network ids are `0..TYPE_COUNT`)."
    );
    let _ = writeln!(out, "pub const TYPE_COUNT: u32 = {count};\n");

    let _ = writeln!(
        out,
        "/// Canonical entity-type identifier, indexed by network registry id."
    );
    let _ = writeln!(out, "pub static ENTITY_TYPE_NAMES: [&str; {count}] = [");
    for chunk in names.chunks(4) {
        out.push_str("    ");
        let row: Vec<String> = chunk.iter().map(|name| format!("\"{name}\",")).collect();
        out.push_str(&row.join(" "));
        out.push('\n');
    }
    out.push_str("];\n");

    out
}

// ---------------------------------------------------------------------------
// Hermetic tests over the committed table (no report needed)
// ---------------------------------------------------------------------------

#[test]
fn ids_are_contiguous_and_out_of_range_is_none() {
    for id in 0..TYPE_COUNT as i32 {
        assert!(
            entity_types::entity_type_name(id).is_some(),
            "id {id} in 0..{TYPE_COUNT} did not resolve to a name"
        );
    }
    assert_eq!(entity_types::entity_type_name(-1), None);
    assert_eq!(entity_types::entity_type_name(TYPE_COUNT as i32), None);
    assert_eq!(entity_types::entity_type_name(i32::MAX), None);
}

#[test]
fn known_ids_resolve_to_their_identifiers() {
    // Spot ids that the live seam relies on; a transposed table fails instantly.
    assert_eq!(entity_types::entity_type_name(100), Some("minecraft:pig"));
    // Every name is a well-formed namespaced identifier.
    for id in 0..TYPE_COUNT as i32 {
        let name = entity_types::entity_type_name(id).unwrap();
        assert!(
            name.starts_with("minecraft:") && name.len() > "minecraft:".len(),
            "id {id} has a malformed name {name:?}"
        );
    }
}

// ---------------------------------------------------------------------------
// Drift guard (needs the report; #[ignore]d so the default suite stays hermetic)
// ---------------------------------------------------------------------------

#[test]
#[ignore = "reads the gitignored registries.json; run explicitly to regen/verify"]
fn committed_table_matches_report() {
    let raw = std::fs::read_to_string(report_path())
        .expect("registries.json present under .cache/mc/26.2/generated/reports");
    let doc: serde_json::Value = serde_json::from_str(&raw).expect("registries.json parses");
    let generated = generate(&doc);

    if std::env::var_os("LODESTONE_REGEN").is_some() {
        std::fs::write(committed_path(), &generated).expect("write committed table");
        eprintln!("regenerated {}", committed_path().display());
        return;
    }

    let committed = std::fs::read_to_string(committed_path()).expect("committed table present");
    assert_eq!(
        generated, committed,
        "src/generated/entity_types.rs is stale vs registries.json; regenerate with LODESTONE_REGEN=1"
    );

    // Whole-corpus cross-check: every id in the report resolves through the
    // committed accessor to the same identifier (not a spot check).
    let names = parse_report(&doc);
    assert_eq!(
        names.len(),
        TYPE_COUNT as usize,
        "report/table count mismatch"
    );
    let mut mismatches = 0usize;
    for (id, name) in names.iter().enumerate() {
        if entity_types::entity_type_name(id as i32) != Some(name.as_str()) {
            mismatches += 1;
        }
    }
    println!("=== ENTITY-TYPE TABLE REPORT ===");
    println!(
        "entity types (report / table): {} / {TYPE_COUNT}",
        names.len()
    );
    println!(
        "whole-corpus mismatches       : {mismatches} / {}",
        names.len()
    );
    println!("================================");
    assert_eq!(mismatches, 0, "committed table disagrees with the report");
}
