//! Per-entity-type base-dimension table: hermetic checks over the committed
//! table, plus an `#[ignore]`d drift guard that regenerates it from the
//! committed JVM dump and asserts byte-for-byte equality (modelled on the
//! entity-type and collision-shape tables). The generator lives here so the
//! checked-in table can never silently drift from the game data.
//!
//! # Data provenance
//!
//! `tests/support/entity_dimensions_jvm.txt` is an authoritative dump produced
//! by booting the real 26.2 server and reading vanilla's own entity-type
//! width/height accessors (base entity-dimensions record, scale 1) for every registered type —
//! `width`/`height` as raw f32 bits, keyed by network registry id. It is
//! committed as the external anchor (§ "an expected value must originate outside
//! the code under test"): the table is derived from it, so a misread f32 or a
//! transposed row fails the drift check rather than silently shipping.
//!
//! # Refreshing after a version bump
//!
//! 1. Re-dump from the server (regenerates the gitignored working copy):
//!
//! ```text
//! CACHE="$(cd .cache/mc/26.2 && pwd)"
//! HERE="$(cd crates/protocol/v770/oracle-java && pwd)"
//! docker run --rm -v "$CACHE":/mc:ro -v "$HERE":/oracle -w /work eclipse-temurin:25-jdk bash -c '
//!   CP="/mc/versions/26.2/server-26.2.jar:$(find /mc/libraries -name "*.jar" | tr "\n" ":")"
//!   cp /oracle/EntityDimensionsOracle.java /work/ && javac -cp "$CP" -d /work /work/EntityDimensionsOracle.java
//!   java -cp "/work:$CP" EntityDimensionsOracle'
//! ```
//!
//!    then copy its stdout over `tests/support/entity_dimensions_jvm.txt`
//!    (keeping the `#` header).
//!
//! 2. Regenerate the committed table:
//!
//! ```text
//! LODESTONE_REGEN=1 cargo test -p lodestone-data --test entity_dimensions \
//!     committed_table_matches_dump -- --ignored --nocapture
//! ```

use std::fmt::Write as _;
use std::path::PathBuf;

use lodestone_data::entity_dimensions::{base_dimensions, TYPE_COUNT};

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn committed_path() -> PathBuf {
    manifest_dir().join("src/generated/entity_dimensions.rs")
}

/// The committed JVM dump — an external anchor, not gitignored.
const DUMP: &str = include_str!("support/entity_dimensions_jvm.txt");

/// One authoritative row: network id, name, and the raw f32 bits of the base
/// `width`/`height`.
struct Row {
    id: usize,
    name: String,
    width_bits: u32,
    height_bits: u32,
}

fn parse_dump(text: &str) -> Vec<Row> {
    let mut rows = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut tok = line.split_whitespace();
        let id: usize = tok.next().expect("id column").parse().expect("id is a usize");
        let name = tok.next().expect("name column").to_owned();
        let width_bits =
            u32::from_str_radix(tok.next().expect("width bits column"), 16).expect("width hex");
        let height_bits =
            u32::from_str_radix(tok.next().expect("height bits column"), 16).expect("height hex");
        assert!(tok.next().is_none(), "unexpected trailing tokens on {line:?}");
        rows.push(Row {
            id,
            name,
            width_bits,
            height_bits,
        });
    }
    rows.sort_by_key(|row| row.id);
    for (index, row) in rows.iter().enumerate() {
        assert_eq!(row.id, index, "dump ids are not a dense 0..N (gap at {index})");
    }
    rows
}

fn generate(rows: &[Row]) -> String {
    let count = rows.len();

    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo test -p lodestone-data --test entity_dimensions -- --ignored`\n\
         // from tests/support/entity_dimensions_jvm.txt (a headless 26.2 server dump of\n\
         // EntityType.getWidth()/getHeight(), protocol 776 / Minecraft 26.2). DO NOT EDIT\n\
         // BY HAND. Regenerate with LODESTONE_REGEN=1 (see the test module docs).\n",
    );
    out.push_str(
        "//! Generated per-entity-type base `(width, height)` table for protocol 776\n\
         //! (Minecraft 26.2), indexed by network entity-type registry id. Base dims only\n\
         //! (no scale, no step_height). Consumed by [`crate::entity_dimensions`].\n\n",
    );

    let _ = writeln!(
        out,
        "/// Number of entity types (network ids are `0..TYPE_COUNT`)."
    );
    let _ = writeln!(out, "pub const TYPE_COUNT: u32 = {count};\n");

    let _ = writeln!(
        out,
        "/// Base `(width, height)` hitbox in blocks, indexed by network registry id."
    );
    let _ = writeln!(out, "pub static ENTITY_DIMENSIONS: [(f32, f32); {count}] = [");
    for row in rows {
        // Round-trip through the exact f32 the game produced. Rust's `{:?}`
        // emits the shortest decimal that parses back to the same f32, so the
        // literal is human-readable *and* bit-exact.
        let width = f32::from_bits(row.width_bits);
        let height = f32::from_bits(row.height_bits);
        assert_eq!(
            width.to_bits(),
            row.width_bits,
            "width literal for {} does not round-trip",
            row.name
        );
        assert_eq!(
            height.to_bits(),
            row.height_bits,
            "height literal for {} does not round-trip",
            row.name
        );
        let _ = writeln!(out, "    ({width:?}, {height:?}), // {} {}", row.id, row.name);
    }
    out.push_str("];\n");

    out
}

// ---------------------------------------------------------------------------
// Hermetic tests over the committed table (anchored to the committed dump)
// ---------------------------------------------------------------------------

#[test]
fn committed_table_matches_the_committed_dump_bit_for_bit() {
    // The strongest check: every value in the shipped accessor equals the raw
    // f32 the real server produced. Non-vacuous by construction — it iterates
    // all 158 types and compares exact bits, so a single misread float fails.
    let rows = parse_dump(DUMP);
    assert_eq!(
        rows.len(),
        TYPE_COUNT as usize,
        "dump/table type count mismatch"
    );
    let mut checked = 0usize;
    for row in &rows {
        let dims = base_dimensions(row.id as i32)
            .unwrap_or_else(|| panic!("id {} ({}) missing from table", row.id, row.name));
        assert_eq!(
            dims.width.to_bits(),
            row.width_bits,
            "width mismatch for {} (id {}): table {:?} vs server f32::from_bits(0x{:08x})",
            row.name,
            row.id,
            dims.width,
            row.width_bits
        );
        assert_eq!(
            dims.height.to_bits(),
            row.height_bits,
            "height mismatch for {} (id {}): table {:?} vs server f32::from_bits(0x{:08x})",
            row.name,
            row.id,
            dims.height,
            row.height_bits
        );
        checked += 1;
    }
    assert_eq!(checked, 158, "expected 158 entity types checked, got {checked}");
}

// ---------------------------------------------------------------------------
// Drift guard (regenerates from the committed dump; `#[ignore]`d for parity
// with the other generated tables, though it needs no external artifact)
// ---------------------------------------------------------------------------

#[test]
#[ignore = "regenerates/verifies the committed table; run explicitly"]
fn committed_table_matches_dump() {
    let rows = parse_dump(DUMP);
    let generated = generate(&rows);

    if std::env::var_os("LODESTONE_REGEN").is_some() {
        std::fs::write(committed_path(), &generated).expect("write committed table");
        eprintln!("regenerated {}", committed_path().display());
        return;
    }

    let committed = std::fs::read_to_string(committed_path()).expect("committed table present");
    assert_eq!(
        generated, committed,
        "src/generated/entity_dimensions.rs is stale vs the JVM dump; regenerate with LODESTONE_REGEN=1"
    );
}
