//! `Item` enum: hermetic checks over the committed table, plus an `#[ignore]`d
//! drift guard that regenerates it from the committed JVM dump and asserts
//! byte-for-byte equality — modelled on `tools.rs`'s `generate_block_enum` and
//! `block_enum.rs`'s gates. The generator lives here so the checked-in enum can
//! never silently drift from game data.
//!
//! # Data provenance
//!
//! `tests/support/item_prototype_jvm.txt` is already the committed JVM dump for
//! this registry: `ItemPrototypeOracle.java` walks vanilla's own item registry on
//! the real 26.2 server and writes one `P <registryId> <itemName> …` line per
//! item, in registration order. `tests/item_prototypes.rs`'s
//! `dump_ids_and_names_match_the_registries_json_table` already cross-checked
//! this id/name pairing against Mojang's own `registries.json`
//! (`crate::items::item_name`, generated by `cargo xtask gen-registries`), so
//! the two independently produced artifacts agree on all 1,537 pairs before
//! this file ever runs. This generator reads only the `id`/`name` columns of
//! that same dump; the other columns (stack size, damage, equip slot) are
//! `item_prototypes.rs`'s concern, not this one's.
//!
//! Unlike `generate_block_enum`, there is no default-state table to join in —
//! an item has no analogue of a block state.
//!
//! # Refreshing after a version bump
//!
//! 1. Re-dump `tests/support/item_prototype_jvm.txt` per the recipe in
//!    `tests/item_prototypes.rs`'s module docs.
//! 2. Regenerate the committed enum:
//!
//! ```text
//! LODESTONE_REGEN=1 cargo test -p lodestone-data --test item_enum \
//!     committed_enum_matches_dump -- --ignored --nocapture
//! ```

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::PathBuf;

use lodestone_data::item::{CustomItemId, Item, ItemKind, ItemRef};

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn committed_path() -> PathBuf {
    manifest_dir().join("src/generated/item_enum.rs")
}

/// The committed JVM dump — an external anchor, not gitignored. Shared with
/// `tests/item_prototypes.rs`, but parsed independently here.
const DUMP: &str = include_str!("support/item_prototype_jvm.txt");

// ---------------------------------------------------------------------------
// Dump parsing (id + name columns only)
// ---------------------------------------------------------------------------

fn parse_dump(text: &str) -> Vec<(u16, String)> {
    let mut rows: Vec<(u16, String)> = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut tok = line.split_whitespace();
        assert_eq!(tok.next(), Some("P"), "unexpected record kind on {line:?}");
        let id: u16 = tok
            .next()
            .expect("id column")
            .parse()
            .expect("id fits u16");
        let name = tok.next().expect("name column").to_owned();
        rows.push((id, name));
    }
    rows.sort_unstable_by_key(|(id, _)| *id);
    for (index, (id, _)) in rows.iter().enumerate() {
        assert_eq!(
            *id as usize, index,
            "dump ids are not a dense 0..N (gap at {index})"
        );
    }
    rows
}

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

/// The Rust enum variant name for a registry path: `oak_sapling` → `OakSapling`.
///
/// Callers must have already checked the path against
/// [`assert_path_is_variant_safe`]; this function only transforms.
fn variant_name(path: &str) -> String {
    let mut out = String::with_capacity(path.len());
    for word in path.split('_') {
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            out.extend(first.to_uppercase());
            out.push_str(chars.as_str());
        }
    }
    out
}

/// Fails the generator — loudly, naming the offender — if any item name cannot
/// become a distinct, legal Rust variant. Mirrors
/// `tools.rs`'s `assert_path_is_variant_safe`, whose reasoning applies
/// unchanged: a silently-aliased collision is the dangerous failure mode, not
/// a non-compiling variant. `docs/registry-types.md` already recorded this
/// registry as clean (1,537 paths, 1,537 distinct variants, all
/// `minecraft:`, none digit-leading); asserting it here is what keeps that
/// true after a version bump rather than a fact that happened to hold once.
fn assert_path_is_variant_safe(names: &[String]) -> Vec<(String, String)> {
    let mut seen: BTreeMap<String, String> = BTreeMap::new();
    let mut pairs = Vec::with_capacity(names.len());
    for name in names {
        let (namespace, path) = name
            .split_once(':')
            .unwrap_or_else(|| panic!("registry name {name:?} has no namespace"));
        assert_eq!(
            namespace, "minecraft",
            "the generated enum covers the built-in registry only; {name:?} is not `minecraft:`"
        );
        assert!(
            !path.is_empty()
                && path
                    .bytes()
                    .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_'),
            "item path {path:?} is outside [a-z0-9_] and has no obvious variant spelling"
        );
        assert!(
            !path.as_bytes()[0].is_ascii_digit(),
            "item path {path:?} starts with a digit, which is not a legal Rust variant"
        );
        let variant = variant_name(path);
        assert_ne!(
            variant, "Self",
            "item path {path:?} camel-cases to the reserved identifier `Self`"
        );
        if let Some(previous) = seen.insert(variant.clone(), path.to_owned()) {
            panic!(
                "item paths {previous:?} and {path:?} both camel-case to `{variant}`; the \
                 generator must be taught a disambiguation rather than silently aliasing them"
            );
        }
        pairs.push((variant, name.clone()));
    }
    pairs
}

/// Renders `src/generated/item_enum.rs`: the `Item` enum whose discriminant
/// **is** the `minecraft:item` registry id, plus the name-lookup index table.
fn generate(rows: &[(u16, String)]) -> String {
    let count = rows.len();
    let names: Vec<String> = rows.iter().map(|(_, name)| name.clone()).collect();
    let variants = assert_path_is_variant_safe(&names);

    let mut by_name: Vec<u16> = (0..count as u16).collect();
    by_name.sort_unstable_by(|&a, &b| names[a as usize].cmp(&names[b as usize]));

    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo test -p lodestone-data --test item_enum -- --ignored`\n\
         // from tests/support/item_prototype_jvm.txt (a headless 26.2 server dump of\n\
         // BuiltInRegistries.ITEM's registration order, protocol 776 / Minecraft 26.2).\n\
         // DO NOT EDIT BY HAND. Regenerate with LODESTONE_REGEN=1 (see the test module\n\
         // docs).\n",
    );
    out.push_str(
        "//! The generated `minecraft:item` registry as a Rust enum.\n\
         //!\n\
         //! One variant per built-in item, in **registration** order, with the\n\
         //! discriminant written out explicitly so that `item as u16` *is* the registry\n\
         //! id a `Holder<Item>` carries on the wire — no lookup, no branch, no table. That\n\
         //! identity is the whole point of the representation: every per-item census in\n\
         //! this crate is a plain array indexed by it.\n\
         //!\n\
         //! The accessors live in [`crate::item`]; this file is data only.\n\n",
    );

    let _ = writeln!(
        out,
        "/// A built-in item of Minecraft 26.2, one variant per `minecraft:item`\n\
         /// registry entry.\n\
         ///\n\
         /// `Item as u16` is the registry id. Ordering is **registration** order, not\n\
         /// alphabetical.\n\
         ///\n\
         /// This enum is intentionally *not* `#[non_exhaustive]` and carries no `Custom`\n\
         /// variant: a match over it is exhaustive, so a version bump that adds an item\n\
         /// fails the compile of every incomplete match instead of falling into a\n\
         /// wildcard. Items a plugin adds are represented by [`crate::item::ItemRef`],\n\
         /// one level out.\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\n\
         #[repr(u16)]\n\
         pub enum Item {{"
    );
    for (id, (variant, name)) in variants.iter().enumerate() {
        let _ = writeln!(out, "    /// `{name}`\n    {variant} = {id},");
    }
    out.push_str("}\n\n");

    let _ = writeln!(
        out,
        "/// Every [`Item`], indexed by its registry id — the safe inverse of\n\
         /// `item as u16`, and the iteration order of the registry.\n\
         ///\n\
         /// An array rather than a {count}-arm `match` because this crate forbids\n\
         /// `unsafe` (so the transmute is unavailable) and because a table index is one\n\
         /// bounds check where the match is a jump table plus {count} lines for rustc to\n\
         /// chew.\n\
         pub static ITEMS_BY_REGISTRY_ID: [Item; {count}] = ["
    );
    for chunk in variants.chunks(4) {
        out.push_str("    ");
        for (variant, _) in chunk {
            let _ = write!(out, "Item::{variant}, ");
        }
        out.pop();
        out.push('\n');
    }
    out.push_str("];\n\n");

    let _ = writeln!(
        out,
        "/// Registry ids sorted by canonical name, for `O(log {count})` name lookup\n\
         /// against [`crate::generated_items::ITEM_NAMES`].\n\
         ///\n\
         /// A permutation of `u16` rather than a `[(&str, Item)]` pairs table on purpose:\n\
         /// the pairs table would re-introduce {count} fat pointers and their relocations\n\
         /// for names that already exist once in rodata.\n\
         pub static REGISTRY_IDS_BY_NAME: [u16; {count}] = ["
    );
    for chunk in by_name.chunks(16) {
        out.push_str("    ");
        for id in chunk {
            let _ = write!(out, "{id}, ");
        }
        out.pop();
        out.push('\n');
    }
    out.push_str("];\n");
    out
}

// ---------------------------------------------------------------------------
// Hermetic tests over the committed enum (anchored to the committed dump,
// re-parsed independently of the generator)
// ---------------------------------------------------------------------------

/// The load-bearing identity: the enum discriminant *is* the wire's registry
/// id, and the name attached to it is the one the server registered there.
/// Mirrors `block_enum.rs`'s
/// `discriminant_is_the_registry_id_and_names_match_the_server_dump`.
#[test]
fn discriminant_is_the_registry_id_and_names_match_the_server_dump() {
    let rows = parse_dump(DUMP);
    assert_eq!(rows.len(), Item::COUNT as usize, "dump/enum item count");

    let mut mismatches = Vec::new();
    for (id, name) in &rows {
        match Item::from_registry_id(*id) {
            Some(item) => {
                if item.registry_id() != *id || item.name() != name {
                    mismatches.push(format!(
                        "id {id} ({name}): enum gave {:?} = id {} name {}",
                        item,
                        item.registry_id(),
                        item.name()
                    ));
                }
            }
            None => mismatches.push(format!("id {id} ({name}): enum has no such registry id")),
        }
    }
    assert!(
        mismatches.is_empty(),
        "{} of {} items disagree with the dump:\n{}",
        mismatches.len(),
        rows.len(),
        mismatches.join("\n")
    );
    assert_eq!(Item::from_registry_id(Item::COUNT), None);
    assert_eq!(Item::all().len(), rows.len());
}

#[test]
fn name_order_is_also_path_order() {
    let names: Vec<&'static str> = Item::all().map(Item::name).collect();
    let paths: Vec<&'static str> = Item::all().map(Item::path).collect();
    let mut by_name: Vec<usize> = (0..names.len()).collect();
    let mut by_path = by_name.clone();
    by_name.sort_by_key(|&i| names[i]);
    by_path.sort_by_key(|&i| paths[i]);
    assert_eq!(
        by_name, by_path,
        "sorting items by namespaced name and by bare path give different orders; \
         `Item::from_name`'s bare-path search is no longer sound"
    );
}

#[test]
fn names_and_paths_round_trip_through_from_name() {
    let mut failures = Vec::new();
    for item in Item::all() {
        if Item::from_name(item.name()) != Some(item) {
            failures.push(format!("{}: namespaced form did not round-trip", item.name()));
        }
        if Item::from_name(item.path()) != Some(item) {
            failures.push(format!("{}: bare path did not round-trip", item.path()));
        }
        if item.name() != format!("minecraft:{}", item.path()) {
            failures.push(format!("{}: name/path disagree", item.name()));
        }
    }
    assert!(
        failures.is_empty(),
        "{} round-trip failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn from_name_rejects_foreign_namespaces_and_unknown_paths() {
    assert_eq!(Item::from_name("minecraft:diamond"), Some(Item::Diamond));
    assert_eq!(Item::from_name("diamond"), Some(Item::Diamond));
    assert_eq!(Item::from_name("mypack:diamond"), None);
    assert_eq!(Item::from_name("minecraft:not_an_item"), None);
    assert_eq!(Item::from_name(""), None);
    assert_eq!(Item::from_name("minecraft:"), None);
}

/// The representation claims, as numbers — mirrors `block_enum.rs`'s sibling
/// test. `Option<Item>` costing the same as `Item` is what makes an
/// `[Option<Item>; 1537]` census half the width of `[Option<&str>; 1537]` on a
/// 32-bit target and a quarter on a 64-bit one.
#[test]
fn the_representation_is_the_size_it_claims() {
    assert_eq!(size_of::<Item>(), 2, "Item is a u16 discriminant");
    assert_eq!(
        size_of::<Option<Item>>(),
        2,
        "Option<Item> must use the unused discriminants as its niche"
    );
    assert_eq!(size_of::<ItemRef>(), 4);
}

/// `ItemRef` must cost the built-in path nothing and still carry a custom id
/// losslessly, including at the boundary where the two encodings meet.
#[test]
fn item_ref_separates_builtin_from_custom_without_aliasing() {
    for item in Item::all() {
        let reference = ItemRef::builtin(item);
        assert_eq!(reference.kind(), ItemKind::Builtin(item));
        assert_eq!(reference.builtin_or_none(), Some(item));
    }
    for index in [0u32, 1, 7, 1_000_000, u32::MAX - Item::COUNT as u32] {
        let id = CustomItemId::from_index(index);
        let reference = ItemRef::custom(id);
        assert_eq!(reference.kind(), ItemKind::Custom(id));
        assert_eq!(reference.builtin_or_none(), None);
        assert_eq!(
            reference.kind(),
            ItemKind::Custom(CustomItemId::from_index(index)),
            "custom index {index} did not survive the round trip"
        );
    }
    assert_ne!(
        ItemRef::builtin(Item::from_registry_id(Item::COUNT - 1).expect("last item")),
        ItemRef::custom(CustomItemId::from_index(0)),
        "the last built-in item and the first custom item collided"
    );
}

// ---------------------------------------------------------------------------
// Drift guard (regenerates from the committed dump; needs no external
// artifact beyond it)
// ---------------------------------------------------------------------------

#[test]
#[ignore = "regenerates/verifies the committed enum; run explicitly"]
fn committed_enum_matches_dump() {
    let rows = parse_dump(DUMP);
    let generated = generate(&rows);

    if std::env::var_os("LODESTONE_REGEN").is_some() {
        std::fs::write(committed_path(), &generated).expect("write item enum");
        eprintln!("regenerated {}", committed_path().display());
        return;
    }

    let committed = std::fs::read_to_string(committed_path()).expect("committed item enum present");
    assert_eq!(
        generated, committed,
        "src/generated/item_enum.rs is stale vs the JVM dump; regenerate with LODESTONE_REGEN=1"
    );
}
