//! Potion effect-name base ids: fixture-backed generation and whole-table drift checks.
//!
//! `tests/support/potion_effect_bases_26_2.txt` records all 46 built-in potion
//! registrations as `(registry id, canonical name, explicit base-potion name)`.
//! The last column was transcribed from the cached 26.2 source and is deliberately
//! independent of the generated table: an alias is data, never a prefix-removal rule.
//!
//! Regenerate after refreshing the fixture with:
//!
//! ```text
//! LODESTONE_REGEN=1 cargo test -p lodestone-data --test potion_effect_ids \
//!     committed_table_matches_the_committed_fixture -- --nocapture
//! ```

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::PathBuf;

use lodestone_data::potion::{self, POTION_COUNT};

const FIXTURE: &str = include_str!("support/potion_effect_bases_26_2.txt");

#[derive(Debug, Clone, PartialEq, Eq)]
struct Row {
    id: usize,
    potion_name: String,
    base_name: String,
}

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn committed_path() -> PathBuf {
    manifest_dir().join("src/generated/potion_effect_ids.rs")
}

fn retired_string_table_path() -> PathBuf {
    manifest_dir().join("src/generated/potion_effect_keys.rs")
}

fn parse_fixture(text: &str, expected_count: usize) -> Result<Vec<Row>, String> {
    let mut by_id = vec![None; expected_count];
    let mut names = BTreeSet::new();

    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut columns = line.split_whitespace();
        let id = columns
            .next()
            .ok_or_else(|| format!("missing id in {line:?}"))?
            .parse::<usize>()
            .map_err(|error| format!("invalid id in {line:?}: {error}"))?;
        let potion_name = columns
            .next()
            .ok_or_else(|| format!("missing potion name in {line:?}"))?;
        let base_name = columns
            .next()
            .ok_or_else(|| format!("missing base-potion name in {line:?}"))?;
        if columns.next().is_some() {
            return Err(format!("unexpected trailing columns in {line:?}"));
        }
        if id >= expected_count {
            return Err(format!(
                "potion id {id} is outside the required 0..{expected_count} range"
            ));
        }
        for (label, name) in [("potion", potion_name), ("base potion", base_name)] {
            let Some(path) = name.strip_prefix("minecraft:") else {
                return Err(format!("{label} name {name:?} is not namespaced"));
            };
            if path.is_empty() || path.contains(':') {
                return Err(format!("{label} name {name:?} has an invalid path"));
            }
        }
        if !names.insert(potion_name.to_owned()) {
            return Err(format!("duplicate potion name {potion_name:?}"));
        }
        if by_id[id].is_some() {
            return Err(format!("duplicate potion id {id}"));
        }
        by_id[id] = Some(Row {
            id,
            potion_name: potion_name.to_owned(),
            base_name: base_name.to_owned(),
        });
    }

    by_id
        .into_iter()
        .enumerate()
        .map(|(id, row)| row.ok_or_else(|| format!("missing potion id {id}")))
        .collect()
}

fn base_ids(rows: &[Row]) -> Result<Vec<u8>, String> {
    rows
        .iter()
        .map(|row| {
            let base_id = rows
                .iter()
                .position(|candidate| candidate.potion_name == row.base_name)
                .ok_or_else(|| {
                    format!(
                        "potion id {} maps to absent base potion {:?}",
                        row.id, row.base_name
                    )
                })?;
            u8::try_from(base_id).map_err(|_| {
                format!(
                    "base potion {:?} has id {base_id}, outside the generated u8 range",
                    row.base_name
                )
            })
        })
        .collect()
}

fn generate(rows: &[Row]) -> Result<String, String> {
    let ids = base_ids(rows)?;
    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo test -p lodestone-data --test potion_effect_ids`\n\
         // from tests/support/potion_effect_bases_26_2.txt (protocol 776 / Minecraft\n\
         // 26.2). DO NOT EDIT BY HAND. Regenerate with LODESTONE_REGEN=1 (see the test\n\
         // module docs).\n\
         //! Generated potion -> base-potion id table for protocol 776 (Minecraft 26.2).\n//!\n\
         //! Each value is a network id into [`crate::generated_potions::POTION_NAMES`].\n\
         //! Aliases are explicit source data: no name prefix is removed to infer them.\n\n\
         /// Base-potion registry id, indexed by potion registry id.\n\
         pub static POTION_EFFECT_BASE_IDS: [u8; crate::generated_potions::POTION_COUNT as usize] = [\n",
    );
    for (row, base_id) in rows.iter().zip(ids) {
        let _ = writeln!(
            out,
            "    {base_id}, // {} {} -> {}",
            row.id, row.potion_name, row.base_name
        );
    }
    out.push_str("];\n");
    Ok(out)
}

#[test]
fn fixture_covers_every_mapping_and_unique_base() {
    let rows = parse_fixture(FIXTURE, POTION_COUNT as usize).expect("valid potion fixture");
    let bases = base_ids(&rows).expect("every base potion resolves within the fixture");
    assert_eq!(rows.len(), 46, "the complete protocol-776 potion registry");
    assert_eq!(bases.iter().copied().collect::<BTreeSet<_>>().len(), 24);

    for (row, base_id) in rows.iter().zip(bases) {
        assert_eq!(potion::potion_name(row.id as i32), Some(row.potion_name.as_str()));
        let expected_key = row
            .base_name
            .strip_prefix("minecraft:")
            .expect("validated namespace");
        assert_eq!(potion::potion_effect_key(row.id as i32), Some(expected_key));
        assert_eq!(
            potion::potion_name(i32::from(base_id)),
            Some(row.base_name.as_str()),
            "potion id {} must join through its canonical base-potion row",
            row.id
        );
    }
}

#[test]
fn aliases_and_irregular_keys_use_the_explicit_mapping() {
    for ids in [[13, 14, 15], [19, 20, 21]] {
        let expected = potion::potion_effect_key(ids[0]);
        assert!(ids.into_iter().all(|id| potion::potion_effect_key(id) == expected));
    }
    assert_eq!(potion::potion_effect_key(20), Some("turtle_master"));
    assert_eq!(potion::potion_effect_key(40), Some("slow_falling"));
    assert_eq!(potion::potion_effect_key(42), Some("wind_charged"));
    assert_eq!(potion::potion_effect_key(45), Some("infested"));

    let rows = parse_fixture(
        "0 minecraft:water minecraft:water\n\
         1 minecraft:long_swiftness minecraft:water\n",
        2,
    )
    .expect("synthetic explicit alias fixture parses");
    assert_eq!(base_ids(&rows), Ok(vec![0, 0]));
}

#[test]
fn negative_and_out_of_range_ids_are_none() {
    assert_eq!(potion::potion_effect_key(i32::MIN), None);
    assert_eq!(potion::potion_effect_key(-1), None);
    assert_eq!(potion::potion_effect_key(POTION_COUNT as i32), None);
    assert_eq!(potion::potion_effect_key(i32::MAX), None);
}

#[test]
fn invalid_and_out_of_range_source_mappings_are_rejected() {
    let out_of_range = "0 minecraft:water minecraft:water\n2 minecraft:thick minecraft:thick\n";
    assert!(parse_fixture(out_of_range, 2).unwrap_err().contains("outside"));

    let gapped = "0 minecraft:water minecraft:water\n2 minecraft:thick minecraft:thick\n";
    assert!(parse_fixture(gapped, 3).unwrap_err().contains("missing potion id 1"));

    let missing_base = vec![Row {
        id: 0,
        potion_name: "minecraft:water".to_owned(),
        base_name: "minecraft:not_registered".to_owned(),
    }];
    assert!(base_ids(&missing_base).unwrap_err().contains("absent base potion"));

    let duplicate = "0 minecraft:water minecraft:water\n0 minecraft:thick minecraft:thick\n";
    assert!(parse_fixture(duplicate, 2).unwrap_err().contains("duplicate potion id"));

    let duplicate_name =
        "0 minecraft:water minecraft:water\n1 minecraft:water minecraft:water\n";
    assert!(
        parse_fixture(duplicate_name, 2)
            .unwrap_err()
            .contains("duplicate potion name")
    );

    let too_wide: Vec<Row> = (0..=usize::from(u8::MAX) + 1)
        .map(|id| Row {
            id,
            potion_name: format!("minecraft:potion_{id}"),
            base_name: format!("minecraft:potion_{id}"),
        })
        .collect();
    assert!(base_ids(&too_wide).unwrap_err().contains("outside the generated u8 range"));
}

#[test]
fn committed_table_matches_the_committed_fixture() {
    let rows = parse_fixture(FIXTURE, POTION_COUNT as usize).expect("valid potion fixture");
    let generated = generate(&rows).expect("fixture maps to numeric base-potion ids");

    if std::env::var_os("LODESTONE_REGEN").is_some() {
        std::fs::write(committed_path(), &generated).expect("write generated potion table");
        eprintln!("regenerated {}", committed_path().display());
        return;
    }

    let committed = std::fs::read_to_string(committed_path())
        .expect("generated numeric potion-effect table is committed");
    assert_eq!(generated, committed, "generated potion-effect table is stale");
    assert!(
        !retired_string_table_path().exists(),
        "the retired generated string table must not remain beside the numeric table"
    );
}
