//! Generator and drift controls for the redstone-conductor table.
//!
//! The external dump is produced by `just oracle-redstone-conductor` after a
//! real server registry walk of the `mc-version` release. It names states, and
//! this test joins them to the canonical state ids. Regenerate the Rust source
//! with:
//!
//! ```text
//! LODESTONE_REGEN=1 cargo test -p lodestone-data --test redstone_conductor \
//!     committed_table_matches_dump -- --ignored --nocapture
//! ```

use std::fmt::Write as _;
use std::path::PathBuf;

use lodestone_data::{block_states, redstone_conductor};

/// The committed JVM dump - an external anchor, not generated Rust data.
const DUMP: &str = include_str!("support/redstone_conductor_jvm.txt");

/// The conducts bit of every canonical state, joined by name, and the count of
/// states the dump named.
fn joined() -> (Vec<Option<bool>>, usize) {
    let mut bits = vec![None; block_states::STATE_COUNT as usize];
    let mut named = 0;
    let mut declared = None;
    for line in DUMP.lines().map(str::trim).filter(|l| !l.is_empty() && !l.starts_with('#')) {
        let mut parts = line.splitn(3, ' ');
        match parts.next().expect("row kind") {
            "C" => declared = Some(parts.next().expect("count").parse::<usize>().expect("usize")),
            "S" => {
                let conducts = parts.next().expect("bit") == "1";
                let state = parts.next().expect("state");
                let id = block_states::StateId::from_state_str(state)
                    .unwrap_or_else(|| panic!("dump state {state} is not a canonical state"));
                let slot = &mut bits[id.raw() as usize];
                assert!(slot.is_none(), "{state} named twice");
                *slot = Some(conducts);
                named += 1;
            }
            kind => panic!("unknown dump row {kind}"),
        }
    }
    assert_eq!(Some(named), declared, "C row matches the S rows");
    (bits, named)
}

fn generate(bits: &[bool]) -> String {
    let words = bits.len().div_ceil(64);
    let mut packed = vec![0u64; words];
    for (state, &set) in bits.iter().enumerate() {
        if set {
            packed[state / 64] |= 1u64 << (state % 64);
        }
    }
    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo test -p lodestone-data --test redstone_conductor -- --ignored`\n\
         // from tests/support/redstone_conductor_jvm.txt (a headless server dump of the\n\
         // `mc-version` release). DO NOT EDIT BY HAND. Regenerate with LODESTONE_REGEN=1.\n\n\
         //! Generated per-state redstone-conductor bits, indexed by global block-state id.\n\n",
    );
    let _ = writeln!(out, "/// Number of block states (ids are `0..STATE_COUNT`).");
    let _ = writeln!(out, "pub const STATE_COUNT: u32 = {};\n", bits.len());
    let _ = writeln!(out, "/// Bit `id % 64` of word `id / 64` is set when the state conducts.");
    let _ = writeln!(out, "pub static REDSTONE_CONDUCTOR: [u64; {words}] = [");
    for chunk in packed.chunks(4) {
        out.push_str("    ");
        for word in chunk {
            let _ = write!(out, "0x{word:016x}, ");
        }
        out.pop();
        out.push('\n');
    }
    out.push_str("];\n");
    out
}

#[test]
fn every_canonical_state_is_named_by_the_dump_and_matches_the_table() {
    let (bits, named) = joined();
    assert_eq!(named, block_states::STATE_COUNT as usize, "the dump covers every canonical state");
    assert_eq!(redstone_conductor::STATE_COUNT, block_states::STATE_COUNT);
    for (raw, bit) in bits.iter().enumerate() {
        let state = block_states::StateId::new(raw as u32).expect("valid id");
        assert_eq!(Some(redstone_conductor::conducts(state)), *bit, "state {raw}");
    }
}

#[test]
fn glass_leaves_and_air_do_not_conduct_but_stone_does() {
    let conducts = |name: &str| {
        redstone_conductor::conducts(block_states::StateId::from_state_str(name).expect("state"))
    };
    assert!(conducts("minecraft:stone"));
    assert!(conducts("minecraft:dirt"));
    for non in ["minecraft:air", "minecraft:glass", "minecraft:oak_slab[type=bottom,waterlogged=false]"] {
        assert!(!conducts(non), "{non}");
    }
}

#[test]
#[ignore = "regenerates and checks the committed table from the oracle dump"]
fn committed_table_matches_dump() {
    let (bits, _) = joined();
    let bits: Vec<bool> = bits.into_iter().map(|b| b.expect("every state named")).collect();
    let generated = generate(&bits);
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src/generated/redstone_conductor.rs");
    if std::env::var_os("LODESTONE_REGEN").is_some() {
        std::fs::write(&path, generated).expect("write generated table");
        return;
    }
    let committed = std::fs::read_to_string(&path).expect("generated table is present");
    assert_eq!(generated, committed, "src/generated/redstone_conductor.rs is stale");
}
