//! Generator and drift controls for the redstone-conductor table.
//!
//! The external dump is produced by `just oracle-redstone-conductor` after a
//! real 26.2 server registry walk. Only the 26.2 state-id prefix is captured:
//! the block-state table is an append-only union with 26.3, and states added
//! after 26.2 read as unknown. Regenerate the Rust source with:
//!
//! ```text
//! LODESTONE_REGEN=1 cargo test -p lodestone-data --test redstone_conductor \
//!     committed_table_matches_dump -- --ignored --nocapture
//! ```

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::PathBuf;

use lodestone_data::{block_states, redstone_conductor};

/// The committed JVM dump - an external anchor, not generated Rust data.
const DUMP: &str = include_str!("support/redstone_conductor_jvm.txt");

struct Dump {
    state_count: usize,
    blocks: Vec<(usize, String)>,
    trues: usize,
    bits: Vec<bool>,
}

fn parse_dump(text: &str) -> Dump {
    let (mut state_count, mut block_count, mut trues) = (None, None, None);
    let mut blocks = Vec::new();
    let mut chunks: BTreeMap<usize, String> = BTreeMap::new();
    for line in text.lines().map(str::trim).filter(|l| !l.is_empty() && !l.starts_with('#')) {
        let mut parts = line.split_whitespace();
        match parts.next().expect("row kind") {
            "C" => {
                state_count = Some(parts.next().expect("states").parse::<usize>().expect("usize"));
                block_count = Some(parts.next().expect("blocks").parse::<usize>().expect("usize"));
            }
            "B" => {
                let start = parts.next().expect("start").parse::<usize>().expect("usize");
                blocks.push((start, parts.next().expect("name").to_owned()));
            }
            "K" => trues = Some(parts.next().expect("count").parse::<usize>().expect("usize")),
            "P" => {
                let start = parts.next().expect("start").parse::<usize>().expect("usize");
                let bits = parts.next().expect("bits");
                assert!(bits.bytes().all(|b| b == b'0' || b == b'1'));
                assert!(chunks.insert(start, bits.to_owned()).is_none(), "duplicate P row");
            }
            kind => panic!("unknown dump row {kind}"),
        }
    }
    let state_count = state_count.expect("C row");
    assert_eq!(blocks.len(), block_count.expect("C row"), "B rows cover every block");
    let mut bits = Vec::with_capacity(state_count);
    for (start, chunk) in chunks {
        assert_eq!(start, bits.len(), "P chunks are gap-free and ordered");
        bits.extend(chunk.bytes().map(|b| b == b'1'));
    }
    assert_eq!(bits.len(), state_count);
    Dump { state_count, blocks, trues: trues.expect("K row"), bits }
}

fn generate(dump: &Dump) -> String {
    let words = dump.state_count.div_ceil(64);
    let mut packed = vec![0u64; words];
    for (state, &set) in dump.bits.iter().enumerate() {
        if set {
            packed[state / 64] |= 1u64 << (state % 64);
        }
    }
    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo test -p lodestone-data --test redstone_conductor -- --ignored`\n\
         // from tests/support/redstone_conductor_jvm.txt (a headless 26.2 server dump,\n\
         // protocol 776 / Minecraft 26.2). DO NOT EDIT BY HAND. Regenerate with LODESTONE_REGEN=1.\n\n\
         //! Generated per-state redstone-conductor bits, indexed by global block-state id.\n\n",
    );
    let _ = writeln!(out, "/// Number of block states (ids are `0..STATE_COUNT`).");
    let _ = writeln!(out, "pub const STATE_COUNT: u32 = {};\n", dump.state_count);
    let _ = writeln!(out, "/// Bit `id % 64` of word `id / 64` is set when the state conducts.");
    let _ = writeln!(out, "pub static REDSTONE_CONDUCTOR: [u64; {words}] = [");
    for chunk in packed.chunks(4) {
        out.push_str("    ");
        for word in chunk {
            let _ = write!(out, "0x{word:016x}, ");
        }
        out.pop();
        out.push('\n');
    }
    out.push_str("];\n");
    out
}

fn assert_committed_bits_match_dump(dump: &Dump) {
    assert_eq!(dump.state_count, 32_366, "complete 26.2 prefix");
    assert_eq!(redstone_conductor::STATE_COUNT as usize, dump.state_count);
    assert!(block_states::STATE_COUNT >= redstone_conductor::STATE_COUNT, "the 26.2 states are a prefix");
    for raw in 0..dump.state_count {
        let index = dump.blocks.partition_point(|(start, _)| *start <= raw) - 1;
        let expected = block_states::block_name(raw as u32).expect("canonical state has a name");
        assert_eq!(dump.blocks[index].1, expected, "block coverage agrees at state {raw}");
    }
    let mut count = 0;
    for (raw, &want) in dump.bits.iter().enumerate() {
        let state = block_states::StateId::new(raw as u32).expect("dump id is valid");
        let got = redstone_conductor::conducts(state).expect("inside the captured prefix");
        assert_eq!(got, want, "state {raw}: committed {got}, dump {want}");
        count += usize::from(got);
    }
    assert_eq!(count, dump.trues, "population matches the JVM K row");
}

#[test]
fn committed_bits_match_dump() {
    assert_committed_bits_match_dump(&parse_dump(DUMP));
}

#[test]
fn glass_leaves_and_air_do_not_conduct_but_stone_does() {
    let conducts = |name: &str| {
        redstone_conductor::conducts(block_states::StateId::from_state_str(name).expect("state"))
            .expect("a 26.2 state")
    };
    assert!(conducts("minecraft:stone"));
    assert!(conducts("minecraft:dirt"));
    for non in ["minecraft:air", "minecraft:glass", "minecraft:oak_slab[type=bottom,waterlogged=false]"] {
        assert!(!conducts(non), "{non}");
    }
}

#[test]
#[ignore = "requires the redstone-conductor oracle dump; regenerates and checks the committed table"]
fn committed_table_matches_dump() {
    let dump = parse_dump(DUMP);
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src/generated/redstone_conductor.rs");
    let generated = generate(&dump);
    if std::env::var_os("LODESTONE_REGEN").is_some() {
        std::fs::write(&path, generated).expect("write generated table");
        return;
    }
    assert_committed_bits_match_dump(&dump);
    let committed = std::fs::read_to_string(&path).expect("generated table is present");
    assert_eq!(generated, committed, "src/generated/redstone_conductor.rs is stale");
}
