//! Creative flight (issue #191): the dispatch suppressor, the speed
//! substitution, the `0.6` Y overwrite, and the `!flying` conjuncts.
//!
//! # Where the expected values come from
//!
//! **Every expectation in this file is hand-derived from the literals in
//! `.cache/mc/26.2/src`**, never by calling the crate's own helper to produce the
//! expected side. That distinction is load-bearing here for a specific reason:
//! this crate's golden traces are generated by `tests/gen_golden.py`, a Python
//! port sharing an author with the Rust — and that oracle carried the *same*
//! `getFlyingSpeed` defect the Rust did (`gen_golden.py:869`,
//! `speed = P.flying_speed`), so the two agreed with each other and both
//! disagreed with the jar. Agreement across ports sharing an author is weak
//! evidence; the Java literal is the authority.
//!
//! The four literals used below, each read directly from the jar:
//!
//! | value | source |
//! |---|---|
//! | `0.05F` (`Abilities.flyingSpeed` default) | `Abilities.java`'s `DEFAULT_FLYING_SPEED` |
//! | `0.025999999F` (airborne sprint) | `Player.java:1978` |
//! | `0.02F` (airborne walk) | `Player.java:1978`'s other arm |
//! | `0.6` (the Y overwrite) | `Player.java:1420` |
//!
//! # Anti-vacuity
//!
//! Each behavioural test carries a **negative control** in the same function: the
//! identical fixture with `flying = false`, asserted to differ. A test that only
//! ran the flying case would pass just as well if `flying` were ignored
//! altogether, which is the precondition species of vacuous test this crate's
//! other files guard against explicitly.
//!
//! The *world* species is guarded too, and it is the real hazard for a
//! server-gated feature: the fluid-suppression test needs a fixture whose water
//! genuinely reaches the player, or it proves nothing about the suppressor. The
//! `WaterColumn` fixture below is asserted to actually submerge a *non*-flying
//! player before the flying assertion is made.

use lodestone_physics::collision::CollisionView;
use lodestone_physics::geometry::Aabb;
use lodestone_physics::{
    MovementInput, PhysicsProfile, PlayerState, Pose, Vec3d, player_flying_speed, tick, tick_air,
};

/// `Abilities.DEFAULT_FLYING_SPEED` (`Abilities.java`).
const ABILITY_FLYING_SPEED: f32 = 0.05;
/// `Player.getFlyingSpeed()`'s non-flying sprinting arm (`Player.java:1978`).
const AIRBORNE_SPRINT: f32 = 0.025_999_999;
/// `Player.getFlyingSpeed()`'s non-flying walking arm (`Player.java:1978`).
const AIRBORNE_WALK: f32 = 0.02;

/// A flat floor at `y = 0` and nothing else.
struct FlatFloor;

impl CollisionView for FlatFloor {
    fn collision_boxes(&self, x: i32, y: i32, z: i32, out: &mut Vec<Aabb>) {
        if y == 0 {
            out.push(cell(x, z));
        }
    }
}

/// Open air with no floor at all — for the airborne cases, so `on_ground` cannot
/// accidentally become `true` and route through the grounded speed branch.
struct Void;

impl CollisionView for Void {
    fn collision_boxes(&self, _x: i32, _y: i32, _z: i32, _out: &mut Vec<Aabb>) {}
}

/// A deep water column over a floor, tall enough to submerge a standing player.
struct WaterColumn;

impl CollisionView for WaterColumn {
    fn collision_boxes(&self, x: i32, y: i32, z: i32, out: &mut Vec<Aabb>) {
        if y == 0 {
            out.push(cell(x, z));
        }
    }

    fn is_water(&self, _x: i32, y: i32, _z: i32) -> bool {
        (1..=20).contains(&y)
    }
}

/// A soul-sand-like slowing block under the player: `speed_factor` 0.4.
struct SlowFloor;

impl CollisionView for SlowFloor {
    fn collision_boxes(&self, x: i32, y: i32, z: i32, out: &mut Vec<Aabb>) {
        if y == 0 {
            out.push(cell(x, z));
        }
    }

    fn speed_factor(&self, _x: i32, y: i32, _z: i32) -> f32 {
        if y == 0 { 0.4 } else { 1.0 }
    }
}

/// A ladder column at the player's own block.
struct LadderShaft;

impl CollisionView for LadderShaft {
    fn collision_boxes(&self, _x: i32, _y: i32, _z: i32, _out: &mut Vec<Aabb>) {}

    fn is_climbable(&self, _x: i32, _y: i32, _z: i32) -> bool {
        true
    }
}

fn cell(x: i32, z: i32) -> Aabb {
    Aabb::new(
        f64::from(x),
        0.0,
        f64::from(z),
        f64::from(x) + 1.0,
        1.0,
        f64::from(z) + 1.0,
    )
}

fn forward() -> MovementInput {
    MovementInput {
        forward: 1.0,
        ..MovementInput::NONE
    }
}

/// An airborne player at `y = 10`, facing `yaw = 0` (so `getInputVector`'s
/// rotation is the identity and the whole acceleration lands on `+Z`).
fn airborne() -> PlayerState {
    PlayerState::at(Vec3d::new(0.5, 10.0, 0.5), 0.0)
}

// ---------------------------------------------------------------------------
// 1. The speed substitution — all four arms of Player.getFlyingSpeed()
// ---------------------------------------------------------------------------

#[test]
fn player_flying_speed_has_four_arms_not_one() {
    let profile = PhysicsProfile::mc_1_21();
    let mut s = airborne();

    // Not flying. **This pair is the pre-existing bug**: the airborne branch of
    // `getFrictionInfluencedSpeed` used to return a flat `profile.flying_speed`
    // with no sprint term at all, so the second assertion here failed by 30%
    // before #191 — with no creative flight involved anywhere.
    s.sprinting = false;
    assert_eq!(player_flying_speed(&s, &profile), AIRBORNE_WALK);
    s.sprinting = true;
    assert_eq!(
        player_flying_speed(&s, &profile),
        AIRBORNE_SPRINT,
        "Player.java:1978's sprinting arm — 0.025999999F, and it is not 0.026F"
    );

    // Flying: the ability speed, doubled while sprinting.
    s = s.with_flight(true, ABILITY_FLYING_SPEED);
    s.sprinting = false;
    assert_eq!(player_flying_speed(&s, &profile), ABILITY_FLYING_SPEED);
    s.sprinting = true;
    assert_eq!(player_flying_speed(&s, &profile), ABILITY_FLYING_SPEED * 2.0);

    // A server-set speed is honoured rather than the default being assumed.
    let s = airborne().with_flight(true, 0.123);
    assert_eq!(player_flying_speed(&s, &profile), 0.123);
}

#[test]
fn the_sprint_literal_is_not_0_026() {
    // `0.026F` and `0.025999999F` are different `f32`s, and `input_vector` is
    // linear in the value, so picking the tidier-looking constant is observable
    // in the reported position. Pinned as bits so a "cleanup" cannot silently
    // round it.
    assert_ne!(AIRBORNE_SPRINT.to_bits(), 0.026_f32.to_bits());
    assert_eq!(
        PhysicsProfile::mc_1_21().airborne_sprint_speed.to_bits(),
        AIRBORNE_SPRINT.to_bits()
    );
}

#[test]
fn flight_accelerates_two_and_a_half_times_faster_than_walking_airborne() {
    let profile = PhysicsProfile::mc_1_21();
    let world = Void;

    let run = |flying: bool| -> PlayerState {
        let mut s = airborne().with_flight(flying, ABILITY_FLYING_SPEED);
        tick_air(&mut s, forward(), &world, &profile);
        s
    };

    let walking = run(false);
    let flying = run(true);

    // NEGATIVE CONTROL: the two must differ, or this test cannot see `flying`.
    assert_ne!(
        walking.position.z, flying.position.z,
        "control: flight must change the airborne acceleration"
    );

    // Hand-derived, from the jar's formula rather than the crate's helpers.
    // At yaw 0 with a single forward axis, `modifyInputSpeedForSquareMovement`
    // leaves `zza = 1.0F * 0.98F` and `getInputVector` rotation is the identity,
    // so the first tick's Z displacement is `0.98F * speed` widened to f64.
    // `Entity.getInputVector` builds `new Vec3(xxa, 0, zza)` — widening the
    // `float` axes to `double` **first** — and only then scales by
    // `(double) speed`. So it is `f64::from(0.98F) * f64::from(speed)`, not
    // `f64::from(0.98F * speed)`; the two differ at ~3e-10, which is exactly the
    // kind of ULP the server's replay accumulates.
    let expect_z = |speed: f32| 0.5 + f64::from(0.98_f32) * f64::from(speed);
    assert_eq!(walking.position.z, expect_z(AIRBORNE_WALK));
    assert_eq!(flying.position.z, expect_z(ABILITY_FLYING_SPEED));
}

// ---------------------------------------------------------------------------
// 2. The Y overwrite
// ---------------------------------------------------------------------------

#[test]
fn flight_overwrites_y_with_the_pre_travel_value_times_0_6() {
    let profile = PhysicsProfile::mc_1_21();
    let world = Void;

    let mut s = airborne().with_flight(true, ABILITY_FLYING_SPEED);
    s.velocity = Vec3d::new(0.0, 0.5, 0.0);
    let pre_travel_y = s.velocity.y;
    tick(&mut s, MovementInput::NONE, &world, &profile);

    // The *pre*-travel Y times 0.6 — gravity's contribution during the tick is
    // discarded outright, not damped. `0.5 * 0.6 == 0.3`, and crucially **not**
    // `(0.5 - 0.08) * 0.98 * 0.6`, which is what "vertical damping applied after
    // gravity" would give.
    assert_eq!(s.velocity.y, pre_travel_y * 0.6);

    // What plain `travelInAir` would have left: gravity then vertical drag.
    let no_overwrite = (0.5 - f64::from(0.08_f32)) * f64::from(0.98_f32);
    // …and what "damp the post-travel Y by 0.6" — the issue body's reading —
    // would have produced. The overwrite *replaces*, so neither of these is it.
    let damped_after_gravity = no_overwrite * 0.6;
    assert_ne!(
        s.velocity.y, damped_after_gravity,
        "the 0.6 replaces the post-travel Y; it does not scale it"
    );
    assert_ne!(s.velocity.y, no_overwrite);

    // NEGATIVE CONTROL: not flying, the same tick keeps gravity and drag.
    let mut ground = airborne();
    ground.velocity = Vec3d::new(0.0, 0.5, 0.0);
    tick(&mut ground, MovementInput::NONE, &world, &profile);
    assert_ne!(
        ground.velocity.y,
        pre_travel_y * 0.6,
        "control: without flight the Y must come from gravity + drag"
    );
    assert_eq!(ground.velocity.y, no_overwrite);
}

#[test]
fn there_is_no_horizontal_drag_term_in_the_flight_branch() {
    // The issue body described the `0.6` as "horizontal drag and vertical
    // damping". It is Y-only. A horizontal term would show up as flight X/Z
    // decaying faster than `travelInAir`'s ordinary `0.91` air drag, so compare
    // the two directly with the same starting velocity and no input.
    let profile = PhysicsProfile::mc_1_21();
    let world = Void;

    let run = |flying: bool| -> PlayerState {
        let mut s = airborne().with_flight(flying, ABILITY_FLYING_SPEED);
        s.velocity = Vec3d::new(0.3, 0.0, 0.0);
        tick(&mut s, MovementInput::NONE, &world, &profile);
        s
    };

    assert_eq!(
        run(true).velocity.x,
        run(false).velocity.x,
        "flight must not touch the horizontal components at all"
    );
    // …and the shared value is `travelInAir`'s own drag, so neither path is
    // silently zeroing it.
    assert_eq!(run(true).velocity.x, 0.3 * f64::from(0.91_f32));
}

#[test]
fn a_hovering_flier_settles_to_exactly_zero_vertical_velocity() {
    // The capture point matters: `Player.travel` reads the Y *after* aiStep's
    // snap-to-zero prologue. Capturing before it would leave a residual
    // `1.8e-3 * 0.6^n` that decays but never reaches zero, invisible in position
    // and then visible as a ~0.001 offset the next time the player climbs.
    let profile = PhysicsProfile::mc_1_21();
    let world = Void;
    let mut s = airborne().with_flight(true, ABILITY_FLYING_SPEED);
    s.velocity = Vec3d::new(0.0, 0.0025, 0.0);
    // 0.0025 is inside the snap threshold (|y| < 0.003), so vanilla's captured
    // value is exactly 0.0 and the very first tick must land on 0.0.
    tick(&mut s, MovementInput::NONE, &world, &profile);
    assert_eq!(
        s.velocity.y, 0.0,
        "the pre-travel capture must read through snap_small_velocity"
    );
}

// ---------------------------------------------------------------------------
// 3. The dispatch suppressor — the strongest discriminator between the
//    "wrapper" shape and the (wrong) "fourth travel mode" shape
// ---------------------------------------------------------------------------

#[test]
fn a_flying_player_in_water_takes_the_air_path() {
    let profile = PhysicsProfile::mc_1_21();
    let world = WaterColumn;
    let submerged = Vec3d::new(0.5, 10.0, 0.5);

    // WORLD CONTROL, and the one that matters most: prove the fixture actually
    // puts water on the player before asserting anything about suppression. A
    // fixture whose water never reaches the box would make the suppression test
    // pass for the wrong reason — the *world* species of vacuous test, whose
    // flaw lives in the input data and is invisible in the test source.
    let mut swimmer = PlayerState::at(submerged, 0.0);
    tick(&mut swimmer, MovementInput::NONE, &world, &profile);
    assert!(
        swimmer.eye_in_water,
        "world control: the fixture must genuinely submerge a non-flying player"
    );
    // …and a non-flying player in water gets water's own vertical behaviour:
    // buoyancy, not `-0.08` gravity.
    assert!(
        swimmer.velocity.y > -0.08,
        "world control: the non-flying player must be taking the water branch"
    );

    let mut flier = PlayerState::at(submerged, 0.0).with_flight(true, ABILITY_FLYING_SPEED);
    tick(&mut flier, forward(), &world, &profile);

    // `Player.isAffectedByFluids()` is `!flying`, so `shouldTravelInFluid` is
    // false and this went through `travelInAir`: the horizontal input is scaled
    // by the *flight* speed with no `0.8` water slow-down anywhere.
    assert_eq!(
        flier.position.z,
        0.5 + f64::from(0.98_f32) * f64::from(ABILITY_FLYING_SPEED),
        "a flying player in water must move at flight speed through travelInAir"
    );

    // NEGATIVE CONTROL: the same input on the non-flying path goes much slower,
    // because `travelInWater`'s input speed is `0.02F` and its drag is `0.8`.
    let mut walker = PlayerState::at(submerged, 0.0);
    tick(&mut walker, forward(), &world, &profile);
    assert!(
        walker.position.z < flier.position.z,
        "control: the water path must be slower than the suppressed one"
    );

    // And the swim pose never engages: `Player.updateSwimming` forces false.
    let mut sprint_swimmer = PlayerState::at(submerged, 0.0).with_flight(true, ABILITY_FLYING_SPEED);
    sprint_swimmer.swimming = true;
    tick(
        &mut sprint_swimmer,
        MovementInput {
            forward: 1.0,
            sprint: true,
            ..MovementInput::NONE
        },
        &world,
        &profile,
    );
    assert!(
        !sprint_swimmer.swimming,
        "Player.updateSwimming (Player.java:1433) forces setSwimming(false) while flying"
    );
}

// ---------------------------------------------------------------------------
// 4. The !flying conjuncts, one test per site
// ---------------------------------------------------------------------------

#[test]
fn a_flying_player_never_jumps_from_the_ground() {
    // `LivingEntity.aiStep`'s whole jump block is gated on `isAffectedByFluids()`
    // (`LivingEntity.java:3089`) — `!abilities.flying` for a player. This is the
    // conjunct the issue's research comment did **not** list, and without it a
    // flier hovering at floor level would get `jumpFromGround`'s `0.42` on top of
    // the driver's `flyingSpeed * 3` climb impulse.
    let profile = PhysicsProfile::mc_1_21();
    let world = FlatFloor;
    let jump = MovementInput {
        jump: true,
        ..MovementInput::NONE
    };

    // `tick`, not `tick_air`: the `0.6` Y overwrite is `Player.travel`, one level
    // *above* `travelInAir`, so only the full player tick shows the flier's
    // resulting Y. (Through `tick_air` alone a flier still gets gravity, which is
    // correct and simply not the thing under test here.)
    let run = |flying: bool| -> PlayerState {
        let mut s = PlayerState::at(Vec3d::new(0.5, 1.0, 0.5), 0.0).with_flight(flying, 0.05);
        s.on_ground = true;
        tick(&mut s, jump, &world, &profile);
        s
    };

    // NEGATIVE CONTROL first: a non-flying player *does* jump, so this fixture
    // can see the difference.
    let walker = run(false);
    assert!(
        walker.velocity.y > 0.3,
        "control: a grounded non-flying player must jump (got {})",
        walker.velocity.y
    );
    assert_eq!(walker.no_jump_delay, 10);

    let flier = run(true);
    assert_eq!(
        flier.velocity.y, 0.0,
        "a flying player must not jump; the Y overwrite of a 0.0 pre-travel Y is 0.0"
    );
    assert_eq!(
        flier.no_jump_delay, 0,
        "the else arm of the jump block clears noJumpDelay"
    );
}

#[test]
fn flight_suppresses_the_block_speed_factor() {
    // `Player.getBlockSpeedFactor()` (`Player.java:1855`) is
    // `!flying && !isFallFlying() ? super : 1.0F`.
    let profile = PhysicsProfile::mc_1_21();
    let world = SlowFloor;

    let run = |flying: bool, fall_flying: bool| -> f64 {
        let mut s = PlayerState::at(Vec3d::new(0.5, 1.0, 0.5), 0.0).with_flight(flying, 0.05);
        s.on_ground = true;
        s.fall_flying = fall_flying;
        s.velocity = Vec3d::new(0.2, 0.0, 0.0);
        tick_air(&mut s, MovementInput::NONE, &world, &profile);
        s.velocity.x
    };

    let slowed = run(false, false);
    let flying = run(true, false);
    // NEGATIVE CONTROL: the fixture must actually slow a plain walker, or the
    // suppression assertion is measuring nothing.
    assert!(
        slowed.abs() < flying.abs(),
        "control: SlowFloor must slow a non-flying, non-gliding player"
    );
    // The elytra half of the same expression, which was wrong here before #191.
    assert_eq!(
        run(false, true),
        flying,
        "isFallFlying() suppresses it too — the whole predicate, not half of it"
    );
}

#[test]
fn flight_detaches_the_player_from_ladders() {
    // `Player.onClimbable()` → `false` while flying (`Player.java:2025`).
    let profile = PhysicsProfile::mc_1_21();
    let world = LadderShaft;

    let run = |flying: bool| -> PlayerState {
        let mut s = airborne().with_flight(flying, ABILITY_FLYING_SPEED);
        s.velocity = Vec3d::new(0.0, -0.5, 0.0);
        s.fall_distance = 3.0;
        tick(&mut s, MovementInput::NONE, &world, &profile);
        s
    };

    // NEGATIVE CONTROL: a non-flying player on a ladder has the descent clamped
    // to `-0.15F`, which is the ladder-specific observable. (Its `fall_distance`
    // is the *clamped* descent rather than zero, for the pre-travel-reset reason
    // `flight_resets_fall_distance_every_tick` documents — the ladder reset also
    // runs before the move.)
    let climber = run(false);
    // The clamp is applied **pre-move**; gravity and vertical drag then run after
    // it, so the tick ends at `(-0.15F - 0.08F) * 0.98F` rather than at the clamp
    // bound itself. Writing `-0.15` here would be asserting the wrong stage of the
    // same tick.
    assert_eq!(
        climber.velocity.y,
        (-f64::from(0.15_f32) - f64::from(0.08_f32)) * f64::from(0.98_f32),
        "control: the ladder must clamp the descent to -0.15F before gravity"
    );
    assert_eq!(
        climber.fall_distance,
        f64::from(0.15_f32),
        "control: reset pre-move, then the clamped descent accumulates"
    );

    let flier = run(true);
    assert_eq!(
        flier.velocity.y,
        -0.5 * 0.6,
        "a flier passes the ladder untouched; only the 0.6 Y overwrite applies"
    );
}

#[test]
fn shift_while_flying_is_descend_not_crouch() {
    // `Player.getDesiredPose()` (`Player.java:369`):
    // `isShiftKeyDown() && !abilities.flying ? CROUCHING : STANDING`.
    let profile = PhysicsProfile::mc_1_21();
    let world = Void;
    let sneak = MovementInput {
        sneak: true,
        ..MovementInput::NONE
    };

    let mut walker = airborne();
    tick(&mut walker, sneak, &world, &profile);
    // NEGATIVE CONTROL.
    assert_eq!(
        walker.pose,
        Pose::Crouching,
        "control: shift must crouch a non-flying player"
    );

    let mut flier = airborne().with_flight(true, ABILITY_FLYING_SPEED);
    tick(&mut flier, sneak, &world, &profile);
    assert_eq!(flier.pose, Pose::Standing);
}

#[test]
fn flight_resets_fall_distance_every_tick() {
    // `Player.aiStep`: `if (abilities.flying && !isPassenger()) resetFallDistance();`
    // (`Player.java:449-451`) — before `super.aiStep()`, so before travel.
    let profile = PhysicsProfile::mc_1_21();
    let world = Void;

    let run = |flying: bool| -> f64 {
        let mut s = airborne().with_flight(flying, ABILITY_FLYING_SPEED);
        s.velocity = Vec3d::new(0.0, -0.6, 0.0);
        s.fall_distance = 12.0;
        tick(&mut s, MovementInput::NONE, &world, &profile);
        s.fall_distance
    };

    // **The reset is pre-travel, not post-tick.** `Player.aiStep` resets before
    // `super.aiStep()`, and `Entity.move`'s own `checkFallDamage` then accumulates
    // *this* tick's descent — so a flier ends the tick holding one tick's worth,
    // never zero. What the reset buys is that it cannot **accumulate across**
    // ticks, which is the whole point (no fall damage on landing from flight).
    //
    // Asserting `== 0.0` here would have been wrong about vanilla in a way that
    // looks more correct, which is why the exact value is pinned instead.
    let one_tick_descent = f64::from(0.6_f32);
    assert_eq!(run(true), one_tick_descent);
    // NEGATIVE CONTROL: a falling non-flier keeps the 12.0 it arrived with.
    assert_eq!(
        run(false),
        12.0 + one_tick_descent,
        "control: a non-flying faller must keep accumulating fall distance"
    );

    // …and the multi-tick claim, which is what actually matters: a flier's fall
    // distance is bounded, a faller's is not.
    let mut flier = airborne().with_flight(true, ABILITY_FLYING_SPEED);
    flier.velocity = Vec3d::new(0.0, -0.6, 0.0);
    let mut faller = airborne();
    faller.velocity = Vec3d::new(0.0, -0.6, 0.0);
    for _ in 0..20 {
        tick(&mut flier, MovementInput::NONE, &world, &profile);
        tick(&mut faller, MovementInput::NONE, &world, &profile);
    }
    assert!(
        flier.fall_distance < 1.0,
        "20 ticks of flight must not accumulate fall distance (got {})",
        flier.fall_distance
    );
    assert!(
        faller.fall_distance > 10.0,
        "control: 20 ticks of falling must (got {})",
        faller.fall_distance
    );
}

#[test]
fn a_sneaking_flier_can_leave_a_ledge() {
    // `Player.maybeBackOffFromEdge`'s first conjunct is `!this.abilities.flying`
    // (`Player.java:882`). Before #191 that conjunct was documented as "satisfied
    // by construction, this crate does not model creative flight" — an argument
    // that has now expired, so the gate has to be real.
    //
    // Fixture shape is borrowed from `tests/edge_back_off.rs`, which is the file
    // that proves this rule works at all: **one** tick, an explicit horizontal
    // velocity, `delta.y == 0.0`, `on_ground = true`. A multi-tick walk does not
    // work here — `move_entity` recomputes `on_ground` from the tick's own
    // vertical collision, so the first tick (which moves `y` by zero) flips it to
    // `false` and the player then jitters between supported and falling, taking
    // the airborne speed branch. That fixture measured nothing and its control
    // correctly refused to pass.
    struct Ledge;
    impl CollisionView for Ledge {
        fn collision_boxes(&self, x: i32, y: i32, z: i32, out: &mut Vec<Aabb>) {
            // Floor only at x == 0: everything at x >= 1 is open air.
            if y == 0 && x == 0 {
                out.push(cell(x, z));
            }
        }
    }

    let profile = PhysicsProfile::mc_1_21();
    let world = Ledge;
    let sneak = MovementInput {
        sneak: true,
        ..MovementInput::NONE
    };

    let run = |flying: bool| -> f64 {
        let mut s = PlayerState::at(Vec3d::new(0.5, 1.0, 0.5), 0.0).with_flight(flying, 0.05);
        s.on_ground = true;
        s.velocity = Vec3d::new(0.8, 0.0, 0.0);
        tick_air(&mut s, sneak, &world, &profile);
        s.position.x
    };

    let off_the_edge = 0.5 + 0.8;
    let held_back = run(false);
    let flew_off = run(true);

    // NEGATIVE CONTROL: the back-off must actually be holding the sneaking walker,
    // or "the flier went further" measures nothing.
    assert_ne!(
        held_back, off_the_edge,
        "control: a sneaking non-flier must be held on the ledge"
    );
    assert!(
        held_back < off_the_edge,
        "control: the back-off only ever shortens the move (got {held_back})"
    );

    // …and the flier is exempt, taking the whole 0.8.
    assert_eq!(
        flew_off, off_the_edge,
        "a flying player is exempt from the edge back-off"
    );
}

#[test]
fn flight_is_not_grabbed_by_a_cobweb() {
    // `Player.makeStuckInBlock` skips `super` while flying (`Player.java:1514`).
    struct Web;
    impl CollisionView for Web {
        fn collision_boxes(&self, _x: i32, _y: i32, _z: i32, _out: &mut Vec<Aabb>) {}

        fn stuck_multiplier(&self, _x: i32, _y: i32, _z: i32) -> Option<Vec3d> {
            Some(Vec3d::new(0.25, 0.05, 0.25))
        }
    }

    let profile = PhysicsProfile::mc_1_21();
    let world = Web;

    let run = |flying: bool| -> Vec3d {
        let mut s = airborne().with_flight(flying, ABILITY_FLYING_SPEED);
        tick(&mut s, MovementInput::NONE, &world, &profile);
        s.stuck_speed_multiplier
    };

    // NEGATIVE CONTROL: the fixture must genuinely grab a non-flier.
    assert_ne!(
        run(false),
        Vec3d::ZERO,
        "control: the web must record a multiplier for a non-flying player"
    );
    assert_eq!(run(true), Vec3d::ZERO);
}

#[test]
fn flight_ignores_a_bubble_column() {
    // Both `Player` overrides skip the impulse entirely (`Player.java:309-321`).
    struct Column;
    impl CollisionView for Column {
        fn collision_boxes(&self, _x: i32, _y: i32, _z: i32, _out: &mut Vec<Aabb>) {}

        fn bubble_column(&self, _x: i32, _y: i32, _z: i32) -> Option<bool> {
            Some(false) // soul sand: push up
        }
        fn is_water(&self, _x: i32, _y: i32, _z: i32) -> bool {
            true
        }
    }

    let profile = PhysicsProfile::mc_1_21();
    let world = Column;

    let run = |flying: bool| -> f64 {
        let mut s = airborne().with_flight(flying, ABILITY_FLYING_SPEED);
        tick(&mut s, MovementInput::NONE, &world, &profile);
        s.velocity.y
    };

    // NEGATIVE CONTROL: the column must genuinely lift a non-flier.
    assert!(
        run(false) > 0.0,
        "control: the column must push a non-flying player up"
    );
    // A flier's Y is purely the `0.6` overwrite of a zero pre-travel Y.
    assert_eq!(run(true), 0.0);
}

// ---------------------------------------------------------------------------
// 5. What is deliberately NOT modelled
// ---------------------------------------------------------------------------

#[test]
fn spectator_noclip_is_not_modelled_and_this_pins_that() {
    // `Player.tick` sets `this.noPhysics = this.isSpectator()` (`Player.java:233`),
    // which makes `Entity.move` skip collision resolution entirely. This crate
    // models **no** part of that: `flying` is creative flight, which *collides*.
    //
    // Asserting the gap explicitly rather than half-modelling it is the ruling
    // `docs/edge-back-off.md` records for its own sibling case — a partial model
    // feeding a position-affecting path is worse than an honest stand-in, because
    // it looks finished. When spectator lands, this test should fail and be
    // replaced.
    let profile = PhysicsProfile::mc_1_21();
    let world = FlatFloor;
    let mut s = PlayerState::at(Vec3d::new(0.5, 5.0, 0.5), 0.0).with_flight(true, 0.05);
    s.velocity = Vec3d::new(0.0, -2.0, 0.0);
    for _ in 0..10 {
        tick(&mut s, MovementInput::NONE, &world, &profile);
    }
    assert!(
        s.position.y >= 1.0,
        "creative flight collides with the floor; there is no noclip here (y = {})",
        s.position.y
    );
}

#[test]
fn flight_does_not_change_the_grounded_walk_speed() {
    // The substitution is airborne-only: `getFrictionInfluencedSpeed` only calls
    // `getFlyingSpeed()` in its `!onGround()` branch. A flying player standing on
    // the ground (possible for exactly one tick, before the driver's climb
    // impulse lifts them) still walks at `getSpeed()`.
    let profile = PhysicsProfile::mc_1_21();
    let world = FlatFloor;

    let run = |flying: bool| -> f64 {
        let mut s = PlayerState::at(Vec3d::new(0.5, 1.0, 0.5), 0.0).with_flight(flying, 0.05);
        s.on_ground = true;
        tick_air(&mut s, forward(), &world, &profile);
        s.position.z
    };

    assert_eq!(
        run(true),
        run(false),
        "the speed substitution is gated on !onGround(), so grounded is unchanged"
    );
}
