//! Reads real `.mca` region files this repo did not write — the primary
//! evidence gate for issue #298's own rule: `decode(encode(x)) == x` against
//! our own writer proves nothing, so at least one side of every check here
//! must be bytes this crate never produced.
//!
//! # What's actually available
//!
//! `.cache/mc/{1.8.9,1.12.2,1.16.5}/world/region/*.mca` — region files
//! genuinely written by real dedicated servers of those versions (from this
//! repo's other live-oracle-driven test suites, e.g. the legacy protocol
//! families' parity gates). The Anvil **container** format — the header,
//! sector addressing, chunk framing, compression-scheme byte — has been
//! byte-identical across every one of these versions and 26.2 alike (it
//! predates all of them, back to 1.2's introduction of Anvil); only the
//! chunk NBT *schema* differs, and this crate deliberately does not parse
//! that (see the crate doc). Every "expected" value in these three tests
//! was read out of these exact files with an independent Python script
//! (`struct`/`zlib`/`gzip` from the stdlib, no code from this crate) — see
//! each test's comment for the byte offsets that produced it.
//!
//! `tests/region_real_world_26_2.rs` covers the same evidence bar for a
//! **freshly generated 26.2** region file, produced from this repo's own
//! `creative` oracle over RCON (not checked in here, since booting the
//! oracle wasn't needed for these three tests) — see that file's doc.
//!
//! Every test below is `#[ignore]`d, per this repo's rule against a test
//! whose missing precondition silently downgrades to a pass rather than a
//! failure — run explicitly with `cargo test -p lodestone-anvil --test
//! region_real_world -- --ignored`.

use lodestone_anvil::region::RegionFile;
use lodestone_core::Nbt;
use std::path::{Path, PathBuf};

fn cache_dir(relative: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../.cache/mc")
        .join(relative)
}

fn read_region(relative: &str) -> RegionFile {
    let path = cache_dir(relative);
    RegionFile::read_from_file(&path).unwrap_or_else(|e| {
        panic!(
            "no real region file at {} ({e}); this repo's .cache/mc/<version>/world is not \
             checked in and must be regenerated by that version's live oracle first",
            path.display()
        )
    })
}

fn find_nbt_field<'a>(nbt: &'a Nbt, name: &str) -> Option<&'a Nbt> {
    match nbt {
        Nbt::Compound(fields) => fields.iter().find(|(n, _)| n == name).map(|(_, v)| v),
        _ => None,
    }
}

fn assert_chunk_position(nbt: &Nbt, expected_x: i32, expected_z: i32) {
    // Every version in this test wraps per-chunk fields in a top-level
    // "Level" compound (pre-flattening-removal schema; 26.2's own
    // `SerializableChunkData` is different and out of scope here — see the
    // module doc). `xPos`/`zPos` are the one pair of fields stable across
    // all of them and independent of any block-encoding scheme, which is
    // why they're the check: proof this crate decoded a *real, specific*
    // chunk's tree, not just "some NBT that happened to parse".
    let level = find_nbt_field(nbt, "Level").expect("chunk NBT has a top-level \"Level\" compound");
    let x_pos = find_nbt_field(level, "xPos").expect("Level has xPos");
    let z_pos = find_nbt_field(level, "zPos").expect("Level has zPos");
    assert_eq!(*x_pos, Nbt::Int(expected_x), "xPos");
    assert_eq!(*z_pos, Nbt::Int(expected_z), "zPos");
}

fn decode_chunk(region: &RegionFile, local_x: u8, local_z: u8) -> Nbt {
    let raw = region
        .read_chunk_nbt_bytes(local_x, local_z)
        .expect("reads without a corrupt-input error")
        .unwrap_or_else(|| panic!("chunk ({local_x}, {local_z}) unexpectedly absent"));
    let mut reader = lodestone_core::Reader::new(&raw);
    let (_, nbt) = lodestone_core::read_named_nbt(&mut reader).expect("decodes as named NBT");
    nbt
}

#[test]
#[ignore = "requires .cache/mc/1.16.5/world/region/r.0.0.mca, a real file this crate did not write"]
fn reads_a_real_1_16_5_region_file() {
    // Independently measured (Python `struct`/`zlib`, not this crate):
    // chunk local index 0 (region-local x=0, z=0 — chunk (0, 0), since this
    // is region r.0.0) has location entry sector_number=2, sector_count=1,
    // and its 5-byte chunk header declares length=723 (so a 722-byte zlib
    // payload; scheme byte 2 confirmed by the raw bytes at that offset
    // starting 0x78 0x9c, the standard zlib default-level header).
    let region = read_region("1.16.5/world/region/r.0.0.mca");

    let location = region
        .locate_chunk(0, 0)
        .expect("in range")
        .expect("chunk (0,0) is present in this real file");
    assert_eq!(location.sector_number, 2, "measured via a Python struct.unpack of the header");
    assert_eq!(location.sector_count, 1);

    let nbt = decode_chunk(&region, 0, 0);
    assert_chunk_position(&nbt, 0, 0);
}

#[test]
#[ignore = "requires .cache/mc/1.12.2/world/region/r.0.-1.mca, a real file this crate did not write"]
fn reads_a_real_1_12_2_region_file() {
    // Region r.0.-1 covers chunk Z in [-32, -1]; independently measured:
    // local index 8 (x=8, z=0 within the region) is the first present
    // chunk, at sector_number=2, declared length 268 (a 267-byte zlib
    // payload). Its absolute chunk coordinate is (8, 0*32 + (-32)) =
    // (8, -32) — regionZ=-1 times 32 chunks/region.
    let region = read_region("1.12.2/world/region/r.0.-1.mca");

    let location = region
        .locate_chunk(8, 0)
        .expect("in range")
        .expect("chunk present");
    assert_eq!(location.sector_number, 2);
    assert_eq!(location.sector_count, 1);

    let nbt = decode_chunk(&region, 8, 0);
    assert_chunk_position(&nbt, 8, -32);
}

#[test]
#[ignore = "requires .cache/mc/1.8.9/world/region/r.0.0.mca, a real file this crate did not write"]
fn reads_a_real_1_8_9_region_file() {
    // The oldest file checked here, and a useful contrast with the other
    // two: independently measured, local index 0 (chunk (0,0)) sits at
    // sector_number=115 near the end of a 116-sector file, not sector 2 —
    // this world's chunks were resaved over a session in an order that
    // doesn't match ascending local index, unlike this crate's own writer
    // (`region.rs`'s `build_region`, which always packs first-fit from
    // sector 2 in call order). That's expected: nothing requires vanilla's
    // *placement* to match ours, only that this reader recovers the right
    // chunk regardless of where in the file it landed.
    let region = read_region("1.8.9/world/region/r.0.0.mca");

    let location = region
        .locate_chunk(0, 0)
        .expect("in range")
        .expect("chunk present");
    assert_eq!(location.sector_number, 115, "measured via a Python struct.unpack of the header");
    assert_eq!(location.sector_count, 1);

    let nbt = decode_chunk(&region, 0, 0);
    assert_chunk_position(&nbt, 0, 0);
}

#[test]
#[ignore = "requires .cache/mc/1.16.5/world/region/r.0.0.mca, a real file this crate did not write"]
fn absent_chunk_in_a_real_file_reads_as_none() {
    // Corrupt/absent-input control using a real file rather than a
    // synthetic one: chunk local (31, 31) is far outside this small
    // 9-chunk test world's generated area, so its location entry is
    // legitimately zero. This must read as `Ok(None)`, not an error —
    // proving the "absent, not corrupt" distinction holds against a real
    // file's actual all-zero table entries, not just our own constructed
    // ones (see `tests/region_container.rs` for the synthetic version of
    // this same control).
    let region = read_region("1.16.5/world/region/r.0.0.mca");
    assert_eq!(
        region.read_chunk_nbt_bytes(31, 31).expect("reads cleanly"),
        None
    );
}
