//! The era's entity-type id->name table: hermetic checks over the committed
//! table, plus an `#[ignore]`d drift guard that regenerates it from the jar's
//! own registry report and asserts byte-for-byte equality.
//!
//! # One protocol, one dump
//!
//! The registry is dense, so any insertion renumbers everything after it. That
//! is what forces one table per protocol in the multi-version eras. This era
//! serves a single protocol, so the question does not arise — but the dump is
//! still pinned by content hash so a different version's dump swapped in under
//! the same filename fails loudly.
//!
//! The dump is derived from the output of the jar's own data generator in its
//! reports mode, run against the real `.cache/mc/1.21.11/server.jar` — an
//! authority, not a community dataset. The full report is several megabytes of
//! registries this crate has no use for, so the committed file is a **filtered
//! extract**: three registries (`minecraft:entity_type`,
//! `minecraft:data_component_type`, `minecraft:block_entity_type`), copied
//! verbatim and re-serialised with sorted keys. Every `protocol_id` and every
//! identifier is the generator's own, so there is no casing or prefixing
//! judgement anywhere in this file.
//!
//! # This registry is not alphabetical
//!
//! It looks alphabetical at a glance and is not. Its order is the registry's
//! own insertion order, which puts the two types with no summon form last, and
//! which also disagrees with a plain string sort in the middle — potion
//! variants sit where their shared prefix does, `enderman` precedes
//! `ender_dragon`, and `snowball` precedes `snow_golem`. Anything that
//! re-derives an id by sorting the names is wrong by a variable offset, which
//! is worse than being wrong by a constant one, so
//! [`the_registry_order_is_not_plain_alphabetical`] pins several of the
//! inversions by id.
//!
//! Regenerate the committed table after a data bump with:
//!
//! ```text
//! LODESTONE_REGEN=1 cargo test -p lodestone-v1-21-11 --test entity_types \
//!     committed -- --ignored --nocapture
//! ```

use std::fmt::Write as _;
use std::path::PathBuf;

use lodestone_v1_21_11::PROTOCOL_1_21_11;
use lodestone_v1_21_11::entity_types;

/// The 1.21.11 jar's registry extract — the source the committed table is
/// rendered from.
const DUMP: &str = include_str!("support/registries_1_21_11_jar.json");
/// That dump's own filename, for assertion messages.
const DUMP_FILE: &str = "registries_1_21_11_jar.json";

/// Path under `src/generated/` the rendered table is committed at.
const COMMITTED: &str = "src/generated/entity_types.rs";

/// Number of entity types in this era's registry, counted from the dump.
const ENTITY_TYPES: usize = 157;

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Parses `minecraft:entity_type` out of a registry report into a sorted
/// `(id, identifier)` table, asserting the ids are dense from zero.
fn parse_registry_entities(doc: &str) -> Vec<(i32, String)> {
    let value: serde_json::Value = serde_json::from_str(doc).expect("registry report parses");
    let entries = value["minecraft:entity_type"]["entries"]
        .as_object()
        .expect("the report carries minecraft:entity_type entries");
    let mut pairs: Vec<(i32, String)> = entries
        .iter()
        .map(|(name, entry)| {
            let id = i32::try_from(
                entry["protocol_id"]
                    .as_i64()
                    .expect("entry has an integer protocol_id"),
            )
            .expect("protocol_id fits i32");
            (id, name.clone())
        })
        .collect();
    pairs.sort_by_key(|(id, _)| *id);
    for (index, (id, _)) in pairs.iter().enumerate() {
        assert_eq!(
            usize::try_from(*id).expect("id is non-negative"),
            index,
            "entity_type protocol ids are not dense from 0"
        );
    }
    pairs
}

/// Renders the committed table source from a parsed dump.
fn generate(pairs: &[(i32, String)]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo test -p lodestone-v1-21-11 --test entity_types -- --ignored`\n\
         // from tests/support/registries_1_21_11_jar.json (protocol 774 / Minecraft\n\
         // 1.21.11). DO NOT EDIT BY HAND.\n\
         // Regenerate with LODESTONE_REGEN=1 (see the test module docs).\n",
    );
    out.push_str(
        "//! Generated entity-type id->name table for protocol 774\n\
         //! (Minecraft 1.21.11).\n//!\n\
         //! Maps the unified numeric entity-type id space to canonical\n\
         //! `minecraft:*` identifiers. Consumed by [`crate::entity_types`].\n\n",
    );
    let _ = writeln!(out, "/// Number of entity_types type entries.");
    let _ = writeln!(
        out,
        "pub const ENTITY_TYPE_COUNT: usize = {};\n",
        pairs.len()
    );
    out.push_str("/// `(type id, canonical identifier)` pairs, sorted by id for binary search.\n");
    let _ = writeln!(
        out,
        "pub static ENTITY_TYPES: [(i32, &str); {}] = [",
        pairs.len()
    );
    for (id, name) in pairs {
        let _ = writeln!(out, "    ({id}, \"{name}\"),");
    }
    out.push_str("];\n");
    out
}

/// The committed dump is the one the jar produces, by shape and by content.
#[test]
fn the_committed_dump_is_the_one_the_jar_produces() {
    let pairs = parse_registry_entities(DUMP);
    assert_eq!(
        pairs.len(),
        ENTITY_TYPES,
        "1.21.11's entity registry holds 157 types"
    );

    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in DUMP.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    assert_eq!(
        hash, 0x298d_d0b5_505a_4145,
        "tests/support/{DUMP_FILE} is not the dump this table was generated from"
    );
}

/// The committed table is exactly what the dump renders to.
#[test]
#[ignore = "regenerates a committed table; run with --ignored"]
fn committed_table_matches_dump() {
    let pairs = parse_registry_entities(DUMP);
    let rendered = generate(&pairs);
    let path = manifest_dir().join(COMMITTED);
    if std::env::var_os("LODESTONE_REGEN").is_some() {
        std::fs::write(&path, &rendered).expect("write generated table");
        println!("regenerated {}", path.display());
        return;
    }
    let committed = std::fs::read_to_string(&path).expect("committed table exists");
    assert_eq!(
        committed, rendered,
        "{COMMITTED} has drifted from its dump; regenerate with LODESTONE_REGEN=1"
    );
}

/// The protocol resolves through `table_for`, and the generated file's two
/// halves agree.
#[test]
fn the_protocol_resolves_a_self_consistent_table() {
    let table = entity_types::table_for(PROTOCOL_1_21_11);
    assert_eq!(
        table.len(),
        table.declared_len(),
        "generated len/count disagree"
    );
    assert!(!table.is_empty());
    assert_eq!(table.len(), ENTITY_TYPES);
}

/// Spot values, each read out of the committed dump rather than out of the
/// table under test: several named types, the last entry, and one past it.
#[test]
fn named_ids_match_the_jar_dump() {
    let pairs = parse_registry_entities(DUMP);
    let table = entity_types::table_for(PROTOCOL_1_21_11);
    for probe in [
        "minecraft:copper_golem",
        "minecraft:creaking",
        "minecraft:happy_ghast",
        "minecraft:armadillo",
        "minecraft:player",
        "minecraft:zombie",
    ] {
        let Some((id, _)) = pairs.iter().find(|(_, name)| name == probe) else {
            panic!("{probe} is absent from the committed dump");
        };
        assert_eq!(
            table.entity_type_name(*id),
            Some(probe),
            "id {id} should be {probe}"
        );
    }
    let (last_id, last_name) = pairs.last().expect("registry is non-empty");
    assert_eq!(table.entity_type_name(*last_id), Some(last_name.as_str()));
    assert_eq!(
        table.entity_type_name(i32::try_from(pairs.len()).expect("fits")),
        None,
        "one past the end names no entity"
    );
}

/// A player carries no dedicated spawn packet, so the constant the crate
/// exposes for one has to be a real registry entry rather than a spelling.
#[test]
fn the_player_constant_is_a_real_registry_entry() {
    let pairs = parse_registry_entities(DUMP);
    assert!(
        pairs.iter().any(|(_, name)| name == entity_types::PLAYER),
        "{} is absent from the committed dump",
        entity_types::PLAYER
    );
}

/// The registry is not in plain alphabetical order, so nothing may re-derive
/// an id by sorting names.
///
/// Every fact here is read out of the dump. The inversions are named
/// individually rather than counted, because a count would pass under a
/// *different* set of inversions and this table's whole value is that each id
/// is the one the wire uses.
#[test]
fn the_registry_order_is_not_plain_alphabetical() {
    let pairs = parse_registry_entities(DUMP);
    let names: Vec<&str> = pairs.iter().map(|(_, name)| name.as_str()).collect();

    let mut sorted = names.clone();
    sorted.sort_unstable();
    assert_ne!(
        names, sorted,
        "if the registry were plain alphabetical this test would assert nothing"
    );

    let id_of = |probe: &str| {
        names
            .iter()
            .position(|name| *name == probe)
            .unwrap_or_else(|| panic!("{probe} is absent from the committed dump"))
    };

    // Four inversions, in four different parts of the registry.
    assert!(
        id_of("minecraft:copper_golem") < id_of("minecraft:command_block_minecart"),
        "a string sort would put the minecart first"
    );
    assert!(
        id_of("minecraft:enderman") < id_of("minecraft:ender_dragon"),
        "a string sort would put the underscore-separated names first"
    );
    assert!(
        id_of("minecraft:snowball") < id_of("minecraft:snow_golem"),
        "a string sort would put the golem first"
    );
    assert!(
        id_of("minecraft:splash_potion") < id_of("minecraft:pufferfish"),
        "a string sort would put the potion after every p-name"
    );

    // And the two types with no summon form sit at the very end.
    assert_eq!(
        &names[names.len() - 2..],
        &["minecraft:player", "minecraft:fishing_bobber"],
        "the two types with no summon form sit at the end"
    );
    assert!(
        id_of("minecraft:player") > id_of("minecraft:zombified_piglin"),
        "a string sort would put the player two thirds of the way up"
    );
}

/// This era's additions are what separate this table from the 1.20.6 era's, so
/// their presence is the cheapest proof the right dump was used — and the ids
/// below them having moved is the proof the two tables are not
/// interchangeable.
#[test]
fn the_era_additions_are_present_and_the_ids_below_have_moved() {
    let table = entity_types::table_for(PROTOCOL_1_21_11);
    let names: Vec<&str> = (0..i32::try_from(table.len()).expect("fits"))
        .filter_map(|id| table.entity_type_name(id))
        .collect();
    for added in [
        "minecraft:copper_golem",
        "minecraft:creaking",
        "minecraft:happy_ghast",
        "minecraft:acacia_boat",
        "minecraft:acacia_chest_boat",
    ] {
        assert!(
            names.contains(&added),
            "{added} missing from the 1.21.11 registry"
        );
    }

    // The single `boat` entry of the eras below became one per wood type, and
    // `acacia_boat` sorts first, so *every* id moved: even id 0 names a
    // different entity than it does one era down. That is why a table
    // inherited from there would misroute every spawn rather than a few.
    let pairs = parse_registry_entities(DUMP);
    assert_eq!(
        pairs
            .iter()
            .take(3)
            .map(|(id, name)| (*id, name.as_str()))
            .collect::<Vec<_>>(),
        vec![
            (0, "minecraft:acacia_boat"),
            (1, "minecraft:acacia_chest_boat"),
            (2, "minecraft:allay"),
        ],
        "the per-wood boat split moves the whole id space, starting at 0"
    );
}
