#!/usr/bin/env python3
"""Write crates/lodestone-assets/tests/fixtures/keyframe-samples.txt.

An evaluator for the reference animation definitions that shares nothing with the
Rust sampler or with `gen-keyframes.py`'s parser: it scans the definition sources
line by line, keeps authored values in degrees / authored units, and samples in
double precision, converting to the pose units only at the end. The Rust test
`keyframe_samples` compares its own sampling of the generated data against this
file within a small tolerance.

Each line is `anim channel_index bone target millis weight x y z`. `weight` is the
walk-style blend factor (1 for state animations).

    python3 scripts/keyframe-oracle.py
"""
import importlib.util
import math
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
VERSION = (ROOT / "mc-version").read_text().strip()
DEFS = ROOT / ".cache" / "mc" / VERSION / "client-src/net/minecraft/client/animation/definitions"
OUT = ROOT / "crates/lodestone-assets/tests/fixtures/keyframe-samples.txt"

# Only the (file, constant) -> variant table is taken from the generator.
spec = importlib.util.spec_from_file_location("gen", ROOT / "scripts/gen-keyframes.py")
src = (ROOT / "scripts/gen-keyframes.py").read_text()
table = re.search(r"WANTED = \[(.*?)\n\]", src, re.S).group(1)
WANTED = re.findall(r'\("(\w+)", "(\w+)", "(\w+)"\)', table)

TIMES_MS = [0, 37, 210, 333, 750, 1000, 2599, 7999]
# A walk-style half weight is checked at one time.
HALF_WEIGHT_MS = 333


def read_definitions(path):
    """{constant: (length, looping, [(bone, target, [(t, kind, (a, b, c), interp)])])}"""
    out = {}
    cur = None
    bone = target = None
    for raw in path.read_text().splitlines():
        line = raw.strip()
        m = re.search(r"AnimationDefinition (\w+) = AnimationDefinition\.Builder\.withLength\(([\d.]+)F\)", line)
        if m:
            cur = [float(m.group(2)), False, []]
            out[m.group(1)] = cur
            continue
        if cur is None:
            continue
        if line == ".looping()":
            cur[1] = True
        m = re.match(r'^"([a-z_0-9]+)",$', line)
        if m:
            bone = m.group(1)
        m = re.search(r"AnimationChannel\.Targets\.(POSITION|ROTATION|SCALE)", line)
        if m:
            target = m.group(1)
            cur[2].append((bone, target, []))
        m = re.search(
            r"new Keyframe\(([-\d.]+)F, KeyframeAnimations\.(\w+)\(([^)]*)\), AnimationChannel\.Interpolations\.(\w+)\)", line
        )
        if m:
            nums = tuple(float(x.strip().rstrip("FfDd")) for x in m.group(3).split(","))
            cur[2][-1][2].append((float(m.group(1)), m.group(2), nums, m.group(4)))
    return out


def to_units(kind, v):
    if kind == "degreeVec":
        return [math.radians(c) for c in v]
    if kind == "posVec":
        return [v[0], -v[1], v[2]]
    return [c - 1.0 for c in v]


def catmull(t, p0, p1, p2, p3):
    return 0.5 * (2 * p1 + (p2 - p0) * t + (2 * p0 - 5 * p1 + 4 * p2 - p3) * t * t + (3 * p1 - p0 - 3 * p2 + p3) * t ** 3)


def sample(keys, seconds, weight):
    vals = [to_units(k[1], k[2]) for k in keys]
    n = len(keys)
    first = n
    for i, k in enumerate(keys):
        if seconds <= k[0]:
            first = i
            break
    prev = max(0, first - 1)
    nxt = min(n - 1, prev + 1)
    alpha = 0.0
    if nxt != prev:
        alpha = min(1.0, max(0.0, (seconds - keys[prev][0]) / (keys[nxt][0] - keys[prev][0])))
    out = []
    for axis in range(3):
        if keys[nxt][3] == "LINEAR":
            v = vals[prev][axis] + (vals[nxt][axis] - vals[prev][axis]) * alpha
        else:
            p0 = vals[max(0, prev - 1)][axis]
            p3 = vals[min(n - 1, nxt + 1)][axis]
            v = catmull(alpha, p0, vals[prev][axis], vals[nxt][axis], p3)
        out.append(v * weight)
    return out


def main():
    lines = ["# anim channel bone target millis weight x y z (generated by scripts/keyframe-oracle.py)"]
    cache = {}
    for file, const, variant in WANTED:
        if file not in cache:
            cache[file] = read_definitions(DEFS / (file + ".java"))
        length, looping, channels = cache[file][const]
        for ms in TIMES_MS:
            seconds = ms / 1000.0
            if looping and length > 0:
                seconds = math.fmod(seconds, length)
            elif looping:
                continue  # a zero-length loop has no defined clock
            for weight in ([1.0, 0.5] if ms == HALF_WEIGHT_MS else [1.0]):
                for index, (bone, target, keys) in enumerate(channels):
                    x, y, z = sample(keys, seconds, weight)
                    lines.append("%s %d %s %s %d %g %.9g %.9g %.9g" % (variant, index, bone, target, ms, weight, x, y, z))
    OUT.write_text("\n".join(lines) + "\n")
    print("wrote", len(lines) - 1, "samples")


main()
