#!/usr/bin/env python3
"""Rebuild the datapack data `lodestone-server` bundles, from the current release's
decompiled client data (`.cache/mc/<mc-version>/client-src/data/minecraft`).

Recipes: only the types the server's matchers consume (crafting_shaped,
crafting_shapeless, stonecutting). Item tags and stored loot predicates are copied
whole. Loot tables are regenerated by `just regen-loot-corpus`, whose test decides
which tables the loader supports. See docs/server-data.md.
"""
import json
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import mc_version  # noqa: E402

DATA = mc_version.cache_root() / "client-src/data/minecraft"
ASSETS = mc_version.ROOT / "crates/lodestone-server/assets"
RECIPE_TYPES = {"minecraft:crafting_shaped", "minecraft:crafting_shapeless", "minecraft:stonecutting"}


def refresh(dst: Path, files):
    if dst.exists():
        shutil.rmtree(dst)
    n = 0
    for rel, text in files:
        out = dst / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text.rstrip("\n") + "\n")
        n += 1
    print(f"{dst.relative_to(mc_version.ROOT)}: {n} files")


def tree(src: Path, keep=lambda doc: True):
    for p in sorted(src.rglob("*.json")):
        text = p.read_text()
        if keep(json.loads(text)):
            yield p.relative_to(src), text


if not DATA.is_dir():
    sys.exit(f"{DATA} is absent: fetch and decompile the release first (docs/mc-version-bump.md)")
refresh(ASSETS / "recipe", tree(DATA / "recipe", lambda d: d.get("type") in RECIPE_TYPES))
refresh(ASSETS / "tags/item", tree(DATA / "tags/item"))
refresh(ASSETS / "predicate", tree(DATA / "predicate"))
