//! Embeds the bundled singleplayer worldgen data (`assets/worldgen/`) into the
//! binary as an `include_str!` table.
//!
//! The integrated server ships a default overworld so singleplayer needs no
//! external files. This is the shape+surface subset of the 26.2 vanilla data
//! (noise settings + density functions + noises); per plan §3 the eventual home
//! for version-specific worldgen data is the version crate, and this bundled
//! copy is the singleplayer default the direct-call path consumes today.
//!
//! The generated file (`$OUT_DIR/embedded_worldgen.rs`) is a sorted
//! `&[(&str, &str)]` of `(relative-id-without-extension, file-contents)`, keyed
//! by path under `assets/worldgen/` with forward slashes (e.g.
//! `"density_function/overworld/final_density"`, `"noise/continentalness"`,
//! `"noise_settings/overworld"`). Sorting keeps the output deterministic and
//! independent of `read_dir` order.

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let assets = Path::new(env!("CARGO_MANIFEST_DIR")).join("assets/worldgen");
    println!("cargo::rerun-if-changed=assets/worldgen");

    let mut entries = Vec::new();
    collect(&assets, &assets, &mut entries);
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::from(
        "// @generated by build.rs — do not edit.\n\
         /// `(id, contents)` for every bundled worldgen JSON, sorted by id.\n\
         pub static EMBEDDED_WORLDGEN: &[(&str, &str)] = &[\n",
    );
    for (id, path) in &entries {
        let path = path.to_string_lossy().replace('\\', "\\\\");
        code.push_str(&format!("    ({id:?}, include_str!(\"{path}\")),\n"));
    }
    code.push_str("];\n");

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("embedded_worldgen.rs");
    fs::write(&out, code).unwrap();

    // Issue #337: the bundled loot-table subset lives under `assets/loot_table/`
    // and is embedded the same way, into its own generated table so the
    // worldgen table above stays byte-identical.
    println!("cargo::rerun-if-changed=assets/loot_table");
    let loot = Path::new(env!("CARGO_MANIFEST_DIR")).join("assets/loot_table");
    let mut loot_entries = Vec::new();
    if loot.is_dir() {
        collect(&loot, &loot, &mut loot_entries);
    }
    loot_entries.sort_by(|a, b| a.0.cmp(&b.0));
    let mut loot_code = String::from(
        "// @generated by build.rs — do not edit.\n\
         /// `(id, contents)` for every bundled loot-table JSON, sorted by id.\n\
         /// Ids are relative to `assets/loot_table/` with the `.json` stripped\n\
         /// (`blocks/dirt`), so the full table id is `minecraft:blocks/dirt`.\n\
         pub static EMBEDDED_LOOT: &[(&str, &str)] = &[\n",
    );
    for (id, path) in &loot_entries {
        let path = path.to_string_lossy().replace('\\', "\\\\");
        loot_code.push_str(&format!("    ({id:?}, include_str!(\"{path}\")),\n"));
    }
    loot_code.push_str("];\n");

    let loot_out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("embedded_loot.rs");
    fs::write(&loot_out, loot_code).unwrap();

    // The structure templates the S2 worldgen unit places (shipwreck, ocean
    // ruins, igloo, and the jigsaw pools S4 will want). Binary, so `include_bytes!`
    // rather than `include_str!` — all 1,212 of them, ~3.4 MiB of rodata.
    //
    // Without this table `EmbeddedResolver` takes `Resolver::structure_template`'s
    // `None` default and every template-driven structure is **demoted to
    // `Unsupported`** in the worldgen ledger: the structure start is placed, the
    // blocks are not.
    println!("cargo::rerun-if-changed=assets/structure");
    let structures = Path::new(env!("CARGO_MANIFEST_DIR")).join("assets/structure");
    let mut structure_entries = Vec::new();
    if structures.is_dir() {
        collect_ext(&structures, &structures, "nbt", &mut structure_entries);
    }
    // Sorted because the lookup is a `binary_search_by` — an unsorted table does
    // not fail loudly, it silently misses.
    structure_entries.sort_by(|a, b| a.0.cmp(&b.0));
    let mut structure_code = String::from(
        "// @generated by build.rs — do not edit.\n\
         /// `(id, bytes)` for every bundled structure template, sorted by id.\n\
         /// Ids are relative to `assets/structure/` with the `.nbt` stripped\n\
         /// (`shipwreck/with_mast`), so the full template id is\n\
         /// `minecraft:shipwreck/with_mast`.\n\
         pub static EMBEDDED_STRUCTURE_TEMPLATES: &[(&str, &[u8])] = &[\n",
    );
    for (id, path) in &structure_entries {
        let path = path.to_string_lossy().replace('\\', "\\\\");
        structure_code.push_str(&format!("    ({id:?}, include_bytes!(\"{path}\")),\n"));
    }
    structure_code.push_str("];\n");

    let structure_out =
        PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("embedded_structures.rs");
    fs::write(&structure_out, structure_code).unwrap();

    // Issue #529: the crafting corpus the server re-derives a crafting result
    // from. `assets/recipe/` is vanilla 26.2's `crafting_shaped` +
    // `crafting_shapeless` set plus (issue #150) the `stonecutting` set —
    // 1,375 files total, the only three recipe types this crate's own
    // matchers consume — and `assets/tags/item/` is the 224 item tags their
    // ingredients reference. **Both, or neither**: a recipe whose ingredient
    // is `#planks` matches nothing without the tag, and a corpus that
    // silently drops recipes rejects valid crafts — which is worse than the
    // trust it replaces.
    for (dir, table, doc) in [
        (
            "assets/recipe",
            "EMBEDDED_RECIPES",
            "every bundled crafting recipe JSON (`crafting_shaped` + \
             `crafting_shapeless` + `stonecutting`), sorted by id",
        ),
        (
            "assets/tags/item",
            "EMBEDDED_ITEM_TAGS",
            "every bundled `minecraft:item` tag JSON, sorted by id",
        ),
    ] {
        println!("cargo::rerun-if-changed={dir}");
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).join(dir);
        let mut entries = Vec::new();
        if root.is_dir() {
            collect(&root, &root, &mut entries);
        }
        entries.sort_by(|a, b| a.0.cmp(&b.0));
        let mut code = format!(
            "// @generated by build.rs — do not edit.\n\
             /// `(id, contents)` for {doc}.\n\
             pub static {table}: &[(&str, &str)] = &[\n"
        );
        for (id, path) in &entries {
            let path = path.to_string_lossy().replace('\\', "\\\\");
            code.push_str(&format!("    ({id:?}, include_str!(\"{path}\")),\n"));
        }
        code.push_str("];\n");
        let out = PathBuf::from(std::env::var("OUT_DIR").unwrap())
            .join(format!("embedded_{}.rs", table.to_lowercase()));
        fs::write(&out, code).unwrap();
    }
}

/// Recursively collects `*.json` files under `dir`, keyed by their path relative
/// to `root` (extension stripped, forward slashes).
fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    collect_ext(root, dir, "json", out);
}

/// [`collect`], for any single extension.
fn collect_ext(root: &Path, dir: &Path, ext: &str, out: &mut Vec<(String, PathBuf)>) {
    let mut children: Vec<_> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("reading {}: {e}", dir.display()))
        .map(|e| e.unwrap().path())
        .collect();
    children.sort();
    for path in children {
        if path.is_dir() {
            collect_ext(root, &path, ext, out);
        } else if path.extension().is_some_and(|x| x == ext) {
            let rel = path.strip_prefix(root).unwrap().with_extension("");
            let id = rel.to_string_lossy().replace('\\', "/");
            let abs = path
                .canonicalize()
                .unwrap_or_else(|e| panic!("canonicalizing {}: {e}", path.display()));
            out.push((id, abs));
        }
    }
}
