//! Entity-type id→name tables for this era's three protocols: hermetic
//! checks over the committed tables, plus `#[ignore]`d drift guards that
//! regenerate them from their own sources and assert byte-for-byte equality
//! (modelled on the v26-2 entity-type table and the packet-id generator).
//!
//! # Three tables, two sources
//!
//! The registry is dense and alphabetical, so any insertion renumbers
//! everything after it: 1.15 added the bee at id 4 and 1.16 added four nether
//! mobs, leaving 102 / 103 / 108 entries that agree only on ids 0..=3. The
//! 498 and 578 tables are generated from each jar's own `--reports` registry
//! dump, committed under `tests/support/` — an authority. The 754 table
//! predates those dumps here and still comes from `minecraft-data`, a
//! cross-check; it is left on that source rather than regenerated, so this
//! work cannot silently move it.
//!
//! 1.13 flattening **unified** the entity registry: 1.12's two id spaces (a
//! `spawn_mob` mob table and a `spawn_object` object table) collapsed into a
//! single numeric registry that both `spawn_entity` and `spawn_entity_living`
//! index. So there is exactly one table here, not two. The oracle is
//! `minecraft-data` (`vendor/minecraft-data/data/pc/1.16.2/entities.json`,
//! which 1.16.5 shares per `dataPaths.json`; gitignored).
//!
//! `minecraft-data`'s 1.16 `name` fields are already lowercase snake_case, so
//! there is no casing judgement. The `type` field is unreliable in this dump
//! (several 1.16 mobs are tagged `UNKNOWN`), so the generator keys off `id`
//! and includes every entry rather than filtering by category.
//!
//! Regenerate the committed tables after a data bump with:
//!
//! ```text
//! LODESTONE_REGEN=1 cargo test -p lodestone-v1-14 --test entity_types \
//!     committed -- --ignored --nocapture
//! ```

use std::fmt::Write as _;
use std::path::PathBuf;

use lodestone_v1_14::entity_types;
use lodestone_v1_14::{PROTOCOL_1_14_4, PROTOCOL_1_15_2, PROTOCOL_1_16_5};

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Vendored community data (gitignored local artifact). 1.16.5 shares
/// 1.16.2's entity registry per `minecraft-data`'s `dataPaths.json`.
fn source_path() -> PathBuf {
    manifest_dir().join("../../../vendor/minecraft-data/data/pc/1.16.2/entities.json")
}

fn committed_path() -> PathBuf {
    manifest_dir().join("src/generated/entity_types.rs")
}

/// One jar-sourced table: the unmodified `--reports` registry dump and where
/// its rendered table is committed.
struct JarSource {
    minecraft: &'static str,
    protocol: i32,
    dump: &'static str,
    dump_file: &'static str,
    committed: &'static str,
}

const JAR_SOURCES: &[JarSource] = &[
    JarSource {
        minecraft: "1.14.4",
        protocol: PROTOCOL_1_14_4,
        dump: include_str!("support/registries_1_14_4_jar.json"),
        dump_file: "registries_1_14_4_jar.json",
        committed: "src/generated/entity_types_498.rs",
    },
    JarSource {
        minecraft: "1.15.2",
        protocol: PROTOCOL_1_15_2,
        dump: include_str!("support/registries_1_15_2_jar.json"),
        dump_file: "registries_1_15_2_jar.json",
        committed: "src/generated/entity_types_578.rs",
    },
];

/// Parses `minecraft:entity_type` out of a `--reports` registry dump into the
/// same sorted `(id, identifier)` shape [`parse_entities`] produces from
/// `minecraft-data`.
///
/// The report's own `protocol_id` is authoritative and the identifiers are
/// already namespaced, so unlike the `minecraft-data` path there is no
/// casing or prefixing judgement at all.
fn parse_registry_entities(doc: &str) -> Vec<(i32, String)> {
    let value: serde_json::Value = serde_json::from_str(doc).expect("registries.json parses");
    let entries = value["minecraft:entity_type"]["entries"]
        .as_object()
        .expect("registries.json carries minecraft:entity_type entries");
    let mut pairs: Vec<(i32, String)> = entries
        .iter()
        .map(|(name, entry)| {
            let id = entry["protocol_id"]
                .as_i64()
                .expect("entry has an integer protocol_id") as i32;
            (id, name.clone())
        })
        .collect();
    pairs.sort_by_key(|(id, _)| *id);
    for (index, (id, _)) in pairs.iter().enumerate() {
        assert_eq!(
            *id as usize, index,
            "entity_type protocol ids are not dense from 0"
        );
    }
    pairs
}

/// Renders one jar-sourced table.
fn generate_from_jar(source: &JarSource, pairs: &[(i32, String)]) -> String {
    let JarSource {
        minecraft,
        protocol,
        dump_file,
        ..
    } = *source;

    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo test -p lodestone-v1-14 --test entity_types -- --ignored`\n",
    );
    let _ = writeln!(out, "// from tests/support/{dump_file} (protocol {protocol} /");
    let _ = writeln!(
        out,
        "// Minecraft {minecraft}). DO NOT EDIT BY HAND. Regenerate with LODESTONE_REGEN=1"
    );
    out.push_str("// (see the test module docs).\n");
    let _ = writeln!(
        out,
        "//! Generated entity-type id->name table for protocol {protocol} (Minecraft {minecraft}).\n//!"
    );
    out.push_str(
        "//! Maps the unified numeric entity-type id space to canonical\n\
         //! `minecraft:*` identifiers. Consumed by [`crate::entity_types`].\n\n",
    );
    render_table(&mut out, "ENTITY_TYPES", "ENTITY_TYPE_COUNT", pairs);
    out
}

// ---------------------------------------------------------------------------
// Generator (shared by regen and the drift check)
// ---------------------------------------------------------------------------

/// Converts a `minecraft-data` name to a canonical lowercase path: spaces
/// become underscores and CamelCase word boundaries gain an underscore. For
/// 1.16 this is a no-op on every name, but it is kept for defensiveness.
fn snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    let mut prev_lower_or_digit = false;
    for ch in name.chars() {
        if ch == ' ' || ch == '-' {
            if !out.ends_with('_') && !out.is_empty() {
                out.push('_');
            }
            prev_lower_or_digit = false;
            continue;
        }
        if ch.is_ascii_uppercase() {
            if prev_lower_or_digit {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
            prev_lower_or_digit = false;
        } else {
            out.push(ch);
            prev_lower_or_digit = ch.is_ascii_lowercase() || ch.is_ascii_digit();
        }
    }
    out
}

/// Parses `entities.json` into a sorted `(id, identifier)` table over the
/// whole unified registry (every entry, keyed by `id`).
fn parse_entities(doc: &serde_json::Value) -> Vec<(i32, String)> {
    let entries = doc.as_array().expect("entities.json is an array");
    let mut pairs: Vec<(i32, String)> = entries
        .iter()
        .map(|entry| {
            let id = entry
                .get("id")
                .and_then(serde_json::Value::as_i64)
                .expect("entity entry has an integer id") as i32;
            let name = entry
                .get("name")
                .and_then(serde_json::Value::as_str)
                .expect("entity entry has a name");
            (id, format!("minecraft:{}", snake_case(name)))
        })
        .collect();
    pairs.sort_by_key(|(id, _)| *id);
    for window in pairs.windows(2) {
        assert_ne!(
            window[0].0, window[1].0,
            "duplicate entity id {} in entities.json",
            window[0].0
        );
    }
    pairs
}

fn render_table(out: &mut String, const_name: &str, count_name: &str, pairs: &[(i32, String)]) {
    let _ = writeln!(
        out,
        "/// Number of {} type entries.",
        const_name.to_lowercase()
    );
    let _ = writeln!(out, "pub const {count_name}: usize = {};\n", pairs.len());
    let _ = writeln!(
        out,
        "/// `(type id, canonical identifier)` pairs, sorted by id for binary search."
    );
    let _ = writeln!(
        out,
        "pub static {const_name}: [(i32, &str); {}] = [",
        pairs.len()
    );
    for (id, name) in pairs {
        let _ = writeln!(out, "    ({id}, \"{name}\"),");
    }
    out.push_str("];\n\n");
}

fn generate(doc: &serde_json::Value) -> String {
    let entities = parse_entities(doc);

    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo test -p lodestone-v1-14 --test entity_types -- --ignored`\n\
         // from vendor/minecraft-data/data/pc/1.16.2/entities.json (protocol 754 /\n\
         // Minecraft 1.16.5). DO NOT EDIT BY HAND. Regenerate with LODESTONE_REGEN=1\n\
         // (see the test module docs).\n",
    );
    out.push_str(
        "//! Generated entity-type id->name table for protocol 754 (Minecraft 1.16.5).\n//!\n",
    );
    out.push_str(
        "//! Maps the unified 1.16 numeric entity-type id space to canonical\n\
         //! `minecraft:*` identifiers. Consumed by [`crate::entity_types`].\n\n",
    );

    render_table(&mut out, "ENTITY_TYPES", "ENTITY_TYPE_COUNT", &entities);

    out
}

// ---------------------------------------------------------------------------
// Hermetic tests over the committed table (no source needed)
// ---------------------------------------------------------------------------

#[test]
fn tables_are_non_empty_and_out_of_range_is_none() {
    for protocol in [PROTOCOL_1_14_4, PROTOCOL_1_15_2, PROTOCOL_1_16_5] {
        let table = entity_types::table_for(protocol);
        assert!(table.entity_type_name(12).is_some(), "entity table populated");
        assert_eq!(table.entity_type_name(-1), None);
        assert_eq!(table.entity_type_name(i32::MAX), None);
        // The mob/object aliases resolve through the same unified table.
        assert_eq!(table.mob_type_name(-1), None);
        assert_eq!(table.object_type_name(i32::MAX), None);
        // The rendered count and the rendered array must agree; a hand edit
        // to one half of a generated file is what this catches.
        assert_eq!(table.declared_len(), table.len());
        assert!(!table.is_empty());
    }
}

/// The three registries are genuinely different, and the difference is the
/// kind that produces a real-but-wrong answer rather than an error.
///
/// Ids 0..=3 agree across the era (nothing was inserted before the bat), so
/// the probes are chosen past that: 1.15 inserted the bee at 4 and 1.16 the
/// hoglin at 32. A shared table would name a plausible mob for every spawn
/// packet in the other two protocols.
#[test]
fn the_three_registries_disagree_about_what_a_type_id_means() {
    let name = |protocol: i32, id: i32| {
        entity_types::table_for(protocol)
            .entity_type_name(id)
            .expect("every era member carries these ids")
    };
    assert_eq!(
        [name(PROTOCOL_1_14_4, 4), name(PROTOCOL_1_15_2, 4), name(PROTOCOL_1_16_5, 4)],
        ["minecraft:blaze", "minecraft:bee", "minecraft:bee"]
    );
    assert_eq!(
        [name(PROTOCOL_1_14_4, 32), name(PROTOCOL_1_15_2, 32), name(PROTOCOL_1_16_5, 32)],
        ["minecraft:husk", "minecraft:horse", "minecraft:hoglin"]
    );
    // Counts, measured from the three registries.
    assert_eq!(entity_types::table_for(PROTOCOL_1_14_4).len(), 102);
    assert_eq!(entity_types::table_for(PROTOCOL_1_15_2).len(), 103);
    assert_eq!(entity_types::table_for(PROTOCOL_1_16_5).len(), 108);
}

#[test]
fn known_ids_resolve_to_well_formed_identifiers() {
    // Spot 1.16 unified ids the live seam relies on; a transposed table fails
    // instantly.
    let table = entity_types::table_for(PROTOCOL_1_16_5);
    assert_eq!(table.entity_type_name(12), Some("minecraft:creeper"));
    assert_eq!(table.entity_type_name(59), Some("minecraft:pig"));
    assert_eq!(table.entity_type_name(102), Some("minecraft:zombie"));
    assert_eq!(table.entity_type_name(2), Some("minecraft:arrow"));
    assert_eq!(table.entity_type_name(6), Some("minecraft:boat"));
    assert_eq!(table.entity_type_name(106), Some("minecraft:player"));
    // Both spawn aliases index the unified registry in 1.16.
    assert_eq!(table.mob_type_name(59), Some("minecraft:pig"));
    assert_eq!(table.object_type_name(6), Some("minecraft:boat"));
    assert_eq!(entity_types::PLAYER, "minecraft:player");
}

#[test]
fn identifiers_have_lowercase_paths() {
    for protocol in [PROTOCOL_1_14_4, PROTOCOL_1_15_2, PROTOCOL_1_16_5] {
    let table = entity_types::table_for(protocol);
    for id in 0..256 {
        if let Some(name) = table.entity_type_name(id) {
            let path = name
                .strip_prefix("minecraft:")
                .expect("namespaced identifier");
            assert!(!path.is_empty(), "id {id} has an empty path");
            assert!(
                path.chars().all(|c| c.is_ascii_lowercase()
                    || c.is_ascii_digit()
                    || matches!(c, '_' | '.' | '-' | '/')),
                "id {id} identifier {name:?} has an invalid path character"
            );
            let _key: lodestone_model::ResourceKey = name.parse().expect("valid resource key");
        }
    }
    }
}

// ---------------------------------------------------------------------------
// Drift guard (needs the vendored source; #[ignore]d so the suite stays hermetic)
// ---------------------------------------------------------------------------

#[test]
#[ignore = "reads the gitignored vendor/minecraft-data; run explicitly to regen/verify"]
fn committed_tables_match_source() {
    let raw = std::fs::read_to_string(source_path())
        .expect("entities.json present under vendor/minecraft-data/data/pc/1.16.2");
    let doc: serde_json::Value = serde_json::from_str(&raw).expect("entities.json parses");
    let generated = generate(&doc);

    if std::env::var_os("LODESTONE_REGEN").is_some() {
        std::fs::write(committed_path(), &generated).expect("write committed tables");
        eprintln!("regenerated {}", committed_path().display());
        return;
    }

    let committed = std::fs::read_to_string(committed_path()).expect("committed tables present");
    assert_eq!(
        generated, committed,
        "src/generated/entity_types.rs is stale vs entities.json; regenerate with LODESTONE_REGEN=1"
    );

    let entities = parse_entities(&doc);
    let table = entity_types::table_for(PROTOCOL_1_16_5);
    assert_eq!(entities.len(), table.len(), "entity count mismatch");
    let mut mismatches = 0usize;
    for (id, name) in &entities {
        if table.entity_type_name(*id) != Some(name.as_str()) {
            mismatches += 1;
        }
    }
    println!("=== ENTITY-TYPE TABLE REPORT (protocol 754) ===");
    println!("entity types : {}", table.len());
    println!("mismatches   : {mismatches}");
    println!("===============================================");
    assert_eq!(
        mismatches, 0,
        "committed table disagrees with entities.json"
    );
}

/// Drift guard for the two jar-sourced tables. Hermetic apart from writing:
/// the dumps are committed and `include_str!`d, unlike the 754 guard above
/// which reads the gitignored vendor tree.
#[test]
#[ignore = "regenerates/verifies the committed jar-sourced tables; run explicitly"]
fn committed_jar_tables_match_dumps() {
    let regen = std::env::var_os("LODESTONE_REGEN").is_some();
    for source in JAR_SOURCES {
        let pairs = parse_registry_entities(source.dump);
        let generated = generate_from_jar(source, &pairs);
        let path = manifest_dir().join(source.committed);

        if regen {
            std::fs::write(&path, &generated).expect("write committed table");
            eprintln!("regenerated {} ({} entries)", path.display(), pairs.len());
            continue;
        }

        let committed = std::fs::read_to_string(&path).expect("committed table present");
        assert_eq!(
            generated,
            committed,
            "{} is stale vs tests/support/{}; regenerate with LODESTONE_REGEN=1",
            source.committed,
            source.dump_file
        );

        let table = entity_types::table_for(source.protocol);
        assert_eq!(pairs.len(), table.len(), "{}: entity count mismatch", source.minecraft);
        for (id, name) in &pairs {
            assert_eq!(
                table.entity_type_name(*id),
                Some(name.as_str()),
                "{}: id {id} disagrees with the jar registry",
                source.minecraft
            );
        }
    }
}
