//! **The experience orb's one synchronised field, on the wire.**
//!
//! An orb tells a client exactly one thing about itself: `vanilla's own experience orb's own value`.
//! `ExperienceOrbRenderer` picks one of eleven sprite frames from
//! `vanilla's own experience orb's own get icon`, which buckets that value — so an orb whose value never
//! arrives draws frame 0, the smallest, whatever it is worth. `defineSynchedData`
//! registers `DATA_VALUE` and nothing else, and `ExperienceOrb` does not override
//! `getAddEntityPacket`, so entity metadata is the *only* channel; there is no object
//! data to fall back on.
//!
//! # Where the expected bytes come from
//!
//! The `EntityDataIndexOracle` dump already committed in this crate
//! (`tests/support/entity_data_index_jvm.txt`), which is generated by booting the real
//! 26.2 server and reflecting over every `EntityDataAccessor`:
//!
//! ```text
//! 8 vanilla's own experience orb's own value 1 INT
//! ```
//!
//! Index `8`, serializer id `1`. Neither number is hand-counted — CLAUDE.md records two
//! shipped bugs (`vanilla's own sheep's own wool`, `vanilla's own horse's own id type variant`) from counting
//! `defineId` calls by eye, which is what that dump exists to prevent.
//!
//! # The index-8 collision this file is really about
//!
//! Index 8 is the most crowded index in the dump — nineteen claimants. Two of them are
//! produced by this server: `vanilla's own item entity's own item` (serializer `7`, `ITEM_STACK`) and
//! `vanilla's own experience orb's own value` (serializer `1`, `INT`). The encoder cannot tell them
//! apart from the index, only from the `MetadataField` variant it was handed — so the
//! guard is on the *producer*: `MobSim::snapshots` builds `Item` in its item loop and
//! `ExperienceOrbValue` in its orb loop, and never crosses them.
//!
//! What that leaves for a gate is the thing an encoder bug would actually produce: the
//! same index with the **wrong serializer**, which is wire-legal and makes the client
//! read an item stack out of a VarInt. The assertions below therefore check the
//! serializer byte explicitly rather than only the index, and include the item field
//! alongside to show the two do not collapse into one another.

use lodestone_server::{MetadataField, MobSim, ServerDirective, ServerProtocol};
use lodestone_v770::V770ServerProtocol;
use lodestone_v770::packet_ids::play;

/// The index and serializer id the JVM dump reports for `vanilla's own experience orb's own value`.
const ORB_VALUE_INDEX: u8 = 8;
const SERIALIZER_INT: u8 = 1;
/// `vanilla's own item entity's own item`'s serializer, at the same index — the collision.
const SERIALIZER_ITEM_STACK: u8 = 7;
/// `metadata.rs`' `EOF_MARKER`, which terminates every field list.
const METADATA_EOF: u8 = 0xFF;

fn payload_of(directive: ServerDirective, expected_id: i32) -> Vec<u8> {
    match directive {
        ServerDirective::Send { packet_id, payload } => {
            assert_eq!(packet_id, expected_id, "wrong packet id");
            payload
        }
        other => panic!("expected a Send directive, got {other:?}"),
    }
}

/// The orb's value reaches the wire at index 8 with the `INT` serializer.
///
/// `617` is a real ladder denomination and the threshold for sprite frame 8, so it is
/// also a value whose *icon* changes if the number is mangled. It is above 127, which
/// makes its VarInt two bytes — a single-byte value would hide a length bug.
#[test]
fn an_orb_value_encodes_at_index_eight_with_the_int_serializer() {
    let proto = V770ServerProtocol;
    let payload = payload_of(
        proto.encode_set_entity_data(
            42,
            &[MetadataField::ExperienceOrbValue { value: 617 }],
        ),
        play::clientbound::SET_ENTITY_DATA,
    );
    // VarInt entity id 42, then (index, serializer, value), then the sentinel.
    // 617 = 0b10_1001001 -> VarInt `0xE9 0x04`.
    assert_eq!(
        payload,
        vec![42, ORB_VALUE_INDEX, SERIALIZER_INT, 0xE9, 0x04, METADATA_EOF],
        "index 8 / serializer 1 / VarInt 617, in that order"
    );
}

/// **The collision, both arms in one gate.** Same index, different serializer.
///
/// An encoder that reached the item arm for an orb (or vice versa) would emit a
/// wire-legal packet the client mis-parses, and the index alone cannot see it. Asserted
/// as an inequality on the serializer byte at the same position, plus the equality that
/// the index really is shared — so this fails if a future change silently moves either
/// field to a different index and stops the two from colliding at all.
#[test]
fn the_orb_value_and_the_item_stack_share_index_eight_and_differ_by_serializer() {
    let proto = V770ServerProtocol;
    let orb = payload_of(
        proto.encode_set_entity_data(1, &[MetadataField::ExperienceOrbValue { value: 1 }]),
        play::clientbound::SET_ENTITY_DATA,
    );
    let item = payload_of(
        proto.encode_set_entity_data(
            1,
            &[MetadataField::Item {
                item: "minecraft:diamond".parse().expect("valid key"),
                count: 1,
            }],
        ),
        play::clientbound::SET_ENTITY_DATA,
    );
    assert_eq!(
        (orb[1], item[1]),
        (ORB_VALUE_INDEX, ORB_VALUE_INDEX),
        "both fields are index 8 — if this fails they no longer collide and this gate's \
         premise is gone"
    );
    assert_eq!(orb[2], SERIALIZER_INT, "the orb value is an INT");
    assert_eq!(item[2], SERIALIZER_ITEM_STACK, "the item is an ITEM_STACK");
    assert_ne!(
        orb[2], item[2],
        "the serializer is the only thing separating two fields at the same index"
    );
}

/// **The entity type resolves to a real registry key**, which is the other way an orb
/// can arrive as something else entirely.
///
/// `encode_add_entity_body` resolves the type name with `entity_type_id(name)
/// .unwrap_or(0)`, and network entity type `0` is `minecraft:acacia_boat` — the exact
/// bug that made every dropped item this server ever spawned arrive as a boat, with
/// nothing logged and every connectedness wire reading green. So the assertion is that
/// the orb's id is resolvable *and* is not `0`.
#[test]
fn the_orb_entity_type_is_not_the_unresolved_zero_that_means_acacia_boat() {
    let orb = lodestone_data::entity_types::entity_type_id("minecraft:experience_orb")
        .expect("`minecraft:experience_orb` must be in the 26.2 entity-type registry");
    assert_ne!(
        orb, 0,
        "entity type 0 is minecraft:acacia_boat — a zero here means the key did not \
         resolve and every orb would arrive as a boat"
    );
    // The control: a name that genuinely is not an entity type resolves to nothing,
    // rather than to some plausible id. Without this, the assertion above could be
    // satisfied by a lookup that answers for anything.
    assert_eq!(
        lodestone_data::entity_types::entity_type_id("minecraft:experience"),
        None,
        "the lookup must miss on a non-entity name, or it proves nothing about the hit"
    );
}

/// An orb built by a real [`MobSim`] streams with the type and the field, and the
/// **whole snapshot** — not a hand-assembled one — is what the encoder is handed.
///
/// This is the join the two gates above cannot make: they prove the encoder writes the
/// right bytes for a field, and this proves the field is actually produced. A `MobSim`
/// that spawned orbs and streamed them with an empty metadata list would pass every
/// byte assertion in this file.
#[test]
fn a_real_sim_orb_reaches_the_encoder_with_its_value() {
    let world = lodestone_server::ChunkWorld::new(-64, 384);
    let mut sim = MobSim::new(&world);
    let id = sim.spawn_orb(
        149,
        lodestone_model::Vec3::new(0.5, 65.0, 0.5),
        lodestone_model::Vec3::new(0.0, 0.0, 0.0),
    );
    let snapshot = sim
        .snapshots()
        .into_iter()
        .find(|s| s.id == id)
        .expect("a live orb must be streamed");
    assert_eq!(snapshot.entity_type.to_string(), "minecraft:experience_orb");

    let payload = payload_of(
        V770ServerProtocol.encode_set_entity_data(snapshot.id, &snapshot.metadata),
        play::clientbound::SET_ENTITY_DATA,
    );
    assert_eq!(
        (payload[1], payload[2]),
        (ORB_VALUE_INDEX, SERIALIZER_INT),
        "the sim's own snapshot must encode as index 8 / INT"
    );
    // 149 = 0b1_0010101 -> VarInt `0x95 0x01`.
    assert_eq!(
        &payload[3..5],
        &[0x95, 0x01],
        "and must carry 149, the value the orb was spawned with"
    );
}
