//! Drift guard for the protocol-766 item, attribute, and block registries.
//!
//! The source report is jar-produced and test-only; this module renders the
//! production table so adapter code never needs to load test assets at runtime.

use std::fmt::Write as _;
use std::path::PathBuf;

use lodestone_v1_20_6::registry;

const DUMP: &str = include_str!("support/registries_1_20_6_jar.json");
const COMMITTED: &str = "src/generated/registry.rs";

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn pairs(registry: &str) -> Vec<(i32, String)> {
    let value: serde_json::Value = serde_json::from_str(DUMP).expect("registry dump parses");
    let entries = value[registry]["entries"]
        .as_object()
        .expect("registry report carries entries");
    let mut pairs: Vec<_> = entries
        .iter()
        .map(|(name, entry)| {
            let id = i32::try_from(entry["protocol_id"].as_i64().expect("integer id"))
                .expect("id fits i32");
            (id, name.clone())
        })
        .collect();
    pairs.sort_by_key(|(id, _)| *id);
    for (expected, (id, _)) in pairs.iter().enumerate() {
        assert_eq!(*id as usize, expected, "{registry} ids are dense from zero");
    }
    pairs
}

fn table(out: &mut String, constant: &str, pairs: &[(i32, String)]) {
    let _ = writeln!(out, "pub static {constant}: [(i32, &str); {}] = [", pairs.len());
    for (id, name) in pairs {
        let _ = writeln!(out, "    ({id}, \"{name}\"),");
    }
    out.push_str("];\n\n");
}

fn render() -> String {
    let mut out = String::from(
        "// @generated by `cargo test -p lodestone-v1-20-6 --test registry_mappings -- --ignored`\n\
         // from tests/support/registries_1_20_6_jar.json (protocol 766 / Minecraft\n\
         // 1.20.6). DO NOT EDIT BY HAND.\n\
         // Regenerate with LODESTONE_REGEN=1 (see tests/registry_mappings.rs).\n\n\
         //! Generated protocol-766 registry id-to-name tables.\n\n",
    );
    table(&mut out, "ITEMS", &pairs("minecraft:item"));
    table(&mut out, "ATTRIBUTES", &pairs("minecraft:attribute"));
    table(&mut out, "BLOCKS", &pairs("minecraft:block"));
    out.pop();
    out
}

#[test]
fn jar_registry_shapes_are_pinned() {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in DUMP.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    assert_eq!(hash, 0x3d61_b3bd_a25f_6e48, "the jar registry report changed");
    assert_eq!(pairs("minecraft:item").len(), 1330);
    assert_eq!(pairs("minecraft:attribute").len(), 22);
    assert_eq!(pairs("minecraft:block").len(), 1060);
}

#[test]
#[ignore = "regenerates a committed table; run with --ignored"]
fn committed_table_matches_dump() {
    let rendered = render();
    let path = manifest_dir().join(COMMITTED);
    if std::env::var_os("LODESTONE_REGEN").is_some() {
        std::fs::write(&path, rendered).expect("write generated registry table");
        return;
    }
    assert_eq!(
        std::fs::read_to_string(path).expect("read generated registry table"),
        rendered
    );
}

#[test]
fn generated_tables_resolve_values_from_the_jar_dump() {
    assert_eq!(registry::item_name(1), Some("minecraft:stone"));
    assert_eq!(registry::item_name(1329), Some("minecraft:breeze_rod"));
    assert_eq!(registry::attribute_name(17), Some("minecraft:generic.movement_speed"));
    assert_eq!(registry::block_name(177), Some("minecraft:chest"));
    assert_eq!(registry::item_name(1330), None);
    assert_eq!(registry::attribute_name(22), None);
    assert_eq!(registry::block_name(1060), None);
}
